UPSTOX_ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyWENSTjgiLCJqdGkiOiI2N2NiY2E5MWYwODNkYzZlOWNhOTcwNmIiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaWF0IjoxNzQxNDA4OTEzLCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NDE0NzEyMDB9.yX2cJQrItOIYuLm_y4EWoB1Ol0LjS7_YOeyZvQAgOQs
server:
  port: 8083
spring:
  influx:
    url: https://us-east-1-1.aws.cloud2.influxdata.com
    token: 4Fc5No-DoOyj9q8hbAGjOQsAlgxFYOztiBWvWDwyHDJ2mnkh_LYYv9jZFEscKziP_pzXxCIozwHCsxwX3CbHcQ==
    org: Dev
    bucket: market_data
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: am-market-data-service
      auto-offset-reset: earliest

app:
  kafka:
    topic: am-stock-price-update

upstox:
  interval: I1
  auth:
    base-url: https://api.upstox.com/v2
    code: ${UPSTOX_CODE:uQsNUf}
    api-key: ${UPSTOX_API_KEY:48d1e335-09ad-4dc0-b955-4505c350d10b}
    secret-key: ${UPSTOX_SECRET_KEY:jqre481zf0}
    access-token: ${UPSTOX_ACCESS_TOKEN:your-default-token}
    redirect-uri: http://localhost:8080
    authorization-url: https://api-v2.upstox.com/login/authorization/dialog
    token-url: https://api-v2.upstox.com/login/authorization/token
    token-refresh-interval: 3600000
    scope: orders feed portfolio