/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.am.marketdata.api;

import com.am.marketdata.client.ApiClient;
import com.am.marketdata.client.ApiException;
import com.am.marketdata.client.ApiResponse;
import com.am.marketdata.client.Configuration;
import com.am.marketdata.client.Pair;

import com.am.marketdata.model.MarketDataUpdateV1;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class MarketDataPollingApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public MarketDataPollingApi() {
    this(Configuration.getDefaultApiClient());
  }

  public MarketDataPollingApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get connection status
   * Returns streaming connection status
   * @return Map&lt;String, Object&gt;
   * @throws ApiException if fails to make API call
   */
  public Map<String, Object> getConnectionStatus() throws ApiException {
    return getConnectionStatus(null);
  }

  /**
   * Get connection status
   * Returns streaming connection status
   * @param headers Optional headers to include in the request
   * @return Map&lt;String, Object&gt;
   * @throws ApiException if fails to make API call
   */
  public Map<String, Object> getConnectionStatus(Map<String, String> headers) throws ApiException {
    ApiResponse<Map<String, Object>> localVarResponse = getConnectionStatusWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Get connection status
   * Returns streaming connection status
   * @return ApiResponse&lt;Map&lt;String, Object&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Map<String, Object>> getConnectionStatusWithHttpInfo() throws ApiException {
    return getConnectionStatusWithHttpInfo(null);
  }

  /**
   * Get connection status
   * Returns streaming connection status
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Map&lt;String, Object&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Map<String, Object>> getConnectionStatusWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getConnectionStatusRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getConnectionStatus", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Map<String, Object>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Map<String, Object> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Map<String, Object>>() {});
        

        return new ApiResponse<Map<String, Object>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getConnectionStatusRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/polling/status";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Internal use for SDK generation
   * 
   * @return MarketDataUpdateV1
   * @throws ApiException if fails to make API call
   */
  public MarketDataUpdateV1 getUpdateSchema() throws ApiException {
    return getUpdateSchema(null);
  }

  /**
   * Internal use for SDK generation
   * 
   * @param headers Optional headers to include in the request
   * @return MarketDataUpdateV1
   * @throws ApiException if fails to make API call
   */
  public MarketDataUpdateV1 getUpdateSchema(Map<String, String> headers) throws ApiException {
    ApiResponse<MarketDataUpdateV1> localVarResponse = getUpdateSchemaWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Internal use for SDK generation
   * 
   * @return ApiResponse&lt;MarketDataUpdateV1&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MarketDataUpdateV1> getUpdateSchemaWithHttpInfo() throws ApiException {
    return getUpdateSchemaWithHttpInfo(null);
  }

  /**
   * Internal use for SDK generation
   * 
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MarketDataUpdateV1&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MarketDataUpdateV1> getUpdateSchemaWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getUpdateSchemaRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getUpdateSchema", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<MarketDataUpdateV1>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        MarketDataUpdateV1 responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MarketDataUpdateV1>() {});
        

        return new ApiResponse<MarketDataUpdateV1>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getUpdateSchemaRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/polling/schema/update";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Poll market data
   * Poll live market data for given symbols
   * @param symbols  (required)
   * @param timeFrame  (optional, default to 1m)
   * @param indexSymbol  (optional, default to false)
   * @return Map&lt;String, Object&gt;
   * @throws ApiException if fails to make API call
   */
  public Map<String, Object> pollMarketData(@javax.annotation.Nonnull String symbols, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean indexSymbol) throws ApiException {
    return pollMarketData(symbols, timeFrame, indexSymbol, null);
  }

  /**
   * Poll market data
   * Poll live market data for given symbols
   * @param symbols  (required)
   * @param timeFrame  (optional, default to 1m)
   * @param indexSymbol  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return Map&lt;String, Object&gt;
   * @throws ApiException if fails to make API call
   */
  public Map<String, Object> pollMarketData(@javax.annotation.Nonnull String symbols, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean indexSymbol, Map<String, String> headers) throws ApiException {
    ApiResponse<Map<String, Object>> localVarResponse = pollMarketDataWithHttpInfo(symbols, timeFrame, indexSymbol, headers);
    return localVarResponse.getData();
  }

  /**
   * Poll market data
   * Poll live market data for given symbols
   * @param symbols  (required)
   * @param timeFrame  (optional, default to 1m)
   * @param indexSymbol  (optional, default to false)
   * @return ApiResponse&lt;Map&lt;String, Object&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Map<String, Object>> pollMarketDataWithHttpInfo(@javax.annotation.Nonnull String symbols, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean indexSymbol) throws ApiException {
    return pollMarketDataWithHttpInfo(symbols, timeFrame, indexSymbol, null);
  }

  /**
   * Poll market data
   * Poll live market data for given symbols
   * @param symbols  (required)
   * @param timeFrame  (optional, default to 1m)
   * @param indexSymbol  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Map&lt;String, Object&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Map<String, Object>> pollMarketDataWithHttpInfo(@javax.annotation.Nonnull String symbols, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean indexSymbol, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = pollMarketDataRequestBuilder(symbols, timeFrame, indexSymbol, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("pollMarketData", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Map<String, Object>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Map<String, Object> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Map<String, Object>>() {});
        

        return new ApiResponse<Map<String, Object>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder pollMarketDataRequestBuilder(@javax.annotation.Nonnull String symbols, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean indexSymbol, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'symbols' is set
    if (symbols == null) {
      throw new ApiException(400, "Missing the required parameter 'symbols' when calling pollMarketData");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/polling/data";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "symbols";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("symbols", symbols));
    localVarQueryParameterBaseName = "timeFrame";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("timeFrame", timeFrame));
    localVarQueryParameterBaseName = "indexSymbol";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("indexSymbol", indexSymbol));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Subscribe to symbols
   * Subscribe to symbols for real-time updates
   * @param requestBody  (required)
   * @return Map&lt;String, Object&gt;
   * @throws ApiException if fails to make API call
   */
  public Map<String, Object> subscribe(@javax.annotation.Nonnull List<String> requestBody) throws ApiException {
    return subscribe(requestBody, null);
  }

  /**
   * Subscribe to symbols
   * Subscribe to symbols for real-time updates
   * @param requestBody  (required)
   * @param headers Optional headers to include in the request
   * @return Map&lt;String, Object&gt;
   * @throws ApiException if fails to make API call
   */
  public Map<String, Object> subscribe(@javax.annotation.Nonnull List<String> requestBody, Map<String, String> headers) throws ApiException {
    ApiResponse<Map<String, Object>> localVarResponse = subscribeWithHttpInfo(requestBody, headers);
    return localVarResponse.getData();
  }

  /**
   * Subscribe to symbols
   * Subscribe to symbols for real-time updates
   * @param requestBody  (required)
   * @return ApiResponse&lt;Map&lt;String, Object&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Map<String, Object>> subscribeWithHttpInfo(@javax.annotation.Nonnull List<String> requestBody) throws ApiException {
    return subscribeWithHttpInfo(requestBody, null);
  }

  /**
   * Subscribe to symbols
   * Subscribe to symbols for real-time updates
   * @param requestBody  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Map&lt;String, Object&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Map<String, Object>> subscribeWithHttpInfo(@javax.annotation.Nonnull List<String> requestBody, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = subscribeRequestBuilder(requestBody, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("subscribe", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Map<String, Object>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Map<String, Object> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Map<String, Object>>() {});
        

        return new ApiResponse<Map<String, Object>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder subscribeRequestBuilder(@javax.annotation.Nonnull List<String> requestBody, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'requestBody' is set
    if (requestBody == null) {
      throw new ApiException(400, "Missing the required parameter 'requestBody' when calling subscribe");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/polling/subscribe";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(requestBody);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Unsubscribe from symbols
   * Unsubscribe from symbols
   * @param requestBody  (required)
   * @return Map&lt;String, Object&gt;
   * @throws ApiException if fails to make API call
   */
  public Map<String, Object> unsubscribe(@javax.annotation.Nonnull List<String> requestBody) throws ApiException {
    return unsubscribe(requestBody, null);
  }

  /**
   * Unsubscribe from symbols
   * Unsubscribe from symbols
   * @param requestBody  (required)
   * @param headers Optional headers to include in the request
   * @return Map&lt;String, Object&gt;
   * @throws ApiException if fails to make API call
   */
  public Map<String, Object> unsubscribe(@javax.annotation.Nonnull List<String> requestBody, Map<String, String> headers) throws ApiException {
    ApiResponse<Map<String, Object>> localVarResponse = unsubscribeWithHttpInfo(requestBody, headers);
    return localVarResponse.getData();
  }

  /**
   * Unsubscribe from symbols
   * Unsubscribe from symbols
   * @param requestBody  (required)
   * @return ApiResponse&lt;Map&lt;String, Object&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Map<String, Object>> unsubscribeWithHttpInfo(@javax.annotation.Nonnull List<String> requestBody) throws ApiException {
    return unsubscribeWithHttpInfo(requestBody, null);
  }

  /**
   * Unsubscribe from symbols
   * Unsubscribe from symbols
   * @param requestBody  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Map&lt;String, Object&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Map<String, Object>> unsubscribeWithHttpInfo(@javax.annotation.Nonnull List<String> requestBody, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = unsubscribeRequestBuilder(requestBody, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("unsubscribe", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Map<String, Object>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Map<String, Object> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Map<String, Object>>() {});
        

        return new ApiResponse<Map<String, Object>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder unsubscribeRequestBuilder(@javax.annotation.Nonnull List<String> requestBody, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'requestBody' is set
    if (requestBody == null) {
      throw new ApiException(400, "Missing the required parameter 'requestBody' when calling unsubscribe");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/polling/unsubscribe";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(requestBody);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
