/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.am.marketdata.api;

import com.am.marketdata.client.ApiClient;
import com.am.marketdata.client.ApiException;
import com.am.marketdata.client.ApiResponse;
import com.am.marketdata.client.Configuration;
import com.am.marketdata.client.Pair;

import com.am.marketdata.model.SecurityDTOV1;
import com.am.marketdata.model.SecuritySearchRequestV1;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class SecurityMetadataApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public SecurityMetadataApi() {
    this(Configuration.getDefaultApiClient());
  }

  public SecurityMetadataApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Find securities by symbols
   * Returns metadata for specific symbols
   * @param symbols  (required)
   * @return List&lt;SecurityDTOV1&gt;
   * @throws ApiException if fails to make API call
   */
  public List<SecurityDTOV1> findBySymbols(@javax.annotation.Nonnull String symbols) throws ApiException {
    return findBySymbols(symbols, null);
  }

  /**
   * Find securities by symbols
   * Returns metadata for specific symbols
   * @param symbols  (required)
   * @param headers Optional headers to include in the request
   * @return List&lt;SecurityDTOV1&gt;
   * @throws ApiException if fails to make API call
   */
  public List<SecurityDTOV1> findBySymbols(@javax.annotation.Nonnull String symbols, Map<String, String> headers) throws ApiException {
    ApiResponse<List<SecurityDTOV1>> localVarResponse = findBySymbolsWithHttpInfo(symbols, headers);
    return localVarResponse.getData();
  }

  /**
   * Find securities by symbols
   * Returns metadata for specific symbols
   * @param symbols  (required)
   * @return ApiResponse&lt;List&lt;SecurityDTOV1&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<SecurityDTOV1>> findBySymbolsWithHttpInfo(@javax.annotation.Nonnull String symbols) throws ApiException {
    return findBySymbolsWithHttpInfo(symbols, null);
  }

  /**
   * Find securities by symbols
   * Returns metadata for specific symbols
   * @param symbols  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;SecurityDTOV1&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<SecurityDTOV1>> findBySymbolsWithHttpInfo(@javax.annotation.Nonnull String symbols, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = findBySymbolsRequestBuilder(symbols, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("findBySymbols", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<SecurityDTOV1>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<SecurityDTOV1> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<SecurityDTOV1>>() {});
        

        return new ApiResponse<List<SecurityDTOV1>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder findBySymbolsRequestBuilder(@javax.annotation.Nonnull String symbols, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'symbols' is set
    if (symbols == null) {
      throw new ApiException(400, "Missing the required parameter 'symbols' when calling findBySymbols");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/security/find";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "symbols";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("symbols", symbols));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all securities
   * Returns all available securities in the database
   * @return List&lt;SecurityDTOV1&gt;
   * @throws ApiException if fails to make API call
   */
  public List<SecurityDTOV1> getAll() throws ApiException {
    return getAll(null);
  }

  /**
   * Get all securities
   * Returns all available securities in the database
   * @param headers Optional headers to include in the request
   * @return List&lt;SecurityDTOV1&gt;
   * @throws ApiException if fails to make API call
   */
  public List<SecurityDTOV1> getAll(Map<String, String> headers) throws ApiException {
    ApiResponse<List<SecurityDTOV1>> localVarResponse = getAllWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Get all securities
   * Returns all available securities in the database
   * @return ApiResponse&lt;List&lt;SecurityDTOV1&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<SecurityDTOV1>> getAllWithHttpInfo() throws ApiException {
    return getAllWithHttpInfo(null);
  }

  /**
   * Get all securities
   * Returns all available securities in the database
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;SecurityDTOV1&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<SecurityDTOV1>> getAllWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getAllRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getAll", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<SecurityDTOV1>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<SecurityDTOV1> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<SecurityDTOV1>>() {});
        

        return new ApiResponse<List<SecurityDTOV1>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getAllRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/security/all";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get sectors for symbols
   * Returns a mapping of symbol to sector
   * @param symbols  (required)
   * @return Map&lt;String, String&gt;
   * @throws ApiException if fails to make API call
   */
  public Map<String, String> getSectors(@javax.annotation.Nonnull String symbols) throws ApiException {
    return getSectors(symbols, null);
  }

  /**
   * Get sectors for symbols
   * Returns a mapping of symbol to sector
   * @param symbols  (required)
   * @param headers Optional headers to include in the request
   * @return Map&lt;String, String&gt;
   * @throws ApiException if fails to make API call
   */
  public Map<String, String> getSectors(@javax.annotation.Nonnull String symbols, Map<String, String> headers) throws ApiException {
    ApiResponse<Map<String, String>> localVarResponse = getSectorsWithHttpInfo(symbols, headers);
    return localVarResponse.getData();
  }

  /**
   * Get sectors for symbols
   * Returns a mapping of symbol to sector
   * @param symbols  (required)
   * @return ApiResponse&lt;Map&lt;String, String&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Map<String, String>> getSectorsWithHttpInfo(@javax.annotation.Nonnull String symbols) throws ApiException {
    return getSectorsWithHttpInfo(symbols, null);
  }

  /**
   * Get sectors for symbols
   * Returns a mapping of symbol to sector
   * @param symbols  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Map&lt;String, String&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Map<String, String>> getSectorsWithHttpInfo(@javax.annotation.Nonnull String symbols, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getSectorsRequestBuilder(symbols, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getSectors", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Map<String, String>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Map<String, String> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Map<String, String>>() {});
        

        return new ApiResponse<Map<String, String>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getSectorsRequestBuilder(@javax.annotation.Nonnull String symbols, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'symbols' is set
    if (symbols == null) {
      throw new ApiException(400, "Missing the required parameter 'symbols' when calling getSectors");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/security/sectors";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "symbols";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("symbols", symbols));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Search securities
   * Search for securities using various filters
   * @param securitySearchRequestV1  (required)
   * @return List&lt;SecurityDTOV1&gt;
   * @throws ApiException if fails to make API call
   */
  public List<SecurityDTOV1> search(@javax.annotation.Nonnull SecuritySearchRequestV1 securitySearchRequestV1) throws ApiException {
    return search(securitySearchRequestV1, null);
  }

  /**
   * Search securities
   * Search for securities using various filters
   * @param securitySearchRequestV1  (required)
   * @param headers Optional headers to include in the request
   * @return List&lt;SecurityDTOV1&gt;
   * @throws ApiException if fails to make API call
   */
  public List<SecurityDTOV1> search(@javax.annotation.Nonnull SecuritySearchRequestV1 securitySearchRequestV1, Map<String, String> headers) throws ApiException {
    ApiResponse<List<SecurityDTOV1>> localVarResponse = searchWithHttpInfo(securitySearchRequestV1, headers);
    return localVarResponse.getData();
  }

  /**
   * Search securities
   * Search for securities using various filters
   * @param securitySearchRequestV1  (required)
   * @return ApiResponse&lt;List&lt;SecurityDTOV1&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<SecurityDTOV1>> searchWithHttpInfo(@javax.annotation.Nonnull SecuritySearchRequestV1 securitySearchRequestV1) throws ApiException {
    return searchWithHttpInfo(securitySearchRequestV1, null);
  }

  /**
   * Search securities
   * Search for securities using various filters
   * @param securitySearchRequestV1  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;SecurityDTOV1&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<SecurityDTOV1>> searchWithHttpInfo(@javax.annotation.Nonnull SecuritySearchRequestV1 securitySearchRequestV1, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = searchRequestBuilder(securitySearchRequestV1, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("search", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<SecurityDTOV1>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<SecurityDTOV1> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<SecurityDTOV1>>() {});
        

        return new ApiResponse<List<SecurityDTOV1>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder searchRequestBuilder(@javax.annotation.Nonnull SecuritySearchRequestV1 securitySearchRequestV1, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'securitySearchRequestV1' is set
    if (securitySearchRequestV1 == null) {
      throw new ApiException(400, "Missing the required parameter 'securitySearchRequestV1' when calling search");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/security/search";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(securitySearchRequestV1);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
