/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.am.marketdata.api;

import com.am.marketdata.client.ApiClient;
import com.am.marketdata.client.ApiException;
import com.am.marketdata.client.ApiResponse;
import com.am.marketdata.client.Configuration;
import com.am.marketdata.client.Pair;

import com.am.marketdata.model.NSEStockIndicesDataV1;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class StockIndicesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public StockIndicesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public StockIndicesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get available indices
   * Returns list of available broad market and sector indices
   * @return Map&lt;String, List&lt;String&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public Map<String, List<String>> getAvailableIndices() throws ApiException {
    return getAvailableIndices(null);
  }

  /**
   * Get available indices
   * Returns list of available broad market and sector indices
   * @param headers Optional headers to include in the request
   * @return Map&lt;String, List&lt;String&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public Map<String, List<String>> getAvailableIndices(Map<String, String> headers) throws ApiException {
    ApiResponse<Map<String, List<String>>> localVarResponse = getAvailableIndicesWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Get available indices
   * Returns list of available broad market and sector indices
   * @return ApiResponse&lt;Map&lt;String, List&lt;String&gt;&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Map<String, List<String>>> getAvailableIndicesWithHttpInfo() throws ApiException {
    return getAvailableIndicesWithHttpInfo(null);
  }

  /**
   * Get available indices
   * Returns list of available broad market and sector indices
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Map&lt;String, List&lt;String&gt;&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Map<String, List<String>>> getAvailableIndicesWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getAvailableIndicesRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getAvailableIndices", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Map<String, List<String>>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Map<String, List<String>> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Map<String, List<String>>>() {});
        

        return new ApiResponse<Map<String, List<String>>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getAvailableIndicesRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/stock-indices/available";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get stock indices data
   * Returns constituent stocks for a specific index
   * @param indexSymbol  (required)
   * @param forceRefresh  (optional, default to false)
   * @return NSEStockIndicesDataV1
   * @throws ApiException if fails to make API call
   */
  public NSEStockIndicesDataV1 getStockIndices(@javax.annotation.Nonnull String indexSymbol, @javax.annotation.Nullable Boolean forceRefresh) throws ApiException {
    return getStockIndices(indexSymbol, forceRefresh, null);
  }

  /**
   * Get stock indices data
   * Returns constituent stocks for a specific index
   * @param indexSymbol  (required)
   * @param forceRefresh  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return NSEStockIndicesDataV1
   * @throws ApiException if fails to make API call
   */
  public NSEStockIndicesDataV1 getStockIndices(@javax.annotation.Nonnull String indexSymbol, @javax.annotation.Nullable Boolean forceRefresh, Map<String, String> headers) throws ApiException {
    ApiResponse<NSEStockIndicesDataV1> localVarResponse = getStockIndicesWithHttpInfo(indexSymbol, forceRefresh, headers);
    return localVarResponse.getData();
  }

  /**
   * Get stock indices data
   * Returns constituent stocks for a specific index
   * @param indexSymbol  (required)
   * @param forceRefresh  (optional, default to false)
   * @return ApiResponse&lt;NSEStockIndicesDataV1&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NSEStockIndicesDataV1> getStockIndicesWithHttpInfo(@javax.annotation.Nonnull String indexSymbol, @javax.annotation.Nullable Boolean forceRefresh) throws ApiException {
    return getStockIndicesWithHttpInfo(indexSymbol, forceRefresh, null);
  }

  /**
   * Get stock indices data
   * Returns constituent stocks for a specific index
   * @param indexSymbol  (required)
   * @param forceRefresh  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;NSEStockIndicesDataV1&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NSEStockIndicesDataV1> getStockIndicesWithHttpInfo(@javax.annotation.Nonnull String indexSymbol, @javax.annotation.Nullable Boolean forceRefresh, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getStockIndicesRequestBuilder(indexSymbol, forceRefresh, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getStockIndices", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<NSEStockIndicesDataV1>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        NSEStockIndicesDataV1 responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NSEStockIndicesDataV1>() {});
        

        return new ApiResponse<NSEStockIndicesDataV1>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getStockIndicesRequestBuilder(@javax.annotation.Nonnull String indexSymbol, @javax.annotation.Nullable Boolean forceRefresh, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'indexSymbol' is set
    if (indexSymbol == null) {
      throw new ApiException(400, "Missing the required parameter 'indexSymbol' when calling getStockIndices");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/stock-indices/{indexSymbol}"
        .replace("{indexSymbol}", ApiClient.urlEncode(indexSymbol.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "forceRefresh";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("forceRefresh", forceRefresh));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get multiple stock indices
   * Returns constituent stocks for multiple indices
   * @param requestBody  (required)
   * @param forceRefresh  (optional, default to false)
   * @return List&lt;NSEStockIndicesDataV1&gt;
   * @throws ApiException if fails to make API call
   */
  public List<NSEStockIndicesDataV1> getStockIndicesBatch(@javax.annotation.Nonnull List<String> requestBody, @javax.annotation.Nullable Boolean forceRefresh) throws ApiException {
    return getStockIndicesBatch(requestBody, forceRefresh, null);
  }

  /**
   * Get multiple stock indices
   * Returns constituent stocks for multiple indices
   * @param requestBody  (required)
   * @param forceRefresh  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return List&lt;NSEStockIndicesDataV1&gt;
   * @throws ApiException if fails to make API call
   */
  public List<NSEStockIndicesDataV1> getStockIndicesBatch(@javax.annotation.Nonnull List<String> requestBody, @javax.annotation.Nullable Boolean forceRefresh, Map<String, String> headers) throws ApiException {
    ApiResponse<List<NSEStockIndicesDataV1>> localVarResponse = getStockIndicesBatchWithHttpInfo(requestBody, forceRefresh, headers);
    return localVarResponse.getData();
  }

  /**
   * Get multiple stock indices
   * Returns constituent stocks for multiple indices
   * @param requestBody  (required)
   * @param forceRefresh  (optional, default to false)
   * @return ApiResponse&lt;List&lt;NSEStockIndicesDataV1&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<NSEStockIndicesDataV1>> getStockIndicesBatchWithHttpInfo(@javax.annotation.Nonnull List<String> requestBody, @javax.annotation.Nullable Boolean forceRefresh) throws ApiException {
    return getStockIndicesBatchWithHttpInfo(requestBody, forceRefresh, null);
  }

  /**
   * Get multiple stock indices
   * Returns constituent stocks for multiple indices
   * @param requestBody  (required)
   * @param forceRefresh  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;NSEStockIndicesDataV1&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<NSEStockIndicesDataV1>> getStockIndicesBatchWithHttpInfo(@javax.annotation.Nonnull List<String> requestBody, @javax.annotation.Nullable Boolean forceRefresh, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getStockIndicesBatchRequestBuilder(requestBody, forceRefresh, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getStockIndicesBatch", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<NSEStockIndicesDataV1>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<NSEStockIndicesDataV1> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<NSEStockIndicesDataV1>>() {});
        

        return new ApiResponse<List<NSEStockIndicesDataV1>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getStockIndicesBatchRequestBuilder(@javax.annotation.Nonnull List<String> requestBody, @javax.annotation.Nullable Boolean forceRefresh, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'requestBody' is set
    if (requestBody == null) {
      throw new ApiException(400, "Missing the required parameter 'requestBody' when calling getStockIndicesBatch");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/stock-indices/batch";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "forceRefresh";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("forceRefresh", forceRefresh));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(requestBody);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
