version: '3.8'


services:
  market-data-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_PACKAGES_USERNAME=${GITHUB_PACKAGES_USERNAME}
        - GITHUB_PACKAGES_TOKEN=${GITHUB_PACKAGES_TOKEN}
    environment:
      # Spring Profile
      - SPRING_PROFILES_ACTIVE=docker
      
      # Database Configuration
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}/${POSTGRES_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      
      # InfluxDB Configuration
      - SPRING_INFLUXDB_URL=${INFLUXDB_URL}:8086
      - SPRING_INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - SPRING_INFLUXDB_ORG=${INFLUXDB_ORG}
      - SPRING_INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      
      # Kafka Configuration
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID}
      - SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET=${KAFKA_CONSUMER_AUTO_OFFSET_RESET}
      
      # Application Topics
      - APP_KAFKA_STOCK_PRICE_TOPIC=${STOKUPATE_TOPIC_NAME}
      - APP_KAFKA_NSE_INDICES_TOPIC=${NSE_INDICES_TOPIC_NAME}
      - APP_KAFKA_NSE_ETF_TOPIC=${NSE_ETF_TOPIC_NAME}
      
      # Retry Configuration
      - APP_RETRY_MAX_ATTEMPTS=${MARKET_DATA_MAX_RETRIES}
      - APP_RETRY_BASE_DELAY_MS=${MARKET_DATA_RETRY_DELAY_MS}
      
      # Thread Pool Configuration
      - APP_THREAD_POOL_SIZE=${MARKET_DATA_THREAD_POOL_SIZE}
      - APP_THREAD_POOL_QUEUE_CAPACITY=${MARKET_DATA_THREAD_QUEUE_CAPACITY}
      
      # Validation Configuration
      - APP_VALIDATION_MAX_AGE_MINUTES=${MARKET_DATA_MAX_AGE_MINUTES}
      
      # Upstox Configuration
      - UPSTOX_AUTH_CODE=${UPSTOX_CODE}
      - UPSTOX_AUTH_API_KEY=${UPSTOX_API_KEY}
      - UPSTOX_AUTH_SECRET_KEY=${UPSTOX_SECRET_KEY}
      - UPSTOX_AUTH_ACCESS_TOKEN=${UPSTOX_ACCESS_TOKEN}
      - UPSTOX_AUTH_BASE_URL=https://api.upstox.com/v2
      - UPSTOX_AUTH_REDIRECT_URI=http://localhost:8080
      - UPSTOX_AUTH_TOKEN_REFRESH_INTERVAL=3600000
      - UPSTOX_INTERVAL=I1
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        echo "=== Market Data Service Environment Variables ==="
        echo "Database URL: $${SPRING_DATASOURCE_URL}"
        echo "Database User: $${SPRING_DATASOURCE_USERNAME}"
        echo "InfluxDB URL: $${SPRING_INFLUXDB_URL}"
        echo "InfluxDB Org: $${SPRING_INFLUXDB_ORG}"
        echo "Kafka Servers: $${SPRING_KAFKA_BOOTSTRAP_SERVERS}"
        echo "Kafka Group: $${SPRING_KAFKA_CONSUMER_GROUP_ID}"
        echo "Max Retries: $${APP_RETRY_MAX_ATTEMPTS}"
        echo "Thread Pool Size: $${APP_THREAD_POOL_SIZE}"
        echo "=== Starting Market Data Service ==="
        java -jar app.jar
    ports:
      - "8080:8080"
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: ${MARKET_DATA_MAX_RETRIES}
    restart: unless-stopped

volumes:
  postgres_data:
  influxdb_data:
  grafana_data:
