#!/bin/bash

echo "=== Current Environment Variables ==="
echo "Database Configuration:"
echo "SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL"
echo "SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME"

echo -e "\nInfluxDB Configuration:"
echo "SPRING_INFLUXDB_URL=$SPRING_INFLUXDB_URL"
echo "SPRING_INFLUXDB_ORG=$SPRING_INFLUXDB_ORG"
echo "SPRING_INFLUXDB_BUCKET=$SPRING_INFLUXDB_BUCKET"

echo -e "\nKafka Configuration:"
echo "SPRING_KAFKA_BOOTSTRAP_SERVERS=$SPRING_KAFKA_BOOTSTRAP_SERVERS"
echo "SPRING_KAFKA_CONSUMER_GROUP_ID=$SPRING_KAFKA_CONSUMER_GROUP_ID"
echo "SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET=$SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET"

echo -e "\nApplication Topics:"
echo "APP_KAFKA_STOCK_PRICE_TOPIC=$APP_KAFKA_STOCK_PRICE_TOPIC"
echo "APP_KAFKA_NSE_INDICES_TOPIC=$APP_KAFKA_NSE_INDICES_TOPIC"
echo "APP_KAFKA_NSE_ETF_TOPIC=$APP_KAFKA_NSE_ETF_TOPIC"

echo -e "\nRetry Configuration:"
echo "APP_RETRY_MAX_ATTEMPTS=$APP_RETRY_MAX_ATTEMPTS"
echo "APP_RETRY_BASE_DELAY_MS=$APP_RETRY_BASE_DELAY_MS"

echo -e "\nThread Pool Configuration:"
echo "APP_THREAD_POOL_SIZE=$APP_THREAD_POOL_SIZE"
echo "APP_THREAD_POOL_QUEUE_CAPACITY=$APP_THREAD_POOL_QUEUE_CAPACITY"

echo -e "\nValidation Configuration:"
echo "APP_VALIDATION_MAX_AGE_MINUTES=$APP_VALIDATION_MAX_AGE_MINUTES"

echo -e "\n=== End Environment Variables ===\n"

exec "$@"
