UPSTOX_ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyWENSTjgiLCJqdGkiOiI2N2NmYjM2NmQ4MGZiMDM1MDBjZmUyZTEiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaWF0IjoxNzQxNjY1MTI2LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NDE3MzA0MDB9.g3mIz1jfVCVE1wjcHa6G6kWttFO3FK-ZsOxLPDT7KL0

server:
  port: 8080
spring:
  influx:
    url: http://localhost:8086
    token: my-super-secret-auth-token
    org: am_investment
    bucket: market_data
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: am-market-data-service
      auto-offset-reset: earliest

app:
  kafka:
    topic: am-stock-price-update
    nse-indices-topic: nse-indices-update
    nse-etf-topic: nse-etf-update

upstox:
  interval: I1
  auth:
    base-url: https://api.upstox.com/v2
    code: ${UPSTOX_CODE:SeG3X0}
    api-key: ${UPSTOX_API_KEY:48d1e335-09ad-4dc0-b955-4505c350d10b}
    secret-key: ${UPSTOX_SECRET_KEY:jqre481zf0}
    access-token: ${UPSTOX_ACCESS_TOKEN:your-default-token}
    redirect-uri: http://localhost:8080
    authorization-url: https://api-v2.upstox.com/login/authorization/dialog
    token-url: https://api-v2.upstox.com/login/authorization/token
    token-refresh-interval: 3600000
    scope: orders feed portfolio



scraper:
  urls:
    - https://www.nseindia.com/


# logging:
#   level:
#     root: DEBUG
#     com.am.common.investment: INFO