# PostgreSQL Configuration
POSTGRES_PASSWORD: password
POSTGRES_USERNAME: postgres
POSTGRES_URL: jdbc:postgresql://localhost:5456
POSTGRES_DATABASE: portfolio

# InfluxDB Configuration
INFLUXDB_TOKEN: my-super-secret-auth-token
INFLUXDB_ORG: am_investment
INFLUXDB_BUCKET: market_data
INFLUXDB_URL: http://localhost:8087

# Grafana Configuration
GRAFANA_ADMIN_USER: 1109403
GRAFANA_ADMIN_PASSWORD: XXXXXXXXXX

# Kafka Configuration
KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_ZOOKEEPER_CONNECT: localhost:2181
KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
KAFKA_CONSUMER_GROUP_ID: am-market-data-service
KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest

# Application Configuration
STOKUPATE_TOPIC_NAME: am-stock-price-update
NSE_INDICES_TOPIC_NAME: nse-indices-update
NSE_STOCK_INDICES_TOPIC_NAME: nse-stock-indices-update

MARKET_DATA_MAX_RETRIES: 3
MARKET_DATA_RETRY_DELAY_MS: 1000
MARKET_DATA_THREAD_POOL_SIZE: 5
MARKET_DATA_THREAD_QUEUE_CAPACITY: 10
MARKET_DATA_MAX_AGE_MINUTES: 15

# Upstox Configuration
UPSTOX_ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyWENSTjgiLCJqdGkiOiI2N2RiNDUwZjNkZGQ3YTZhM2Q0MDdmMmEiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaWF0IjoxNzQyNDIzMzExLCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NDI1MDgwMDB9.trE87ksuZgTY_Isx9bYAxECeStUVgGtWxVNzjtcp0Mk
UPSTOX_API_KEY: 48d1e335-09ad-4dc0-b955-4505c350d10b
UPSTOX_SECRET_KEY: jqre481zf0
UPSTOX_CODE: rNLu2Q 

server:
  port: 8084

spring:
  application:
    name: market-data-service
  
  # Database Configuration
  datasource:
    url: ${POSTGRES_URL}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
  # InfluxDB Configuration
  influx:
    url: ${INFLUXDB_URL}
    token: ${INFLUXDB_TOKEN}
    org: ${INFLUXDB_ORG}
    bucket: ${INFLUXDB_BUCKET}
    
  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET}
  
  config:
    import:
      - classpath:isin.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

app:
  kafka:
    stock-price-topic: ${STOKUPATE_TOPIC_NAME}
    nse-indices-topic: ${NSE_INDICES_TOPIC_NAME}
    stock-indices-topic: ${NSE_STOCK_INDICES_TOPIC_NAME}
  
  scheduler:
    # Trading hours configuration (from StockDataSchedulerService)
    trading:
      start-time: "00:00"
      end-time: "23:59"
      timezone: "Asia/Kolkata"
      days: "MON-FRI"
    
    # CookieSchedulerService schedules
    cookie:
      refresh: "0 */30 * * * *"  # Cookie refresh every 30 minutes
      retry: "0 */5 * * * *"     # Retry failed cookie refresh every 5 minutes
    
    # MarketDataProcessingService schedules
    market-data:
      # Thread pool configuration from memory
      thread-pool:
        size: ${MARKET_DATA_THREAD_POOL_SIZE}         # Default: 5
        queue-capacity: ${MARKET_DATA_THREAD_QUEUE_CAPACITY} # Default: 10
        prefix: "market-data-"
      
      # Stock data processing (from StockDataSchedulerService)
      stock:
        fetch: "5 */2 * * * *"           # Runs at 5 seconds past every 2 minutes
        validate: "0 */15 * * * *"       # Validate every 15 minutes (max age check)
      
      # ETF data processing (with retry mechanism)
      etf:
        fetch: "0 */5 * * * *"          # Every 5 minutes, trading hours check in service
        validate: "0 */15 * * * *"      # 15min freshness validation
        retry:
          max-attempts: ${MARKET_DATA_MAX_RETRIES}    # Default: 3
          delay-ms: ${MARKET_DATA_RETRY_DELAY_MS}     # Default: 1000ms
      
      # Indices data processing
      indices:
        fetch: "0 */2 * * * *"          # Every 2 minutes, trading hours check in service
        validate: "0 */15 * * * *"      # Data integrity check
    
    # Retry mechanism schedules (3 retries, 1000ms delay)
    retry:
      failed-operations: "0 */1 * * * *"  # Check and retry failed operations
      cleanup: "0 0 * * * *"             # Clean up retry history hourly
    
    # Data management
    data:
      cleanup: "0 0 18 * * *"            # Daily cleanup at 6 PM
      refresh: "0 0 7 * * MON-FRI"       # Refresh at 7 AM weekdays
    
    # Metrics collection (for Micrometer)
    metrics:
      performance: "0 */1 * * * *"        # Collect performance metrics
      health: "0 */1 * * * *"            # Health checks
      counters: "0 */5 * * * *"          # Update success/failure counters
    
    # Health check schedule (every minute)
    health-check: "0 */1 * * * *"
  
  retry:
    max-attempts: ${MARKET_DATA_MAX_RETRIES}
    base-delay-ms: ${MARKET_DATA_RETRY_DELAY_MS}
  
  thread-pool:
    size: ${MARKET_DATA_THREAD_POOL_SIZE}
    queue-capacity: ${MARKET_DATA_THREAD_QUEUE_CAPACITY}
    prefix: "market-data-"
  
  validation:
    max-age-minutes: ${MARKET_DATA_MAX_AGE_MINUTES}

upstox:
  interval: I1
  auth:
    base-url: https://api.upstox.com/v2
    code: ${UPSTOX_CODE}
    api-key: ${UPSTOX_API_KEY}
    secret-key: ${UPSTOX_SECRET_KEY}
    access-token: ${UPSTOX_ACCESS_TOKEN}
    redirect-uri: http://localhost:8080
    authorization-url: https://api-v2.upstox.com/login/authorization/dialog
    token-url: https://api-v2.upstox.com/login/authorization/token
    token-refresh-interval: 3600000
    scope: orders feed portfolio

stock-data-scheduler: false
nse-scraper-scheduler: true
scraper:
  urls:
    - https://www.nseindia.com/

# Logging Configuration
logging:
  level:
    root: INFO
    '[com.am.marketdata]': INFO
    '[com.am.marketdata.scheduler]': INFO
    '[com.am.marketdata.service]': INFO
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%p","thread":"%t","class":"%c","message":"%m"}%n'