# GitHub Package Registry Authentication
GITHUB_PACKAGES_USERNAME: ssd2658
GITHUB_PACKAGES_TOKEN: hp_gr9NrUvwdVk9D5R4Fe9UFb7g2MXvmz2A5Yi0

# PostgreSQL Configuration
POSTGRES_PASSWORD: password
POSTGRES_USERNAME: postgres
POSTGRES_URL: jdbc:postgresql://localhost:5432
POSTGRES_DATABASE: portfolio

# InfluxDB Configuration
INFLUXDB_TOKEN: my-super-secret-auth-token
INFLUXDB_ORG: am_investment
INFLUXDB_BUCKET: market_data
INFLUXDB_URL: http://localhost:8086

# Grafana Configuration
GRAFANA_ADMIN_USER: admin
GRAFANA_ADMIN_PASSWORD: your_grafana_password

# Kafka Configuration
KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_ZOOKEEPER_CONNECT: localhost:2181
KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

# Application Configuration
STOKUPATE_TOPIC_NAME: am-stock-price-update
NSE_INDICES_TOPIC_NAME: nse-indices-update
NSE_ETF_TOPIC_NAME: nse-etf-update

MARKET_DATA_MAX_RETRIES: 3
MARKET_DATA_RETRY_DELAY_MS: 1000
MARKET_DATA_THREAD_POOL_SIZE: 5
MARKET_DATA_THREAD_QUEUE_CAPACITY: 10
MARKET_DATA_MAX_AGE_MINUTES: 15

# Upstox Configuration
UPSTOX_ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyWENSTjgiLCJqdGkiOiI2N2NmYjM2NmQ4MGZiMDM1MDBjZmUyZTEiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaWF0IjoxNzQxNjY1MTI2LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NDE3MzA0MDB9.g3mIz1jfVCVE1wjcHa6G6kWttFO3FK-ZsOxLPDT7KL0
UPSTOX_API_KEY: 48d1e335-09ad-4dc0-b955-4505c350d10b
UPSTOX_SECRET_KEY: jqre481zf0
UPSTOX_CODE: SeG3X0 

server:
  port: 8084

spring:
  influx:
    url: ${INFLUXDB_URL}
    token: ${INFLUXDB_TOKEN}
    org: ${INFLUXDB_ORG}
    bucket: ${INFLUXDB_BUCKET}
  datasource:
    url: ${POSTGRES_URL}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: am-market-data-service
      auto-offset-reset: earliest

app:
  kafka:
    stock-price-topic: ${STOKUPATE_TOPIC_NAME}
    nse-indices-topic: ${NSE_INDICES_TOPIC_NAME}
    nse-etf-topic: ${NSE_ETF_TOPIC_NAME}
  retry:
    max-attempts: ${market.data.max.retries:3}
    base-delay-ms: ${market.data.retry.delay.ms:1000}
  thread-pool:
    size: ${market.data.thread.pool.size:5}
    queue-capacity: ${market.data.thread.queue.capacity:10}
  validation:
    max-age-minutes: ${market.data.max.age.minutes:15}

upstox:
  interval: I1
  auth:
    base-url: https://api.upstox.com/v2
    code: ${UPSTOX_CODE:SeG3X0}
    api-key: ${UPSTOX_API_KEY:48d1e335-09ad-4dc0-b955-4505c350d10b}
    secret-key: ${UPSTOX_SECRET_KEY:jqre481zf0}
    access-token: ${UPSTOX_ACCESS_TOKEN:your-default-token}
    redirect-uri: http://localhost:8080
    authorization-url: https://api-v2.upstox.com/login/authorization/dialog
    token-url: https://api-v2.upstox.com/login/authorization/token
    token-refresh-interval: 3600000
    scope: orders feed portfolio

scraper:
  urls:
    - https://www.nseindia.com/

# logging:
#   level:
#     root: DEBUG
#     com.am.common.investment: INFO