# PostgreSQL Configuration
POSTGRES_PASSWORD: password
POSTGRES_USERNAME: postgres
POSTGRES_URL: jdbc:postgresql://localhost:5456
POSTGRES_DATABASE: portfolio

#mongo
MONGO_URL: mongodb://admin:password@localhost:27017/portfolio?authSource=admin
MONGO_DATABASE: market_data
MONGO_USERNAME: admin
MONGO_PASSWORD: password

# InfluxDB Configuration
INFLUXDB_TOKEN: my-super-secret-auth-token
INFLUXDB_ORG: am_investment
INFLUXDB_BUCKET: market_data
INFLUXDB_URL: http://localhost:8087

# Grafana Configuration
GRAFANA_ADMIN_USER: 1109403
GRAFANA_ADMIN_PASSWORD: XXXXXXXXXX

MARKET_DATA_MAX_RETRIES: 3
MARKET_DATA_RETRY_DELAY_MS: 1000
MARKET_DATA_THREAD_POOL_SIZE: 5
MARKET_DATA_THREAD_QUEUE_CAPACITY: 10
MARKET_DATA_MAX_AGE_MINUTES: 15

# Upstox Configuration
UPSTOX_ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyWENSTjgiLCJqdGkiOiI2N2RiNDUwZjNkZGQ3YTZhM2Q0MDdmMmEiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaWF0IjoxNzQyNDIzMzExLCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NDI1MDgwMDB9.trE87ksuZgTY_Isx9bYAxECeStUVgGtWxVNzjtcp0Mk
UPSTOX_API_KEY: 48d1e335-09ad-4dc0-b955-4505c350d10b
UPSTOX_SECRET_KEY: jqre481zf0
UPSTOX_CODE: rNLu2Q 

# Spring Configuration
spring:
  profiles:
    active: dev,local  # Default to development profile
  application:
    name: market-data-service

  # MongoDB Configuration
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      authentication-database: admin
  
  # InfluxDB Configuration
  influx:
    url: ${INFLUXDB_URL}
    token: ${INFLUXDB_TOKEN}
    org: ${INFLUXDB_ORG}
    bucket: ${INFLUXDB_BUCKET}
    
  # Database Configuration
  datasource:
    url: ${POSTGRES_URL}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  config:
    import:
      - classpath:isin.yml
      - classpath:nseindices.yml
      - classpath:application-external-api.yml
      - classpath:application-endpoints.yml
      - classpath:application-kafka.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always

upstox:
  interval: I1
  auth:
    base-url: https://api.upstox.com/v2
    code: ${UPSTOX_CODE}
    api-key: ${UPSTOX_API_KEY}
    secret-key: ${UPSTOX_SECRET_KEY}
    access-token: ${UPSTOX_ACCESS_TOKEN}
    redirect-uri: http://localhost:8080
    authorization-url: https://api-v2.upstox.com/login/authorization/dialog
    token-url: https://api-v2.upstox.com/login/authorization/token
    token-refresh-interval: 3600000
    scope: orders feed portfolio

stock-data-scheduler: false
nse-scraper-scheduler: true
scraper:
  urls:
    - https://www.nseindia.com/

# Server Configuration
server:
  port: 8084

# Logging Configuration
logging:
  level:
    root: INFO
    '[com.am.marketdata]': INFO
    '[com.am.marketdata.scheduler]': DEBUG
    '[com.am.marketdata.service]': INFO
    '[com.am.marketdata.external.api]': DEBUG
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%p","thread":"%t","class":"%c","message":"%m"}%n'