# PostgreSQL Configuration
# POSTGRES_PASSWORD: password
# POSTGRES_USERNAME: postgres
# POSTGRES_URL: jdbc:postgresql://localhost:5456
# POSTGRES_DATABASE: portfolio

#mongo
MONGODB_URL: mongodb://ssd2658:ssd2658@localhost:27017/market_data?authSource=admin
MONGODB_DATABASE: market_data
MONGODB_USERNAME: ssd2658
MONGODB_PASSWORD: ssd2658 

# InfluxDB Configuration
INFLUXDB_TOKEN: ssd2658admin123456789
INFLUXDB_ORG: am-portfolio
INFLUXDB_BUCKET: market_data
INFLUXDB_URL: http://localhost:8086


# Redis Configuration
REDIS_HOSTNAME: localhost
REDIS_PASSWORD: RedisPassword123!
REDIS_PORT: 6379

# Grafana Configuration
GRAFANA_ADMIN_USER: 1109403
GRAFANA_ADMIN_PASSWORD: XXXXXXXXXX


# Application Configuration
STOKUPATE_TOPIC_NAME: am-stock-price-update
NSE_INDICES_TOPIC_NAME: nse-indices-update
NSE_STOCK_INDICES_TOPIC_NAME: nse-stock-indices-update
BOARD_OF_DIRECTORS_TOPIC_NAME: stock-board-of-directors
QUATERLY_FINANCIALS_TOPIC_NAME: stock-quaterly-financials
STOCK_RESULTS_FINANCIALS_TOPIC_NAME: stock-results-financials
STOCK_PROFIT_AND_LOSS_FINANCIALS_TOPIC_NAME: stock-profit-and-loss-financials
STOCK_BALANCE_SHEET_FINANCIALS_TOPIC_NAME: stock-balance-sheet-financials
STOCK_CASH_FLOW_FINANCIALS_TOPIC_NAME: stock-cash-flow-financials
STOCK_FACT_SHEET_DIVIDEND_FINANCIALS_TOPIC_NAME: stock-fact-sheet-dividend-financials

MARKET_DATA_MAX_RETRIES: 3
MARKET_DATA_RETRY_DELAY_MS: 1000
MARKET_DATA_THREAD_POOL_SIZE: 5
MARKET_DATA_THREAD_QUEUE_CAPACITY: 10
MARKET_DATA_MAX_AGE_MINUTES: 15

# Upstox Configuration
UPSTOX_ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyWENSTjgiLCJqdGkiOiI2N2RiNDUwZjNkZGQ3YTZhM2Q0MDdmMmEiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaWF0IjoxNzQyNDIzMzExLCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NDI1MDgwMDB9.trE87ksuZgTY_Isx9bYAxECeStUVgGtWxVNzjtcp0Mk
UPSTOX_API_KEY: 48d1e335-09ad-4dc0-b955-4505c350d10b
UPSTOX_SECRET_KEY: jqre481zf0
UPSTOX_CODE: rNLu2Q 

# Spring Configuration
spring:
  application:
    name: market-data-service
  data:
    redis:
      host: ${REDIS_HOSTNAME}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT:6379}
    mongodb:
      uri: ${MONGODB_URL}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin
  
  # InfluxDB Configuration
  influx:
    url: ${INFLUXDB_URL}
    token: ${INFLUXDB_TOKEN}
    org: ${INFLUXDB_ORG}
    bucket: ${INFLUXDB_BUCKET}

# Management and Metrics Configuration
  management:
    endpoints:
      web:
        exposure:
          include: "*"
        base-path: /actuator
    endpoint:
      health:
        show-details: always
        probes:
          enabled: true
        group:
          readiness:
            include: redis, diskSpace
          liveness:
            include: ping
    health:
      livenessState:
        enabled: true
      readinessState:
        enabled: true

  config:
    import:
      - classpath:isin.yml
      - classpath:nseindices.yml
      #- classpath:application-external-api.yml
      #- classpath:application-endpoints.yml
      - classpath:application-kafka.yml
      - classpath:application-zerodha.yml

  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.PostgreSQLDialect
  #       format_sql: true
  #   show-sql: true

# Logging Configuration
logging:
  level:
    root: INFO
    '[com.am.marketdata]': INFO
    '[com.am.marketdata.scheduler]': DEBUG
    '[com.am.marketdata.service]': INFO
    '[com.am.marketdata.external.api]': DEBUG
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%p","thread":"%t","class":"%c","message":"%m"}%n'

upstox:
  interval: I1
  auth:
    base-url: https://api.upstox.com/v2
    code: ${UPSTOX_CODE}
    api-key: ${UPSTOX_API_KEY}
    secret-key: ${UPSTOX_SECRET_KEY}
    access-token: ${UPSTOX_ACCESS_TOKEN}
    redirect-uri: http://localhost:8080
    authorization-url: https://api-v2.upstox.com/login/authorization/dialog
    token-url: https://api-v2.upstox.com/login/authorization/token
    token-refresh-interval: 3600000
    scope: orders feed portfolio

stock-data-scheduler: false
nse-scraper-scheduler: true
scraper:
  urls:
    - https://www.nseindia.com/

# Server Configuration
server:
  port: 8084