apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
    service: market-data
data:
  redis.conf: |
    appendonly yes
    maxmemory 400mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    requirepass REDIS_PASSWORD_PLACEHOLDER
    protected-mode yes
    bind 0.0.0.0