apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app: redis
    service: market-data
type: Opaque
data:
  password: UmVkaXNQYXNzd29yZDEyMyE=  # Base64 encoded "RedisPassword123!"