/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * BrokerageCalculationResponse
 */
@JsonPropertyOrder({
  BrokerageCalculationResponse.JSON_PROPERTY_BUY_TRANSACTION_VALUE,
  BrokerageCalculationResponse.JSON_PROPERTY_SELL_TRANSACTION_VALUE,
  BrokerageCalculationResponse.JSON_PROPERTY_BUY_BROKERAGE,
  BrokerageCalculationResponse.JSON_PROPERTY_SELL_BROKERAGE,
  BrokerageCalculationResponse.JSON_PROPERTY_BUY_S_T_T,
  BrokerageCalculationResponse.JSON_PROPERTY_SELL_S_T_T,
  BrokerageCalculationResponse.JSON_PROPERTY_BUY_EXCHANGE_CHARGES,
  BrokerageCalculationResponse.JSON_PROPERTY_SELL_EXCHANGE_CHARGES,
  BrokerageCalculationResponse.JSON_PROPERTY_BUY_G_S_T,
  BrokerageCalculationResponse.JSON_PROPERTY_SELL_G_S_T,
  BrokerageCalculationResponse.JSON_PROPERTY_BUY_S_E_B_I_CHARGES,
  BrokerageCalculationResponse.JSON_PROPERTY_SELL_S_E_B_I_CHARGES,
  BrokerageCalculationResponse.JSON_PROPERTY_BUY_STAMP_DUTY,
  BrokerageCalculationResponse.JSON_PROPERTY_SELL_STAMP_DUTY,
  BrokerageCalculationResponse.JSON_PROPERTY_DP_CHARGES,
  BrokerageCalculationResponse.JSON_PROPERTY_TOTAL_BUY_CHARGES,
  BrokerageCalculationResponse.JSON_PROPERTY_TOTAL_SELL_CHARGES,
  BrokerageCalculationResponse.JSON_PROPERTY_TOTAL_CHARGES,
  BrokerageCalculationResponse.JSON_PROPERTY_NET_PROFIT_LOSS,
  BrokerageCalculationResponse.JSON_PROPERTY_CHARGES_PERCENTAGE,
  BrokerageCalculationResponse.JSON_PROPERTY_BREAK_EVEN_PRICE,
  BrokerageCalculationResponse.JSON_PROPERTY_STATUS,
  BrokerageCalculationResponse.JSON_PROPERTY_ERROR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class BrokerageCalculationResponse {
  public static final String JSON_PROPERTY_BUY_TRANSACTION_VALUE = "buyTransactionValue";
  @javax.annotation.Nullable
  private BigDecimal buyTransactionValue;

  public static final String JSON_PROPERTY_SELL_TRANSACTION_VALUE = "sellTransactionValue";
  @javax.annotation.Nullable
  private BigDecimal sellTransactionValue;

  public static final String JSON_PROPERTY_BUY_BROKERAGE = "buyBrokerage";
  @javax.annotation.Nullable
  private BigDecimal buyBrokerage;

  public static final String JSON_PROPERTY_SELL_BROKERAGE = "sellBrokerage";
  @javax.annotation.Nullable
  private BigDecimal sellBrokerage;

  public static final String JSON_PROPERTY_BUY_S_T_T = "buySTT";
  @javax.annotation.Nullable
  private BigDecimal buySTT;

  public static final String JSON_PROPERTY_SELL_S_T_T = "sellSTT";
  @javax.annotation.Nullable
  private BigDecimal sellSTT;

  public static final String JSON_PROPERTY_BUY_EXCHANGE_CHARGES = "buyExchangeCharges";
  @javax.annotation.Nullable
  private BigDecimal buyExchangeCharges;

  public static final String JSON_PROPERTY_SELL_EXCHANGE_CHARGES = "sellExchangeCharges";
  @javax.annotation.Nullable
  private BigDecimal sellExchangeCharges;

  public static final String JSON_PROPERTY_BUY_G_S_T = "buyGST";
  @javax.annotation.Nullable
  private BigDecimal buyGST;

  public static final String JSON_PROPERTY_SELL_G_S_T = "sellGST";
  @javax.annotation.Nullable
  private BigDecimal sellGST;

  public static final String JSON_PROPERTY_BUY_S_E_B_I_CHARGES = "buySEBICharges";
  @javax.annotation.Nullable
  private BigDecimal buySEBICharges;

  public static final String JSON_PROPERTY_SELL_S_E_B_I_CHARGES = "sellSEBICharges";
  @javax.annotation.Nullable
  private BigDecimal sellSEBICharges;

  public static final String JSON_PROPERTY_BUY_STAMP_DUTY = "buyStampDuty";
  @javax.annotation.Nullable
  private BigDecimal buyStampDuty;

  public static final String JSON_PROPERTY_SELL_STAMP_DUTY = "sellStampDuty";
  @javax.annotation.Nullable
  private BigDecimal sellStampDuty;

  public static final String JSON_PROPERTY_DP_CHARGES = "dpCharges";
  @javax.annotation.Nullable
  private BigDecimal dpCharges;

  public static final String JSON_PROPERTY_TOTAL_BUY_CHARGES = "totalBuyCharges";
  @javax.annotation.Nullable
  private BigDecimal totalBuyCharges;

  public static final String JSON_PROPERTY_TOTAL_SELL_CHARGES = "totalSellCharges";
  @javax.annotation.Nullable
  private BigDecimal totalSellCharges;

  public static final String JSON_PROPERTY_TOTAL_CHARGES = "totalCharges";
  @javax.annotation.Nullable
  private BigDecimal totalCharges;

  public static final String JSON_PROPERTY_NET_PROFIT_LOSS = "netProfitLoss";
  @javax.annotation.Nullable
  private BigDecimal netProfitLoss;

  public static final String JSON_PROPERTY_CHARGES_PERCENTAGE = "chargesPercentage";
  @javax.annotation.Nullable
  private BigDecimal chargesPercentage;

  public static final String JSON_PROPERTY_BREAK_EVEN_PRICE = "breakEvenPrice";
  @javax.annotation.Nullable
  private BigDecimal breakEvenPrice;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_ERROR = "error";
  @javax.annotation.Nullable
  private String error;

  public BrokerageCalculationResponse() { 
  }

  public BrokerageCalculationResponse buyTransactionValue(@javax.annotation.Nullable BigDecimal buyTransactionValue) {
    this.buyTransactionValue = buyTransactionValue;
    return this;
  }

  /**
   * Get buyTransactionValue
   * @return buyTransactionValue
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUY_TRANSACTION_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBuyTransactionValue() {
    return buyTransactionValue;
  }


  @JsonProperty(value = JSON_PROPERTY_BUY_TRANSACTION_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuyTransactionValue(@javax.annotation.Nullable BigDecimal buyTransactionValue) {
    this.buyTransactionValue = buyTransactionValue;
  }


  public BrokerageCalculationResponse sellTransactionValue(@javax.annotation.Nullable BigDecimal sellTransactionValue) {
    this.sellTransactionValue = sellTransactionValue;
    return this;
  }

  /**
   * Get sellTransactionValue
   * @return sellTransactionValue
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SELL_TRANSACTION_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getSellTransactionValue() {
    return sellTransactionValue;
  }


  @JsonProperty(value = JSON_PROPERTY_SELL_TRANSACTION_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSellTransactionValue(@javax.annotation.Nullable BigDecimal sellTransactionValue) {
    this.sellTransactionValue = sellTransactionValue;
  }


  public BrokerageCalculationResponse buyBrokerage(@javax.annotation.Nullable BigDecimal buyBrokerage) {
    this.buyBrokerage = buyBrokerage;
    return this;
  }

  /**
   * Get buyBrokerage
   * @return buyBrokerage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUY_BROKERAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBuyBrokerage() {
    return buyBrokerage;
  }


  @JsonProperty(value = JSON_PROPERTY_BUY_BROKERAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuyBrokerage(@javax.annotation.Nullable BigDecimal buyBrokerage) {
    this.buyBrokerage = buyBrokerage;
  }


  public BrokerageCalculationResponse sellBrokerage(@javax.annotation.Nullable BigDecimal sellBrokerage) {
    this.sellBrokerage = sellBrokerage;
    return this;
  }

  /**
   * Get sellBrokerage
   * @return sellBrokerage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SELL_BROKERAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getSellBrokerage() {
    return sellBrokerage;
  }


  @JsonProperty(value = JSON_PROPERTY_SELL_BROKERAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSellBrokerage(@javax.annotation.Nullable BigDecimal sellBrokerage) {
    this.sellBrokerage = sellBrokerage;
  }


  public BrokerageCalculationResponse buySTT(@javax.annotation.Nullable BigDecimal buySTT) {
    this.buySTT = buySTT;
    return this;
  }

  /**
   * Get buySTT
   * @return buySTT
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUY_S_T_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBuySTT() {
    return buySTT;
  }


  @JsonProperty(value = JSON_PROPERTY_BUY_S_T_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuySTT(@javax.annotation.Nullable BigDecimal buySTT) {
    this.buySTT = buySTT;
  }


  public BrokerageCalculationResponse sellSTT(@javax.annotation.Nullable BigDecimal sellSTT) {
    this.sellSTT = sellSTT;
    return this;
  }

  /**
   * Get sellSTT
   * @return sellSTT
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SELL_S_T_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getSellSTT() {
    return sellSTT;
  }


  @JsonProperty(value = JSON_PROPERTY_SELL_S_T_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSellSTT(@javax.annotation.Nullable BigDecimal sellSTT) {
    this.sellSTT = sellSTT;
  }


  public BrokerageCalculationResponse buyExchangeCharges(@javax.annotation.Nullable BigDecimal buyExchangeCharges) {
    this.buyExchangeCharges = buyExchangeCharges;
    return this;
  }

  /**
   * Get buyExchangeCharges
   * @return buyExchangeCharges
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUY_EXCHANGE_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBuyExchangeCharges() {
    return buyExchangeCharges;
  }


  @JsonProperty(value = JSON_PROPERTY_BUY_EXCHANGE_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuyExchangeCharges(@javax.annotation.Nullable BigDecimal buyExchangeCharges) {
    this.buyExchangeCharges = buyExchangeCharges;
  }


  public BrokerageCalculationResponse sellExchangeCharges(@javax.annotation.Nullable BigDecimal sellExchangeCharges) {
    this.sellExchangeCharges = sellExchangeCharges;
    return this;
  }

  /**
   * Get sellExchangeCharges
   * @return sellExchangeCharges
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SELL_EXCHANGE_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getSellExchangeCharges() {
    return sellExchangeCharges;
  }


  @JsonProperty(value = JSON_PROPERTY_SELL_EXCHANGE_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSellExchangeCharges(@javax.annotation.Nullable BigDecimal sellExchangeCharges) {
    this.sellExchangeCharges = sellExchangeCharges;
  }


  public BrokerageCalculationResponse buyGST(@javax.annotation.Nullable BigDecimal buyGST) {
    this.buyGST = buyGST;
    return this;
  }

  /**
   * Get buyGST
   * @return buyGST
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUY_G_S_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBuyGST() {
    return buyGST;
  }


  @JsonProperty(value = JSON_PROPERTY_BUY_G_S_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuyGST(@javax.annotation.Nullable BigDecimal buyGST) {
    this.buyGST = buyGST;
  }


  public BrokerageCalculationResponse sellGST(@javax.annotation.Nullable BigDecimal sellGST) {
    this.sellGST = sellGST;
    return this;
  }

  /**
   * Get sellGST
   * @return sellGST
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SELL_G_S_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getSellGST() {
    return sellGST;
  }


  @JsonProperty(value = JSON_PROPERTY_SELL_G_S_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSellGST(@javax.annotation.Nullable BigDecimal sellGST) {
    this.sellGST = sellGST;
  }


  public BrokerageCalculationResponse buySEBICharges(@javax.annotation.Nullable BigDecimal buySEBICharges) {
    this.buySEBICharges = buySEBICharges;
    return this;
  }

  /**
   * Get buySEBICharges
   * @return buySEBICharges
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUY_S_E_B_I_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBuySEBICharges() {
    return buySEBICharges;
  }


  @JsonProperty(value = JSON_PROPERTY_BUY_S_E_B_I_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuySEBICharges(@javax.annotation.Nullable BigDecimal buySEBICharges) {
    this.buySEBICharges = buySEBICharges;
  }


  public BrokerageCalculationResponse sellSEBICharges(@javax.annotation.Nullable BigDecimal sellSEBICharges) {
    this.sellSEBICharges = sellSEBICharges;
    return this;
  }

  /**
   * Get sellSEBICharges
   * @return sellSEBICharges
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SELL_S_E_B_I_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getSellSEBICharges() {
    return sellSEBICharges;
  }


  @JsonProperty(value = JSON_PROPERTY_SELL_S_E_B_I_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSellSEBICharges(@javax.annotation.Nullable BigDecimal sellSEBICharges) {
    this.sellSEBICharges = sellSEBICharges;
  }


  public BrokerageCalculationResponse buyStampDuty(@javax.annotation.Nullable BigDecimal buyStampDuty) {
    this.buyStampDuty = buyStampDuty;
    return this;
  }

  /**
   * Get buyStampDuty
   * @return buyStampDuty
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUY_STAMP_DUTY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBuyStampDuty() {
    return buyStampDuty;
  }


  @JsonProperty(value = JSON_PROPERTY_BUY_STAMP_DUTY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuyStampDuty(@javax.annotation.Nullable BigDecimal buyStampDuty) {
    this.buyStampDuty = buyStampDuty;
  }


  public BrokerageCalculationResponse sellStampDuty(@javax.annotation.Nullable BigDecimal sellStampDuty) {
    this.sellStampDuty = sellStampDuty;
    return this;
  }

  /**
   * Get sellStampDuty
   * @return sellStampDuty
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SELL_STAMP_DUTY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getSellStampDuty() {
    return sellStampDuty;
  }


  @JsonProperty(value = JSON_PROPERTY_SELL_STAMP_DUTY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSellStampDuty(@javax.annotation.Nullable BigDecimal sellStampDuty) {
    this.sellStampDuty = sellStampDuty;
  }


  public BrokerageCalculationResponse dpCharges(@javax.annotation.Nullable BigDecimal dpCharges) {
    this.dpCharges = dpCharges;
    return this;
  }

  /**
   * Get dpCharges
   * @return dpCharges
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DP_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getDpCharges() {
    return dpCharges;
  }


  @JsonProperty(value = JSON_PROPERTY_DP_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDpCharges(@javax.annotation.Nullable BigDecimal dpCharges) {
    this.dpCharges = dpCharges;
  }


  public BrokerageCalculationResponse totalBuyCharges(@javax.annotation.Nullable BigDecimal totalBuyCharges) {
    this.totalBuyCharges = totalBuyCharges;
    return this;
  }

  /**
   * Get totalBuyCharges
   * @return totalBuyCharges
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_BUY_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getTotalBuyCharges() {
    return totalBuyCharges;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_BUY_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalBuyCharges(@javax.annotation.Nullable BigDecimal totalBuyCharges) {
    this.totalBuyCharges = totalBuyCharges;
  }


  public BrokerageCalculationResponse totalSellCharges(@javax.annotation.Nullable BigDecimal totalSellCharges) {
    this.totalSellCharges = totalSellCharges;
    return this;
  }

  /**
   * Get totalSellCharges
   * @return totalSellCharges
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_SELL_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getTotalSellCharges() {
    return totalSellCharges;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_SELL_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalSellCharges(@javax.annotation.Nullable BigDecimal totalSellCharges) {
    this.totalSellCharges = totalSellCharges;
  }


  public BrokerageCalculationResponse totalCharges(@javax.annotation.Nullable BigDecimal totalCharges) {
    this.totalCharges = totalCharges;
    return this;
  }

  /**
   * Get totalCharges
   * @return totalCharges
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getTotalCharges() {
    return totalCharges;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalCharges(@javax.annotation.Nullable BigDecimal totalCharges) {
    this.totalCharges = totalCharges;
  }


  public BrokerageCalculationResponse netProfitLoss(@javax.annotation.Nullable BigDecimal netProfitLoss) {
    this.netProfitLoss = netProfitLoss;
    return this;
  }

  /**
   * Get netProfitLoss
   * @return netProfitLoss
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NET_PROFIT_LOSS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getNetProfitLoss() {
    return netProfitLoss;
  }


  @JsonProperty(value = JSON_PROPERTY_NET_PROFIT_LOSS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetProfitLoss(@javax.annotation.Nullable BigDecimal netProfitLoss) {
    this.netProfitLoss = netProfitLoss;
  }


  public BrokerageCalculationResponse chargesPercentage(@javax.annotation.Nullable BigDecimal chargesPercentage) {
    this.chargesPercentage = chargesPercentage;
    return this;
  }

  /**
   * Get chargesPercentage
   * @return chargesPercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHARGES_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getChargesPercentage() {
    return chargesPercentage;
  }


  @JsonProperty(value = JSON_PROPERTY_CHARGES_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChargesPercentage(@javax.annotation.Nullable BigDecimal chargesPercentage) {
    this.chargesPercentage = chargesPercentage;
  }


  public BrokerageCalculationResponse breakEvenPrice(@javax.annotation.Nullable BigDecimal breakEvenPrice) {
    this.breakEvenPrice = breakEvenPrice;
    return this;
  }

  /**
   * Get breakEvenPrice
   * @return breakEvenPrice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BREAK_EVEN_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBreakEvenPrice() {
    return breakEvenPrice;
  }


  @JsonProperty(value = JSON_PROPERTY_BREAK_EVEN_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBreakEvenPrice(@javax.annotation.Nullable BigDecimal breakEvenPrice) {
    this.breakEvenPrice = breakEvenPrice;
  }


  public BrokerageCalculationResponse status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public BrokerageCalculationResponse error(@javax.annotation.Nullable String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getError() {
    return error;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(@javax.annotation.Nullable String error) {
    this.error = error;
  }


  /**
   * Return true if this BrokerageCalculationResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrokerageCalculationResponse brokerageCalculationResponse = (BrokerageCalculationResponse) o;
    return Objects.equals(this.buyTransactionValue, brokerageCalculationResponse.buyTransactionValue) &&
        Objects.equals(this.sellTransactionValue, brokerageCalculationResponse.sellTransactionValue) &&
        Objects.equals(this.buyBrokerage, brokerageCalculationResponse.buyBrokerage) &&
        Objects.equals(this.sellBrokerage, brokerageCalculationResponse.sellBrokerage) &&
        Objects.equals(this.buySTT, brokerageCalculationResponse.buySTT) &&
        Objects.equals(this.sellSTT, brokerageCalculationResponse.sellSTT) &&
        Objects.equals(this.buyExchangeCharges, brokerageCalculationResponse.buyExchangeCharges) &&
        Objects.equals(this.sellExchangeCharges, brokerageCalculationResponse.sellExchangeCharges) &&
        Objects.equals(this.buyGST, brokerageCalculationResponse.buyGST) &&
        Objects.equals(this.sellGST, brokerageCalculationResponse.sellGST) &&
        Objects.equals(this.buySEBICharges, brokerageCalculationResponse.buySEBICharges) &&
        Objects.equals(this.sellSEBICharges, brokerageCalculationResponse.sellSEBICharges) &&
        Objects.equals(this.buyStampDuty, brokerageCalculationResponse.buyStampDuty) &&
        Objects.equals(this.sellStampDuty, brokerageCalculationResponse.sellStampDuty) &&
        Objects.equals(this.dpCharges, brokerageCalculationResponse.dpCharges) &&
        Objects.equals(this.totalBuyCharges, brokerageCalculationResponse.totalBuyCharges) &&
        Objects.equals(this.totalSellCharges, brokerageCalculationResponse.totalSellCharges) &&
        Objects.equals(this.totalCharges, brokerageCalculationResponse.totalCharges) &&
        Objects.equals(this.netProfitLoss, brokerageCalculationResponse.netProfitLoss) &&
        Objects.equals(this.chargesPercentage, brokerageCalculationResponse.chargesPercentage) &&
        Objects.equals(this.breakEvenPrice, brokerageCalculationResponse.breakEvenPrice) &&
        Objects.equals(this.status, brokerageCalculationResponse.status) &&
        Objects.equals(this.error, brokerageCalculationResponse.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buyTransactionValue, sellTransactionValue, buyBrokerage, sellBrokerage, buySTT, sellSTT, buyExchangeCharges, sellExchangeCharges, buyGST, sellGST, buySEBICharges, sellSEBICharges, buyStampDuty, sellStampDuty, dpCharges, totalBuyCharges, totalSellCharges, totalCharges, netProfitLoss, chargesPercentage, breakEvenPrice, status, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrokerageCalculationResponse {\n");
    sb.append("    buyTransactionValue: ").append(toIndentedString(buyTransactionValue)).append("\n");
    sb.append("    sellTransactionValue: ").append(toIndentedString(sellTransactionValue)).append("\n");
    sb.append("    buyBrokerage: ").append(toIndentedString(buyBrokerage)).append("\n");
    sb.append("    sellBrokerage: ").append(toIndentedString(sellBrokerage)).append("\n");
    sb.append("    buySTT: ").append(toIndentedString(buySTT)).append("\n");
    sb.append("    sellSTT: ").append(toIndentedString(sellSTT)).append("\n");
    sb.append("    buyExchangeCharges: ").append(toIndentedString(buyExchangeCharges)).append("\n");
    sb.append("    sellExchangeCharges: ").append(toIndentedString(sellExchangeCharges)).append("\n");
    sb.append("    buyGST: ").append(toIndentedString(buyGST)).append("\n");
    sb.append("    sellGST: ").append(toIndentedString(sellGST)).append("\n");
    sb.append("    buySEBICharges: ").append(toIndentedString(buySEBICharges)).append("\n");
    sb.append("    sellSEBICharges: ").append(toIndentedString(sellSEBICharges)).append("\n");
    sb.append("    buyStampDuty: ").append(toIndentedString(buyStampDuty)).append("\n");
    sb.append("    sellStampDuty: ").append(toIndentedString(sellStampDuty)).append("\n");
    sb.append("    dpCharges: ").append(toIndentedString(dpCharges)).append("\n");
    sb.append("    totalBuyCharges: ").append(toIndentedString(totalBuyCharges)).append("\n");
    sb.append("    totalSellCharges: ").append(toIndentedString(totalSellCharges)).append("\n");
    sb.append("    totalCharges: ").append(toIndentedString(totalCharges)).append("\n");
    sb.append("    netProfitLoss: ").append(toIndentedString(netProfitLoss)).append("\n");
    sb.append("    chargesPercentage: ").append(toIndentedString(chargesPercentage)).append("\n");
    sb.append("    breakEvenPrice: ").append(toIndentedString(breakEvenPrice)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `buyTransactionValue` to the URL query string
    if (getBuyTransactionValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbuyTransactionValue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBuyTransactionValue()))));
    }

    // add `sellTransactionValue` to the URL query string
    if (getSellTransactionValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssellTransactionValue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSellTransactionValue()))));
    }

    // add `buyBrokerage` to the URL query string
    if (getBuyBrokerage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbuyBrokerage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBuyBrokerage()))));
    }

    // add `sellBrokerage` to the URL query string
    if (getSellBrokerage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssellBrokerage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSellBrokerage()))));
    }

    // add `buySTT` to the URL query string
    if (getBuySTT() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbuySTT%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBuySTT()))));
    }

    // add `sellSTT` to the URL query string
    if (getSellSTT() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssellSTT%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSellSTT()))));
    }

    // add `buyExchangeCharges` to the URL query string
    if (getBuyExchangeCharges() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbuyExchangeCharges%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBuyExchangeCharges()))));
    }

    // add `sellExchangeCharges` to the URL query string
    if (getSellExchangeCharges() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssellExchangeCharges%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSellExchangeCharges()))));
    }

    // add `buyGST` to the URL query string
    if (getBuyGST() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbuyGST%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBuyGST()))));
    }

    // add `sellGST` to the URL query string
    if (getSellGST() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssellGST%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSellGST()))));
    }

    // add `buySEBICharges` to the URL query string
    if (getBuySEBICharges() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbuySEBICharges%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBuySEBICharges()))));
    }

    // add `sellSEBICharges` to the URL query string
    if (getSellSEBICharges() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssellSEBICharges%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSellSEBICharges()))));
    }

    // add `buyStampDuty` to the URL query string
    if (getBuyStampDuty() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbuyStampDuty%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBuyStampDuty()))));
    }

    // add `sellStampDuty` to the URL query string
    if (getSellStampDuty() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssellStampDuty%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSellStampDuty()))));
    }

    // add `dpCharges` to the URL query string
    if (getDpCharges() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdpCharges%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDpCharges()))));
    }

    // add `totalBuyCharges` to the URL query string
    if (getTotalBuyCharges() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalBuyCharges%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalBuyCharges()))));
    }

    // add `totalSellCharges` to the URL query string
    if (getTotalSellCharges() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalSellCharges%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalSellCharges()))));
    }

    // add `totalCharges` to the URL query string
    if (getTotalCharges() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalCharges%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalCharges()))));
    }

    // add `netProfitLoss` to the URL query string
    if (getNetProfitLoss() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snetProfitLoss%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNetProfitLoss()))));
    }

    // add `chargesPercentage` to the URL query string
    if (getChargesPercentage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schargesPercentage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChargesPercentage()))));
    }

    // add `breakEvenPrice` to the URL query string
    if (getBreakEvenPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbreakEvenPrice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBreakEvenPrice()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serror%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getError()))));
    }

    return joiner.toString();
  }
}

