/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * BrokerageCalculationRequest
 */
@JsonPropertyOrder({
  BrokerageCalculationRequest.JSON_PROPERTY_TRADING_SYMBOL,
  BrokerageCalculationRequest.JSON_PROPERTY_QUANTITY,
  BrokerageCalculationRequest.JSON_PROPERTY_BUY_PRICE,
  BrokerageCalculationRequest.JSON_PROPERTY_SELL_PRICE,
  BrokerageCalculationRequest.JSON_PROPERTY_EXCHANGE,
  BrokerageCalculationRequest.JSON_PROPERTY_TRADE_TYPE,
  BrokerageCalculationRequest.JSON_PROPERTY_BROKER_TYPE,
  BrokerageCalculationRequest.JSON_PROPERTY_BROKER_NAME,
  BrokerageCalculationRequest.JSON_PROPERTY_BROKER_FLAT_FEE,
  BrokerageCalculationRequest.JSON_PROPERTY_BROKER_PERCENTAGE_FEE,
  BrokerageCalculationRequest.JSON_PROPERTY_STATE_CODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class BrokerageCalculationRequest {
  public static final String JSON_PROPERTY_TRADING_SYMBOL = "tradingSymbol";
  @javax.annotation.Nullable
  private String tradingSymbol;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  @javax.annotation.Nullable
  private Integer quantity;

  public static final String JSON_PROPERTY_BUY_PRICE = "buyPrice";
  @javax.annotation.Nullable
  private BigDecimal buyPrice;

  public static final String JSON_PROPERTY_SELL_PRICE = "sellPrice";
  @javax.annotation.Nullable
  private BigDecimal sellPrice;

  public static final String JSON_PROPERTY_EXCHANGE = "exchange";
  @javax.annotation.Nullable
  private String exchange;

  /**
   * Gets or Sets tradeType
   */
  public enum TradeTypeEnum {
    DELIVERY(String.valueOf("DELIVERY")),
    
    INTRADAY(String.valueOf("INTRADAY"));

    private String value;

    TradeTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TradeTypeEnum fromValue(String value) {
      for (TradeTypeEnum b : TradeTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TRADE_TYPE = "tradeType";
  @javax.annotation.Nullable
  private TradeTypeEnum tradeType;

  /**
   * Gets or Sets brokerType
   */
  public enum BrokerTypeEnum {
    DISCOUNT(String.valueOf("DISCOUNT")),
    
    FULL_SERVICE(String.valueOf("FULL_SERVICE"));

    private String value;

    BrokerTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static BrokerTypeEnum fromValue(String value) {
      for (BrokerTypeEnum b : BrokerTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_BROKER_TYPE = "brokerType";
  @javax.annotation.Nullable
  private BrokerTypeEnum brokerType;

  public static final String JSON_PROPERTY_BROKER_NAME = "brokerName";
  @javax.annotation.Nullable
  private String brokerName;

  public static final String JSON_PROPERTY_BROKER_FLAT_FEE = "brokerFlatFee";
  @javax.annotation.Nullable
  private BigDecimal brokerFlatFee;

  public static final String JSON_PROPERTY_BROKER_PERCENTAGE_FEE = "brokerPercentageFee";
  @javax.annotation.Nullable
  private BigDecimal brokerPercentageFee;

  public static final String JSON_PROPERTY_STATE_CODE = "stateCode";
  @javax.annotation.Nullable
  private String stateCode;

  public BrokerageCalculationRequest() { 
  }

  public BrokerageCalculationRequest tradingSymbol(@javax.annotation.Nullable String tradingSymbol) {
    this.tradingSymbol = tradingSymbol;
    return this;
  }

  /**
   * Get tradingSymbol
   * @return tradingSymbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRADING_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTradingSymbol() {
    return tradingSymbol;
  }


  @JsonProperty(value = JSON_PROPERTY_TRADING_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTradingSymbol(@javax.annotation.Nullable String tradingSymbol) {
    this.tradingSymbol = tradingSymbol;
  }


  public BrokerageCalculationRequest quantity(@javax.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Get quantity
   * @return quantity
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getQuantity() {
    return quantity;
  }


  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(@javax.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
  }


  public BrokerageCalculationRequest buyPrice(@javax.annotation.Nullable BigDecimal buyPrice) {
    this.buyPrice = buyPrice;
    return this;
  }

  /**
   * Get buyPrice
   * @return buyPrice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBuyPrice() {
    return buyPrice;
  }


  @JsonProperty(value = JSON_PROPERTY_BUY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuyPrice(@javax.annotation.Nullable BigDecimal buyPrice) {
    this.buyPrice = buyPrice;
  }


  public BrokerageCalculationRequest sellPrice(@javax.annotation.Nullable BigDecimal sellPrice) {
    this.sellPrice = sellPrice;
    return this;
  }

  /**
   * Get sellPrice
   * @return sellPrice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SELL_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getSellPrice() {
    return sellPrice;
  }


  @JsonProperty(value = JSON_PROPERTY_SELL_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSellPrice(@javax.annotation.Nullable BigDecimal sellPrice) {
    this.sellPrice = sellPrice;
  }


  public BrokerageCalculationRequest exchange(@javax.annotation.Nullable String exchange) {
    this.exchange = exchange;
    return this;
  }

  /**
   * Get exchange
   * @return exchange
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getExchange() {
    return exchange;
  }


  @JsonProperty(value = JSON_PROPERTY_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchange(@javax.annotation.Nullable String exchange) {
    this.exchange = exchange;
  }


  public BrokerageCalculationRequest tradeType(@javax.annotation.Nullable TradeTypeEnum tradeType) {
    this.tradeType = tradeType;
    return this;
  }

  /**
   * Get tradeType
   * @return tradeType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRADE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TradeTypeEnum getTradeType() {
    return tradeType;
  }


  @JsonProperty(value = JSON_PROPERTY_TRADE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTradeType(@javax.annotation.Nullable TradeTypeEnum tradeType) {
    this.tradeType = tradeType;
  }


  public BrokerageCalculationRequest brokerType(@javax.annotation.Nullable BrokerTypeEnum brokerType) {
    this.brokerType = brokerType;
    return this;
  }

  /**
   * Get brokerType
   * @return brokerType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BROKER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BrokerTypeEnum getBrokerType() {
    return brokerType;
  }


  @JsonProperty(value = JSON_PROPERTY_BROKER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrokerType(@javax.annotation.Nullable BrokerTypeEnum brokerType) {
    this.brokerType = brokerType;
  }


  public BrokerageCalculationRequest brokerName(@javax.annotation.Nullable String brokerName) {
    this.brokerName = brokerName;
    return this;
  }

  /**
   * Get brokerName
   * @return brokerName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BROKER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBrokerName() {
    return brokerName;
  }


  @JsonProperty(value = JSON_PROPERTY_BROKER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrokerName(@javax.annotation.Nullable String brokerName) {
    this.brokerName = brokerName;
  }


  public BrokerageCalculationRequest brokerFlatFee(@javax.annotation.Nullable BigDecimal brokerFlatFee) {
    this.brokerFlatFee = brokerFlatFee;
    return this;
  }

  /**
   * Get brokerFlatFee
   * @return brokerFlatFee
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BROKER_FLAT_FEE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBrokerFlatFee() {
    return brokerFlatFee;
  }


  @JsonProperty(value = JSON_PROPERTY_BROKER_FLAT_FEE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrokerFlatFee(@javax.annotation.Nullable BigDecimal brokerFlatFee) {
    this.brokerFlatFee = brokerFlatFee;
  }


  public BrokerageCalculationRequest brokerPercentageFee(@javax.annotation.Nullable BigDecimal brokerPercentageFee) {
    this.brokerPercentageFee = brokerPercentageFee;
    return this;
  }

  /**
   * Get brokerPercentageFee
   * @return brokerPercentageFee
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BROKER_PERCENTAGE_FEE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBrokerPercentageFee() {
    return brokerPercentageFee;
  }


  @JsonProperty(value = JSON_PROPERTY_BROKER_PERCENTAGE_FEE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrokerPercentageFee(@javax.annotation.Nullable BigDecimal brokerPercentageFee) {
    this.brokerPercentageFee = brokerPercentageFee;
  }


  public BrokerageCalculationRequest stateCode(@javax.annotation.Nullable String stateCode) {
    this.stateCode = stateCode;
    return this;
  }

  /**
   * Get stateCode
   * @return stateCode
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATE_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStateCode() {
    return stateCode;
  }


  @JsonProperty(value = JSON_PROPERTY_STATE_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStateCode(@javax.annotation.Nullable String stateCode) {
    this.stateCode = stateCode;
  }


  /**
   * Return true if this BrokerageCalculationRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrokerageCalculationRequest brokerageCalculationRequest = (BrokerageCalculationRequest) o;
    return Objects.equals(this.tradingSymbol, brokerageCalculationRequest.tradingSymbol) &&
        Objects.equals(this.quantity, brokerageCalculationRequest.quantity) &&
        Objects.equals(this.buyPrice, brokerageCalculationRequest.buyPrice) &&
        Objects.equals(this.sellPrice, brokerageCalculationRequest.sellPrice) &&
        Objects.equals(this.exchange, brokerageCalculationRequest.exchange) &&
        Objects.equals(this.tradeType, brokerageCalculationRequest.tradeType) &&
        Objects.equals(this.brokerType, brokerageCalculationRequest.brokerType) &&
        Objects.equals(this.brokerName, brokerageCalculationRequest.brokerName) &&
        Objects.equals(this.brokerFlatFee, brokerageCalculationRequest.brokerFlatFee) &&
        Objects.equals(this.brokerPercentageFee, brokerageCalculationRequest.brokerPercentageFee) &&
        Objects.equals(this.stateCode, brokerageCalculationRequest.stateCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tradingSymbol, quantity, buyPrice, sellPrice, exchange, tradeType, brokerType, brokerName, brokerFlatFee, brokerPercentageFee, stateCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrokerageCalculationRequest {\n");
    sb.append("    tradingSymbol: ").append(toIndentedString(tradingSymbol)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    buyPrice: ").append(toIndentedString(buyPrice)).append("\n");
    sb.append("    sellPrice: ").append(toIndentedString(sellPrice)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    tradeType: ").append(toIndentedString(tradeType)).append("\n");
    sb.append("    brokerType: ").append(toIndentedString(brokerType)).append("\n");
    sb.append("    brokerName: ").append(toIndentedString(brokerName)).append("\n");
    sb.append("    brokerFlatFee: ").append(toIndentedString(brokerFlatFee)).append("\n");
    sb.append("    brokerPercentageFee: ").append(toIndentedString(brokerPercentageFee)).append("\n");
    sb.append("    stateCode: ").append(toIndentedString(stateCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `tradingSymbol` to the URL query string
    if (getTradingSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stradingSymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTradingSymbol()))));
    }

    // add `quantity` to the URL query string
    if (getQuantity() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squantity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuantity()))));
    }

    // add `buyPrice` to the URL query string
    if (getBuyPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbuyPrice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBuyPrice()))));
    }

    // add `sellPrice` to the URL query string
    if (getSellPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssellPrice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSellPrice()))));
    }

    // add `exchange` to the URL query string
    if (getExchange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexchange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExchange()))));
    }

    // add `tradeType` to the URL query string
    if (getTradeType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stradeType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTradeType()))));
    }

    // add `brokerType` to the URL query string
    if (getBrokerType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbrokerType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBrokerType()))));
    }

    // add `brokerName` to the URL query string
    if (getBrokerName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbrokerName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBrokerName()))));
    }

    // add `brokerFlatFee` to the URL query string
    if (getBrokerFlatFee() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbrokerFlatFee%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBrokerFlatFee()))));
    }

    // add `brokerPercentageFee` to the URL query string
    if (getBrokerPercentageFee() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbrokerPercentageFee%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBrokerPercentageFee()))));
    }

    // add `stateCode` to the URL query string
    if (getStateCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstateCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStateCode()))));
    }

    return joiner.toString();
  }
}

