/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.marketdata.model.OHLCVTPoint;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * HistoricalData
 */
@JsonPropertyOrder({
  HistoricalData.JSON_PROPERTY_TRADING_SYMBOL,
  HistoricalData.JSON_PROPERTY_ISIN,
  HistoricalData.JSON_PROPERTY_FROM_DATE,
  HistoricalData.JSON_PROPERTY_TO_DATE,
  HistoricalData.JSON_PROPERTY_INTERVAL,
  HistoricalData.JSON_PROPERTY_DATA_POINTS,
  HistoricalData.JSON_PROPERTY_DATA_POINT_COUNT,
  HistoricalData.JSON_PROPERTY_EXCHANGE,
  HistoricalData.JSON_PROPERTY_CURRENCY,
  HistoricalData.JSON_PROPERTY_RETRIEVAL_TIME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class HistoricalData {
  public static final String JSON_PROPERTY_TRADING_SYMBOL = "tradingSymbol";
  @javax.annotation.Nullable
  private String tradingSymbol;

  public static final String JSON_PROPERTY_ISIN = "isin";
  @javax.annotation.Nullable
  private String isin;

  public static final String JSON_PROPERTY_FROM_DATE = "fromDate";
  @javax.annotation.Nullable
  private OffsetDateTime fromDate;

  public static final String JSON_PROPERTY_TO_DATE = "toDate";
  @javax.annotation.Nullable
  private OffsetDateTime toDate;

  public static final String JSON_PROPERTY_INTERVAL = "interval";
  @javax.annotation.Nullable
  private String interval;

  public static final String JSON_PROPERTY_DATA_POINTS = "dataPoints";
  @javax.annotation.Nullable
  private List<OHLCVTPoint> dataPoints = new ArrayList<>();

  public static final String JSON_PROPERTY_DATA_POINT_COUNT = "dataPointCount";
  @javax.annotation.Nullable
  private Integer dataPointCount;

  public static final String JSON_PROPERTY_EXCHANGE = "exchange";
  @javax.annotation.Nullable
  private String exchange;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nullable
  private String currency;

  public static final String JSON_PROPERTY_RETRIEVAL_TIME = "retrievalTime";
  @javax.annotation.Nullable
  private OffsetDateTime retrievalTime;

  public HistoricalData() { 
  }

  public HistoricalData tradingSymbol(@javax.annotation.Nullable String tradingSymbol) {
    this.tradingSymbol = tradingSymbol;
    return this;
  }

  /**
   * Get tradingSymbol
   * @return tradingSymbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRADING_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTradingSymbol() {
    return tradingSymbol;
  }


  @JsonProperty(value = JSON_PROPERTY_TRADING_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTradingSymbol(@javax.annotation.Nullable String tradingSymbol) {
    this.tradingSymbol = tradingSymbol;
  }


  public HistoricalData isin(@javax.annotation.Nullable String isin) {
    this.isin = isin;
    return this;
  }

  /**
   * Get isin
   * @return isin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ISIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIsin() {
    return isin;
  }


  @JsonProperty(value = JSON_PROPERTY_ISIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsin(@javax.annotation.Nullable String isin) {
    this.isin = isin;
  }


  public HistoricalData fromDate(@javax.annotation.Nullable OffsetDateTime fromDate) {
    this.fromDate = fromDate;
    return this;
  }

  /**
   * Get fromDate
   * @return fromDate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FROM_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getFromDate() {
    return fromDate;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromDate(@javax.annotation.Nullable OffsetDateTime fromDate) {
    this.fromDate = fromDate;
  }


  public HistoricalData toDate(@javax.annotation.Nullable OffsetDateTime toDate) {
    this.toDate = toDate;
    return this;
  }

  /**
   * Get toDate
   * @return toDate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TO_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getToDate() {
    return toDate;
  }


  @JsonProperty(value = JSON_PROPERTY_TO_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToDate(@javax.annotation.Nullable OffsetDateTime toDate) {
    this.toDate = toDate;
  }


  public HistoricalData interval(@javax.annotation.Nullable String interval) {
    this.interval = interval;
    return this;
  }

  /**
   * Get interval
   * @return interval
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INTERVAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getInterval() {
    return interval;
  }


  @JsonProperty(value = JSON_PROPERTY_INTERVAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterval(@javax.annotation.Nullable String interval) {
    this.interval = interval;
  }


  public HistoricalData dataPoints(@javax.annotation.Nullable List<OHLCVTPoint> dataPoints) {
    this.dataPoints = dataPoints;
    return this;
  }

  public HistoricalData addDataPointsItem(OHLCVTPoint dataPointsItem) {
    if (this.dataPoints == null) {
      this.dataPoints = new ArrayList<>();
    }
    this.dataPoints.add(dataPointsItem);
    return this;
  }

  /**
   * Get dataPoints
   * @return dataPoints
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA_POINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<OHLCVTPoint> getDataPoints() {
    return dataPoints;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA_POINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataPoints(@javax.annotation.Nullable List<OHLCVTPoint> dataPoints) {
    this.dataPoints = dataPoints;
  }


  public HistoricalData dataPointCount(@javax.annotation.Nullable Integer dataPointCount) {
    this.dataPointCount = dataPointCount;
    return this;
  }

  /**
   * Get dataPointCount
   * @return dataPointCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA_POINT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDataPointCount() {
    return dataPointCount;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA_POINT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataPointCount(@javax.annotation.Nullable Integer dataPointCount) {
    this.dataPointCount = dataPointCount;
  }


  public HistoricalData exchange(@javax.annotation.Nullable String exchange) {
    this.exchange = exchange;
    return this;
  }

  /**
   * Get exchange
   * @return exchange
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getExchange() {
    return exchange;
  }


  @JsonProperty(value = JSON_PROPERTY_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchange(@javax.annotation.Nullable String exchange) {
    this.exchange = exchange;
  }


  public HistoricalData currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public HistoricalData retrievalTime(@javax.annotation.Nullable OffsetDateTime retrievalTime) {
    this.retrievalTime = retrievalTime;
    return this;
  }

  /**
   * Get retrievalTime
   * @return retrievalTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETRIEVAL_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getRetrievalTime() {
    return retrievalTime;
  }


  @JsonProperty(value = JSON_PROPERTY_RETRIEVAL_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetrievalTime(@javax.annotation.Nullable OffsetDateTime retrievalTime) {
    this.retrievalTime = retrievalTime;
  }


  /**
   * Return true if this HistoricalData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoricalData historicalData = (HistoricalData) o;
    return Objects.equals(this.tradingSymbol, historicalData.tradingSymbol) &&
        Objects.equals(this.isin, historicalData.isin) &&
        Objects.equals(this.fromDate, historicalData.fromDate) &&
        Objects.equals(this.toDate, historicalData.toDate) &&
        Objects.equals(this.interval, historicalData.interval) &&
        Objects.equals(this.dataPoints, historicalData.dataPoints) &&
        Objects.equals(this.dataPointCount, historicalData.dataPointCount) &&
        Objects.equals(this.exchange, historicalData.exchange) &&
        Objects.equals(this.currency, historicalData.currency) &&
        Objects.equals(this.retrievalTime, historicalData.retrievalTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tradingSymbol, isin, fromDate, toDate, interval, dataPoints, dataPointCount, exchange, currency, retrievalTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoricalData {\n");
    sb.append("    tradingSymbol: ").append(toIndentedString(tradingSymbol)).append("\n");
    sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
    sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
    sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    dataPoints: ").append(toIndentedString(dataPoints)).append("\n");
    sb.append("    dataPointCount: ").append(toIndentedString(dataPointCount)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    retrievalTime: ").append(toIndentedString(retrievalTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `tradingSymbol` to the URL query string
    if (getTradingSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stradingSymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTradingSymbol()))));
    }

    // add `isin` to the URL query string
    if (getIsin() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsin()))));
    }

    // add `fromDate` to the URL query string
    if (getFromDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfromDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFromDate()))));
    }

    // add `toDate` to the URL query string
    if (getToDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stoDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getToDate()))));
    }

    // add `interval` to the URL query string
    if (getInterval() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinterval%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInterval()))));
    }

    // add `dataPoints` to the URL query string
    if (getDataPoints() != null) {
      for (int i = 0; i < getDataPoints().size(); i++) {
        if (getDataPoints().get(i) != null) {
          joiner.add(getDataPoints().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdataPoints%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `dataPointCount` to the URL query string
    if (getDataPointCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdataPointCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDataPointCount()))));
    }

    // add `exchange` to the URL query string
    if (getExchange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexchange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExchange()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `retrievalTime` to the URL query string
    if (getRetrievalTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sretrievalTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRetrievalTime()))));
    }

    return joiner.toString();
  }
}

