/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * HistoricalDataRequest
 */
@JsonPropertyOrder({
  HistoricalDataRequest.JSON_PROPERTY_SYMBOLS,
  HistoricalDataRequest.JSON_PROPERTY_FROM,
  HistoricalDataRequest.JSON_PROPERTY_TO,
  HistoricalDataRequest.JSON_PROPERTY_INTERVAL,
  HistoricalDataRequest.JSON_PROPERTY_CONTINUOUS,
  HistoricalDataRequest.JSON_PROPERTY_INSTRUMENT_TYPE,
  HistoricalDataRequest.JSON_PROPERTY_FORCE_REFRESH,
  HistoricalDataRequest.JSON_PROPERTY_FILTER_TYPE,
  HistoricalDataRequest.JSON_PROPERTY_FILTER_FREQUENCY,
  HistoricalDataRequest.JSON_PROPERTY_ADDITIONAL_PARAMS,
  HistoricalDataRequest.JSON_PROPERTY_IS_INDEX_SYMBOL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class HistoricalDataRequest {
  public static final String JSON_PROPERTY_SYMBOLS = "symbols";
  @javax.annotation.Nullable
  private String symbols;

  public static final String JSON_PROPERTY_FROM = "from";
  @javax.annotation.Nullable
  private String from;

  public static final String JSON_PROPERTY_TO = "to";
  @javax.annotation.Nullable
  private String to;

  /**
   * Gets or Sets interval
   */
  public enum IntervalEnum {
    MINUTE(String.valueOf("MINUTE")),
    
    THREE_MINUTE(String.valueOf("THREE_MINUTE")),
    
    FIVE_MINUTE(String.valueOf("FIVE_MINUTE")),
    
    TEN_MINUTE(String.valueOf("TEN_MINUTE")),
    
    FIFTEEN_MINUTE(String.valueOf("FIFTEEN_MINUTE")),
    
    THIRTY_MINUTE(String.valueOf("THIRTY_MINUTE")),
    
    HOUR(String.valueOf("HOUR")),
    
    FOUR_HOUR(String.valueOf("FOUR_HOUR")),
    
    DAY(String.valueOf("DAY")),
    
    WEEK(String.valueOf("WEEK")),
    
    MONTH(String.valueOf("MONTH")),
    
    YEAR(String.valueOf("YEAR"));

    private String value;

    IntervalEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static IntervalEnum fromValue(String value) {
      for (IntervalEnum b : IntervalEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_INTERVAL = "interval";
  @javax.annotation.Nullable
  private IntervalEnum interval;

  public static final String JSON_PROPERTY_CONTINUOUS = "continuous";
  @javax.annotation.Nullable
  private Boolean continuous;

  public static final String JSON_PROPERTY_INSTRUMENT_TYPE = "instrumentType";
  @javax.annotation.Nullable
  private String instrumentType;

  public static final String JSON_PROPERTY_FORCE_REFRESH = "forceRefresh";
  @javax.annotation.Nullable
  private Boolean forceRefresh;

  public static final String JSON_PROPERTY_FILTER_TYPE = "filterType";
  @javax.annotation.Nullable
  private String filterType;

  public static final String JSON_PROPERTY_FILTER_FREQUENCY = "filterFrequency";
  @javax.annotation.Nullable
  private Integer filterFrequency;

  public static final String JSON_PROPERTY_ADDITIONAL_PARAMS = "additionalParams";
  @javax.annotation.Nullable
  private Map<String, Object> additionalParams = new HashMap<>();

  public static final String JSON_PROPERTY_IS_INDEX_SYMBOL = "isIndexSymbol";
  @javax.annotation.Nullable
  private Boolean isIndexSymbol;

  public HistoricalDataRequest() { 
  }

  public HistoricalDataRequest symbols(@javax.annotation.Nullable String symbols) {
    this.symbols = symbols;
    return this;
  }

  /**
   * Get symbols
   * @return symbols
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SYMBOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSymbols() {
    return symbols;
  }


  @JsonProperty(value = JSON_PROPERTY_SYMBOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbols(@javax.annotation.Nullable String symbols) {
    this.symbols = symbols;
  }


  public HistoricalDataRequest from(@javax.annotation.Nullable String from) {
    this.from = from;
    return this;
  }

  /**
   * Start date in yyyy-MM-dd format
   * @return from
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFrom() {
    return from;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFrom(@javax.annotation.Nullable String from) {
    this.from = from;
  }


  public HistoricalDataRequest to(@javax.annotation.Nullable String to) {
    this.to = to;
    return this;
  }

  /**
   * End date in yyyy-MM-dd format (optional, defaults to current date)
   * @return to
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTo() {
    return to;
  }


  @JsonProperty(value = JSON_PROPERTY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTo(@javax.annotation.Nullable String to) {
    this.to = to;
  }


  public HistoricalDataRequest interval(@javax.annotation.Nullable IntervalEnum interval) {
    this.interval = interval;
    return this;
  }

  /**
   * Get interval
   * @return interval
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INTERVAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public IntervalEnum getInterval() {
    return interval;
  }


  @JsonProperty(value = JSON_PROPERTY_INTERVAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterval(@javax.annotation.Nullable IntervalEnum interval) {
    this.interval = interval;
  }


  public HistoricalDataRequest continuous(@javax.annotation.Nullable Boolean continuous) {
    this.continuous = continuous;
    return this;
  }

  /**
   * Get continuous
   * @return continuous
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTINUOUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContinuous() {
    return continuous;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTINUOUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContinuous(@javax.annotation.Nullable Boolean continuous) {
    this.continuous = continuous;
  }


  public HistoricalDataRequest instrumentType(@javax.annotation.Nullable String instrumentType) {
    this.instrumentType = instrumentType;
    return this;
  }

  /**
   * Get instrumentType
   * @return instrumentType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INSTRUMENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getInstrumentType() {
    return instrumentType;
  }


  @JsonProperty(value = JSON_PROPERTY_INSTRUMENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstrumentType(@javax.annotation.Nullable String instrumentType) {
    this.instrumentType = instrumentType;
  }


  public HistoricalDataRequest forceRefresh(@javax.annotation.Nullable Boolean forceRefresh) {
    this.forceRefresh = forceRefresh;
    return this;
  }

  /**
   * Get forceRefresh
   * @return forceRefresh
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FORCE_REFRESH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getForceRefresh() {
    return forceRefresh;
  }


  @JsonProperty(value = JSON_PROPERTY_FORCE_REFRESH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForceRefresh(@javax.annotation.Nullable Boolean forceRefresh) {
    this.forceRefresh = forceRefresh;
  }


  public HistoricalDataRequest filterType(@javax.annotation.Nullable String filterType) {
    this.filterType = filterType;
    return this;
  }

  /**
   * Get filterType
   * @return filterType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILTER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFilterType() {
    return filterType;
  }


  @JsonProperty(value = JSON_PROPERTY_FILTER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilterType(@javax.annotation.Nullable String filterType) {
    this.filterType = filterType;
  }


  public HistoricalDataRequest filterFrequency(@javax.annotation.Nullable Integer filterFrequency) {
    this.filterFrequency = filterFrequency;
    return this;
  }

  /**
   * Get filterFrequency
   * @return filterFrequency
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILTER_FREQUENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getFilterFrequency() {
    return filterFrequency;
  }


  @JsonProperty(value = JSON_PROPERTY_FILTER_FREQUENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilterFrequency(@javax.annotation.Nullable Integer filterFrequency) {
    this.filterFrequency = filterFrequency;
  }


  public HistoricalDataRequest additionalParams(@javax.annotation.Nullable Map<String, Object> additionalParams) {
    this.additionalParams = additionalParams;
    return this;
  }

  public HistoricalDataRequest putAdditionalParamsItem(String key, Object additionalParamsItem) {
    if (this.additionalParams == null) {
      this.additionalParams = new HashMap<>();
    }
    this.additionalParams.put(key, additionalParamsItem);
    return this;
  }

  /**
   * Get additionalParams
   * @return additionalParams
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_PARAMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getAdditionalParams() {
    return additionalParams;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_PARAMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalParams(@javax.annotation.Nullable Map<String, Object> additionalParams) {
    this.additionalParams = additionalParams;
  }


  public HistoricalDataRequest isIndexSymbol(@javax.annotation.Nullable Boolean isIndexSymbol) {
    this.isIndexSymbol = isIndexSymbol;
    return this;
  }

  /**
   * Whether the symbols represent indices that should be expanded to constituent stocks
   * @return isIndexSymbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsIndexSymbol() {
    return isIndexSymbol;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsIndexSymbol(@javax.annotation.Nullable Boolean isIndexSymbol) {
    this.isIndexSymbol = isIndexSymbol;
  }


  /**
   * Return true if this HistoricalDataRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoricalDataRequest historicalDataRequest = (HistoricalDataRequest) o;
    return Objects.equals(this.symbols, historicalDataRequest.symbols) &&
        Objects.equals(this.from, historicalDataRequest.from) &&
        Objects.equals(this.to, historicalDataRequest.to) &&
        Objects.equals(this.interval, historicalDataRequest.interval) &&
        Objects.equals(this.continuous, historicalDataRequest.continuous) &&
        Objects.equals(this.instrumentType, historicalDataRequest.instrumentType) &&
        Objects.equals(this.forceRefresh, historicalDataRequest.forceRefresh) &&
        Objects.equals(this.filterType, historicalDataRequest.filterType) &&
        Objects.equals(this.filterFrequency, historicalDataRequest.filterFrequency) &&
        Objects.equals(this.additionalParams, historicalDataRequest.additionalParams) &&
        Objects.equals(this.isIndexSymbol, historicalDataRequest.isIndexSymbol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbols, from, to, interval, continuous, instrumentType, forceRefresh, filterType, filterFrequency, additionalParams, isIndexSymbol);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoricalDataRequest {\n");
    sb.append("    symbols: ").append(toIndentedString(symbols)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    continuous: ").append(toIndentedString(continuous)).append("\n");
    sb.append("    instrumentType: ").append(toIndentedString(instrumentType)).append("\n");
    sb.append("    forceRefresh: ").append(toIndentedString(forceRefresh)).append("\n");
    sb.append("    filterType: ").append(toIndentedString(filterType)).append("\n");
    sb.append("    filterFrequency: ").append(toIndentedString(filterFrequency)).append("\n");
    sb.append("    additionalParams: ").append(toIndentedString(additionalParams)).append("\n");
    sb.append("    isIndexSymbol: ").append(toIndentedString(isIndexSymbol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `symbols` to the URL query string
    if (getSymbols() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssymbols%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSymbols()))));
    }

    // add `from` to the URL query string
    if (getFrom() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfrom%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFrom()))));
    }

    // add `to` to the URL query string
    if (getTo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sto%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTo()))));
    }

    // add `interval` to the URL query string
    if (getInterval() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinterval%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInterval()))));
    }

    // add `continuous` to the URL query string
    if (getContinuous() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontinuous%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContinuous()))));
    }

    // add `instrumentType` to the URL query string
    if (getInstrumentType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinstrumentType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInstrumentType()))));
    }

    // add `forceRefresh` to the URL query string
    if (getForceRefresh() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sforceRefresh%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getForceRefresh()))));
    }

    // add `filterType` to the URL query string
    if (getFilterType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfilterType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFilterType()))));
    }

    // add `filterFrequency` to the URL query string
    if (getFilterFrequency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfilterFrequency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFilterFrequency()))));
    }

    // add `additionalParams` to the URL query string
    if (getAdditionalParams() != null) {
      for (String _key : getAdditionalParams().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sadditionalParams%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getAdditionalParams().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getAdditionalParams().get(_key)))));
      }
    }

    // add `isIndexSymbol` to the URL query string
    if (getIsIndexSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisIndexSymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsIndexSymbol()))));
    }

    return joiner.toString();
  }
}

