/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * IndexMetadata
 */
@JsonPropertyOrder({
  IndexMetadata.JSON_PROPERTY_INDEX_NAME,
  IndexMetadata.JSON_PROPERTY_OPEN,
  IndexMetadata.JSON_PROPERTY_HIGH,
  IndexMetadata.JSON_PROPERTY_LOW,
  IndexMetadata.JSON_PROPERTY_PREVIOUS_CLOSE,
  IndexMetadata.JSON_PROPERTY_LAST,
  IndexMetadata.JSON_PROPERTY_PERC_CHANGE,
  IndexMetadata.JSON_PROPERTY_CHANGE,
  IndexMetadata.JSON_PROPERTY_TIME_VAL,
  IndexMetadata.JSON_PROPERTY_YEAR_HIGH,
  IndexMetadata.JSON_PROPERTY_YEAR_LOW,
  IndexMetadata.JSON_PROPERTY_INDICATIVE_CLOSE,
  IndexMetadata.JSON_PROPERTY_TOTAL_TRADED_VOLUME,
  IndexMetadata.JSON_PROPERTY_TOTAL_TRADED_VALUE,
  IndexMetadata.JSON_PROPERTY_FFMC_SUM
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class IndexMetadata {
  public static final String JSON_PROPERTY_INDEX_NAME = "indexName";
  @javax.annotation.Nullable
  private String indexName;

  public static final String JSON_PROPERTY_OPEN = "open";
  @javax.annotation.Nullable
  private Double open;

  public static final String JSON_PROPERTY_HIGH = "high";
  @javax.annotation.Nullable
  private Double high;

  public static final String JSON_PROPERTY_LOW = "low";
  @javax.annotation.Nullable
  private Double low;

  public static final String JSON_PROPERTY_PREVIOUS_CLOSE = "previousClose";
  @javax.annotation.Nullable
  private Double previousClose;

  public static final String JSON_PROPERTY_LAST = "last";
  @javax.annotation.Nullable
  private Double last;

  public static final String JSON_PROPERTY_PERC_CHANGE = "percChange";
  @javax.annotation.Nullable
  private Double percChange;

  public static final String JSON_PROPERTY_CHANGE = "change";
  @javax.annotation.Nullable
  private Double change;

  public static final String JSON_PROPERTY_TIME_VAL = "timeVal";
  @javax.annotation.Nullable
  private String timeVal;

  public static final String JSON_PROPERTY_YEAR_HIGH = "yearHigh";
  @javax.annotation.Nullable
  private Double yearHigh;

  public static final String JSON_PROPERTY_YEAR_LOW = "yearLow";
  @javax.annotation.Nullable
  private Double yearLow;

  public static final String JSON_PROPERTY_INDICATIVE_CLOSE = "indicativeClose";
  @javax.annotation.Nullable
  private Double indicativeClose;

  public static final String JSON_PROPERTY_TOTAL_TRADED_VOLUME = "totalTradedVolume";
  @javax.annotation.Nullable
  private Long totalTradedVolume;

  public static final String JSON_PROPERTY_TOTAL_TRADED_VALUE = "totalTradedValue";
  @javax.annotation.Nullable
  private Double totalTradedValue;

  public static final String JSON_PROPERTY_FFMC_SUM = "ffmc_sum";
  @javax.annotation.Nullable
  private Double ffmcSum;

  public IndexMetadata() { 
  }

  public IndexMetadata indexName(@javax.annotation.Nullable String indexName) {
    this.indexName = indexName;
    return this;
  }

  /**
   * Get indexName
   * @return indexName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDEX_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIndexName() {
    return indexName;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndexName(@javax.annotation.Nullable String indexName) {
    this.indexName = indexName;
  }


  public IndexMetadata open(@javax.annotation.Nullable Double open) {
    this.open = open;
    return this;
  }

  /**
   * Get open
   * @return open
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getOpen() {
    return open;
  }


  @JsonProperty(value = JSON_PROPERTY_OPEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpen(@javax.annotation.Nullable Double open) {
    this.open = open;
  }


  public IndexMetadata high(@javax.annotation.Nullable Double high) {
    this.high = high;
    return this;
  }

  /**
   * Get high
   * @return high
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getHigh() {
    return high;
  }


  @JsonProperty(value = JSON_PROPERTY_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHigh(@javax.annotation.Nullable Double high) {
    this.high = high;
  }


  public IndexMetadata low(@javax.annotation.Nullable Double low) {
    this.low = low;
    return this;
  }

  /**
   * Get low
   * @return low
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLow() {
    return low;
  }


  @JsonProperty(value = JSON_PROPERTY_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLow(@javax.annotation.Nullable Double low) {
    this.low = low;
  }


  public IndexMetadata previousClose(@javax.annotation.Nullable Double previousClose) {
    this.previousClose = previousClose;
    return this;
  }

  /**
   * Get previousClose
   * @return previousClose
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREVIOUS_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPreviousClose() {
    return previousClose;
  }


  @JsonProperty(value = JSON_PROPERTY_PREVIOUS_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviousClose(@javax.annotation.Nullable Double previousClose) {
    this.previousClose = previousClose;
  }


  public IndexMetadata last(@javax.annotation.Nullable Double last) {
    this.last = last;
    return this;
  }

  /**
   * Get last
   * @return last
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLast() {
    return last;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLast(@javax.annotation.Nullable Double last) {
    this.last = last;
  }


  public IndexMetadata percChange(@javax.annotation.Nullable Double percChange) {
    this.percChange = percChange;
    return this;
  }

  /**
   * Get percChange
   * @return percChange
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERC_CHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPercChange() {
    return percChange;
  }


  @JsonProperty(value = JSON_PROPERTY_PERC_CHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPercChange(@javax.annotation.Nullable Double percChange) {
    this.percChange = percChange;
  }


  public IndexMetadata change(@javax.annotation.Nullable Double change) {
    this.change = change;
    return this;
  }

  /**
   * Get change
   * @return change
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getChange() {
    return change;
  }


  @JsonProperty(value = JSON_PROPERTY_CHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChange(@javax.annotation.Nullable Double change) {
    this.change = change;
  }


  public IndexMetadata timeVal(@javax.annotation.Nullable String timeVal) {
    this.timeVal = timeVal;
    return this;
  }

  /**
   * Get timeVal
   * @return timeVal
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME_VAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimeVal() {
    return timeVal;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME_VAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeVal(@javax.annotation.Nullable String timeVal) {
    this.timeVal = timeVal;
  }


  public IndexMetadata yearHigh(@javax.annotation.Nullable Double yearHigh) {
    this.yearHigh = yearHigh;
    return this;
  }

  /**
   * Get yearHigh
   * @return yearHigh
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_YEAR_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getYearHigh() {
    return yearHigh;
  }


  @JsonProperty(value = JSON_PROPERTY_YEAR_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setYearHigh(@javax.annotation.Nullable Double yearHigh) {
    this.yearHigh = yearHigh;
  }


  public IndexMetadata yearLow(@javax.annotation.Nullable Double yearLow) {
    this.yearLow = yearLow;
    return this;
  }

  /**
   * Get yearLow
   * @return yearLow
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_YEAR_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getYearLow() {
    return yearLow;
  }


  @JsonProperty(value = JSON_PROPERTY_YEAR_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setYearLow(@javax.annotation.Nullable Double yearLow) {
    this.yearLow = yearLow;
  }


  public IndexMetadata indicativeClose(@javax.annotation.Nullable Double indicativeClose) {
    this.indicativeClose = indicativeClose;
    return this;
  }

  /**
   * Get indicativeClose
   * @return indicativeClose
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDICATIVE_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getIndicativeClose() {
    return indicativeClose;
  }


  @JsonProperty(value = JSON_PROPERTY_INDICATIVE_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndicativeClose(@javax.annotation.Nullable Double indicativeClose) {
    this.indicativeClose = indicativeClose;
  }


  public IndexMetadata totalTradedVolume(@javax.annotation.Nullable Long totalTradedVolume) {
    this.totalTradedVolume = totalTradedVolume;
    return this;
  }

  /**
   * Get totalTradedVolume
   * @return totalTradedVolume
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_TRADED_VOLUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getTotalTradedVolume() {
    return totalTradedVolume;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_TRADED_VOLUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalTradedVolume(@javax.annotation.Nullable Long totalTradedVolume) {
    this.totalTradedVolume = totalTradedVolume;
  }


  public IndexMetadata totalTradedValue(@javax.annotation.Nullable Double totalTradedValue) {
    this.totalTradedValue = totalTradedValue;
    return this;
  }

  /**
   * Get totalTradedValue
   * @return totalTradedValue
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_TRADED_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTotalTradedValue() {
    return totalTradedValue;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_TRADED_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalTradedValue(@javax.annotation.Nullable Double totalTradedValue) {
    this.totalTradedValue = totalTradedValue;
  }


  public IndexMetadata ffmcSum(@javax.annotation.Nullable Double ffmcSum) {
    this.ffmcSum = ffmcSum;
    return this;
  }

  /**
   * Get ffmcSum
   * @return ffmcSum
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FFMC_SUM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getFfmcSum() {
    return ffmcSum;
  }


  @JsonProperty(value = JSON_PROPERTY_FFMC_SUM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFfmcSum(@javax.annotation.Nullable Double ffmcSum) {
    this.ffmcSum = ffmcSum;
  }


  /**
   * Return true if this IndexMetadata object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndexMetadata indexMetadata = (IndexMetadata) o;
    return Objects.equals(this.indexName, indexMetadata.indexName) &&
        Objects.equals(this.open, indexMetadata.open) &&
        Objects.equals(this.high, indexMetadata.high) &&
        Objects.equals(this.low, indexMetadata.low) &&
        Objects.equals(this.previousClose, indexMetadata.previousClose) &&
        Objects.equals(this.last, indexMetadata.last) &&
        Objects.equals(this.percChange, indexMetadata.percChange) &&
        Objects.equals(this.change, indexMetadata.change) &&
        Objects.equals(this.timeVal, indexMetadata.timeVal) &&
        Objects.equals(this.yearHigh, indexMetadata.yearHigh) &&
        Objects.equals(this.yearLow, indexMetadata.yearLow) &&
        Objects.equals(this.indicativeClose, indexMetadata.indicativeClose) &&
        Objects.equals(this.totalTradedVolume, indexMetadata.totalTradedVolume) &&
        Objects.equals(this.totalTradedValue, indexMetadata.totalTradedValue) &&
        Objects.equals(this.ffmcSum, indexMetadata.ffmcSum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(indexName, open, high, low, previousClose, last, percChange, change, timeVal, yearHigh, yearLow, indicativeClose, totalTradedVolume, totalTradedValue, ffmcSum);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndexMetadata {\n");
    sb.append("    indexName: ").append(toIndentedString(indexName)).append("\n");
    sb.append("    open: ").append(toIndentedString(open)).append("\n");
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("    previousClose: ").append(toIndentedString(previousClose)).append("\n");
    sb.append("    last: ").append(toIndentedString(last)).append("\n");
    sb.append("    percChange: ").append(toIndentedString(percChange)).append("\n");
    sb.append("    change: ").append(toIndentedString(change)).append("\n");
    sb.append("    timeVal: ").append(toIndentedString(timeVal)).append("\n");
    sb.append("    yearHigh: ").append(toIndentedString(yearHigh)).append("\n");
    sb.append("    yearLow: ").append(toIndentedString(yearLow)).append("\n");
    sb.append("    indicativeClose: ").append(toIndentedString(indicativeClose)).append("\n");
    sb.append("    totalTradedVolume: ").append(toIndentedString(totalTradedVolume)).append("\n");
    sb.append("    totalTradedValue: ").append(toIndentedString(totalTradedValue)).append("\n");
    sb.append("    ffmcSum: ").append(toIndentedString(ffmcSum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `indexName` to the URL query string
    if (getIndexName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindexName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndexName()))));
    }

    // add `open` to the URL query string
    if (getOpen() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sopen%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOpen()))));
    }

    // add `high` to the URL query string
    if (getHigh() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shigh%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHigh()))));
    }

    // add `low` to the URL query string
    if (getLow() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slow%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLow()))));
    }

    // add `previousClose` to the URL query string
    if (getPreviousClose() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spreviousClose%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPreviousClose()))));
    }

    // add `last` to the URL query string
    if (getLast() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slast%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLast()))));
    }

    // add `percChange` to the URL query string
    if (getPercChange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spercChange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPercChange()))));
    }

    // add `change` to the URL query string
    if (getChange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChange()))));
    }

    // add `timeVal` to the URL query string
    if (getTimeVal() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimeVal%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimeVal()))));
    }

    // add `yearHigh` to the URL query string
    if (getYearHigh() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%syearHigh%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getYearHigh()))));
    }

    // add `yearLow` to the URL query string
    if (getYearLow() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%syearLow%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getYearLow()))));
    }

    // add `indicativeClose` to the URL query string
    if (getIndicativeClose() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindicativeClose%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndicativeClose()))));
    }

    // add `totalTradedVolume` to the URL query string
    if (getTotalTradedVolume() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalTradedVolume%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalTradedVolume()))));
    }

    // add `totalTradedValue` to the URL query string
    if (getTotalTradedValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalTradedValue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalTradedValue()))));
    }

    // add `ffmc_sum` to the URL query string
    if (getFfmcSum() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sffmc_sum%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFfmcSum()))));
    }

    return joiner.toString();
  }
}

