/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.marketdata.model.PositionMargin;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * MarginCalculationResponse
 */
@JsonPropertyOrder({
  MarginCalculationResponse.JSON_PROPERTY_TOTAL_MARGIN_REQUIRED,
  MarginCalculationResponse.JSON_PROPERTY_SPAN_MARGIN,
  MarginCalculationResponse.JSON_PROPERTY_EXPOSURE_MARGIN,
  MarginCalculationResponse.JSON_PROPERTY_ADDITIONAL_MARGIN,
  MarginCalculationResponse.JSON_PROPERTY_POSITION_MARGINS,
  MarginCalculationResponse.JSON_PROPERTY_STATUS,
  MarginCalculationResponse.JSON_PROPERTY_ERROR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class MarginCalculationResponse {
  public static final String JSON_PROPERTY_TOTAL_MARGIN_REQUIRED = "totalMarginRequired";
  @javax.annotation.Nullable
  private BigDecimal totalMarginRequired;

  public static final String JSON_PROPERTY_SPAN_MARGIN = "spanMargin";
  @javax.annotation.Nullable
  private BigDecimal spanMargin;

  public static final String JSON_PROPERTY_EXPOSURE_MARGIN = "exposureMargin";
  @javax.annotation.Nullable
  private BigDecimal exposureMargin;

  public static final String JSON_PROPERTY_ADDITIONAL_MARGIN = "additionalMargin";
  @javax.annotation.Nullable
  private BigDecimal additionalMargin;

  public static final String JSON_PROPERTY_POSITION_MARGINS = "positionMargins";
  @javax.annotation.Nullable
  private Map<String, PositionMargin> positionMargins = new HashMap<>();

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_ERROR = "error";
  @javax.annotation.Nullable
  private String error;

  public MarginCalculationResponse() { 
  }

  public MarginCalculationResponse totalMarginRequired(@javax.annotation.Nullable BigDecimal totalMarginRequired) {
    this.totalMarginRequired = totalMarginRequired;
    return this;
  }

  /**
   * Get totalMarginRequired
   * @return totalMarginRequired
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_MARGIN_REQUIRED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getTotalMarginRequired() {
    return totalMarginRequired;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_MARGIN_REQUIRED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalMarginRequired(@javax.annotation.Nullable BigDecimal totalMarginRequired) {
    this.totalMarginRequired = totalMarginRequired;
  }


  public MarginCalculationResponse spanMargin(@javax.annotation.Nullable BigDecimal spanMargin) {
    this.spanMargin = spanMargin;
    return this;
  }

  /**
   * Get spanMargin
   * @return spanMargin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPAN_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getSpanMargin() {
    return spanMargin;
  }


  @JsonProperty(value = JSON_PROPERTY_SPAN_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpanMargin(@javax.annotation.Nullable BigDecimal spanMargin) {
    this.spanMargin = spanMargin;
  }


  public MarginCalculationResponse exposureMargin(@javax.annotation.Nullable BigDecimal exposureMargin) {
    this.exposureMargin = exposureMargin;
    return this;
  }

  /**
   * Get exposureMargin
   * @return exposureMargin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPOSURE_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getExposureMargin() {
    return exposureMargin;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPOSURE_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExposureMargin(@javax.annotation.Nullable BigDecimal exposureMargin) {
    this.exposureMargin = exposureMargin;
  }


  public MarginCalculationResponse additionalMargin(@javax.annotation.Nullable BigDecimal additionalMargin) {
    this.additionalMargin = additionalMargin;
    return this;
  }

  /**
   * Get additionalMargin
   * @return additionalMargin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getAdditionalMargin() {
    return additionalMargin;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalMargin(@javax.annotation.Nullable BigDecimal additionalMargin) {
    this.additionalMargin = additionalMargin;
  }


  public MarginCalculationResponse positionMargins(@javax.annotation.Nullable Map<String, PositionMargin> positionMargins) {
    this.positionMargins = positionMargins;
    return this;
  }

  public MarginCalculationResponse putPositionMarginsItem(String key, PositionMargin positionMarginsItem) {
    if (this.positionMargins == null) {
      this.positionMargins = new HashMap<>();
    }
    this.positionMargins.put(key, positionMarginsItem);
    return this;
  }

  /**
   * Get positionMargins
   * @return positionMargins
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POSITION_MARGINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, PositionMargin> getPositionMargins() {
    return positionMargins;
  }


  @JsonProperty(value = JSON_PROPERTY_POSITION_MARGINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPositionMargins(@javax.annotation.Nullable Map<String, PositionMargin> positionMargins) {
    this.positionMargins = positionMargins;
  }


  public MarginCalculationResponse status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public MarginCalculationResponse error(@javax.annotation.Nullable String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getError() {
    return error;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(@javax.annotation.Nullable String error) {
    this.error = error;
  }


  /**
   * Return true if this MarginCalculationResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarginCalculationResponse marginCalculationResponse = (MarginCalculationResponse) o;
    return Objects.equals(this.totalMarginRequired, marginCalculationResponse.totalMarginRequired) &&
        Objects.equals(this.spanMargin, marginCalculationResponse.spanMargin) &&
        Objects.equals(this.exposureMargin, marginCalculationResponse.exposureMargin) &&
        Objects.equals(this.additionalMargin, marginCalculationResponse.additionalMargin) &&
        Objects.equals(this.positionMargins, marginCalculationResponse.positionMargins) &&
        Objects.equals(this.status, marginCalculationResponse.status) &&
        Objects.equals(this.error, marginCalculationResponse.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalMarginRequired, spanMargin, exposureMargin, additionalMargin, positionMargins, status, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarginCalculationResponse {\n");
    sb.append("    totalMarginRequired: ").append(toIndentedString(totalMarginRequired)).append("\n");
    sb.append("    spanMargin: ").append(toIndentedString(spanMargin)).append("\n");
    sb.append("    exposureMargin: ").append(toIndentedString(exposureMargin)).append("\n");
    sb.append("    additionalMargin: ").append(toIndentedString(additionalMargin)).append("\n");
    sb.append("    positionMargins: ").append(toIndentedString(positionMargins)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `totalMarginRequired` to the URL query string
    if (getTotalMarginRequired() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalMarginRequired%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalMarginRequired()))));
    }

    // add `spanMargin` to the URL query string
    if (getSpanMargin() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sspanMargin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSpanMargin()))));
    }

    // add `exposureMargin` to the URL query string
    if (getExposureMargin() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexposureMargin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExposureMargin()))));
    }

    // add `additionalMargin` to the URL query string
    if (getAdditionalMargin() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sadditionalMargin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAdditionalMargin()))));
    }

    // add `positionMargins` to the URL query string
    if (getPositionMargins() != null) {
      for (String _key : getPositionMargins().keySet()) {
        if (getPositionMargins().get(_key) != null) {
          joiner.add(getPositionMargins().get(_key).toUrlQueryString(String.format(java.util.Locale.ROOT, "%spositionMargins%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serror%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getError()))));
    }

    return joiner.toString();
  }
}

