/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.marketdata.model.Position;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * MarginCalculationRequest
 */
@JsonPropertyOrder({
  MarginCalculationRequest.JSON_PROPERTY_POSITIONS,
  MarginCalculationRequest.JSON_PROPERTY_ORDER_TYPE,
  MarginCalculationRequest.JSON_PROPERTY_EXCHANGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class MarginCalculationRequest {
  public static final String JSON_PROPERTY_POSITIONS = "positions";
  @javax.annotation.Nullable
  private List<Position> positions = new ArrayList<>();

  public static final String JSON_PROPERTY_ORDER_TYPE = "orderType";
  @javax.annotation.Nullable
  private String orderType;

  public static final String JSON_PROPERTY_EXCHANGE = "exchange";
  @javax.annotation.Nullable
  private String exchange;

  public MarginCalculationRequest() { 
  }

  public MarginCalculationRequest positions(@javax.annotation.Nullable List<Position> positions) {
    this.positions = positions;
    return this;
  }

  public MarginCalculationRequest addPositionsItem(Position positionsItem) {
    if (this.positions == null) {
      this.positions = new ArrayList<>();
    }
    this.positions.add(positionsItem);
    return this;
  }

  /**
   * Get positions
   * @return positions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POSITIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Position> getPositions() {
    return positions;
  }


  @JsonProperty(value = JSON_PROPERTY_POSITIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPositions(@javax.annotation.Nullable List<Position> positions) {
    this.positions = positions;
  }


  public MarginCalculationRequest orderType(@javax.annotation.Nullable String orderType) {
    this.orderType = orderType;
    return this;
  }

  /**
   * Get orderType
   * @return orderType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORDER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOrderType() {
    return orderType;
  }


  @JsonProperty(value = JSON_PROPERTY_ORDER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderType(@javax.annotation.Nullable String orderType) {
    this.orderType = orderType;
  }


  public MarginCalculationRequest exchange(@javax.annotation.Nullable String exchange) {
    this.exchange = exchange;
    return this;
  }

  /**
   * Get exchange
   * @return exchange
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getExchange() {
    return exchange;
  }


  @JsonProperty(value = JSON_PROPERTY_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchange(@javax.annotation.Nullable String exchange) {
    this.exchange = exchange;
  }


  /**
   * Return true if this MarginCalculationRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarginCalculationRequest marginCalculationRequest = (MarginCalculationRequest) o;
    return Objects.equals(this.positions, marginCalculationRequest.positions) &&
        Objects.equals(this.orderType, marginCalculationRequest.orderType) &&
        Objects.equals(this.exchange, marginCalculationRequest.exchange);
  }

  @Override
  public int hashCode() {
    return Objects.hash(positions, orderType, exchange);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarginCalculationRequest {\n");
    sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `positions` to the URL query string
    if (getPositions() != null) {
      for (int i = 0; i < getPositions().size(); i++) {
        if (getPositions().get(i) != null) {
          joiner.add(getPositions().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%spositions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `orderType` to the URL query string
    if (getOrderType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sorderType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOrderType()))));
    }

    // add `exchange` to the URL query string
    if (getExchange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexchange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExchange()))));
    }

    return joiner.toString();
  }
}

