/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * MarketDataUpdateV1
 */
@JsonPropertyOrder({
  MarketDataUpdateV1.JSON_PROPERTY_INSTRUMENT_KEY,
  MarketDataUpdateV1.JSON_PROPERTY_LAST_PRICE,
  MarketDataUpdateV1.JSON_PROPERTY_CHANGE,
  MarketDataUpdateV1.JSON_PROPERTY_OPEN,
  MarketDataUpdateV1.JSON_PROPERTY_HIGH,
  MarketDataUpdateV1.JSON_PROPERTY_LOW,
  MarketDataUpdateV1.JSON_PROPERTY_PREVIOUS_CLOSE,
  MarketDataUpdateV1.JSON_PROPERTY_VOLUME,
  MarketDataUpdateV1.JSON_PROPERTY_TIMESTAMP,
  MarketDataUpdateV1.JSON_PROPERTY_P_CHANGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class MarketDataUpdateV1 {
  public static final String JSON_PROPERTY_INSTRUMENT_KEY = "instrumentKey";
  @javax.annotation.Nullable
  private String instrumentKey;

  public static final String JSON_PROPERTY_LAST_PRICE = "lastPrice";
  @javax.annotation.Nullable
  private Double lastPrice;

  public static final String JSON_PROPERTY_CHANGE = "change";
  @javax.annotation.Nullable
  private Double change;

  public static final String JSON_PROPERTY_OPEN = "open";
  @javax.annotation.Nullable
  private Double open;

  public static final String JSON_PROPERTY_HIGH = "high";
  @javax.annotation.Nullable
  private Double high;

  public static final String JSON_PROPERTY_LOW = "low";
  @javax.annotation.Nullable
  private Double low;

  public static final String JSON_PROPERTY_PREVIOUS_CLOSE = "previousClose";
  @javax.annotation.Nullable
  private Double previousClose;

  public static final String JSON_PROPERTY_VOLUME = "volume";
  @javax.annotation.Nullable
  private Long volume;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private String timestamp;

  public static final String JSON_PROPERTY_P_CHANGE = "pChange";
  @javax.annotation.Nullable
  private Double pChange;

  public MarketDataUpdateV1() { 
  }

  public MarketDataUpdateV1 instrumentKey(@javax.annotation.Nullable String instrumentKey) {
    this.instrumentKey = instrumentKey;
    return this;
  }

  /**
   * Get instrumentKey
   * @return instrumentKey
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INSTRUMENT_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getInstrumentKey() {
    return instrumentKey;
  }


  @JsonProperty(value = JSON_PROPERTY_INSTRUMENT_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstrumentKey(@javax.annotation.Nullable String instrumentKey) {
    this.instrumentKey = instrumentKey;
  }


  public MarketDataUpdateV1 lastPrice(@javax.annotation.Nullable Double lastPrice) {
    this.lastPrice = lastPrice;
    return this;
  }

  /**
   * Get lastPrice
   * @return lastPrice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLastPrice() {
    return lastPrice;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastPrice(@javax.annotation.Nullable Double lastPrice) {
    this.lastPrice = lastPrice;
  }


  public MarketDataUpdateV1 change(@javax.annotation.Nullable Double change) {
    this.change = change;
    return this;
  }

  /**
   * Get change
   * @return change
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getChange() {
    return change;
  }


  @JsonProperty(value = JSON_PROPERTY_CHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChange(@javax.annotation.Nullable Double change) {
    this.change = change;
  }


  public MarketDataUpdateV1 open(@javax.annotation.Nullable Double open) {
    this.open = open;
    return this;
  }

  /**
   * Get open
   * @return open
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getOpen() {
    return open;
  }


  @JsonProperty(value = JSON_PROPERTY_OPEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpen(@javax.annotation.Nullable Double open) {
    this.open = open;
  }


  public MarketDataUpdateV1 high(@javax.annotation.Nullable Double high) {
    this.high = high;
    return this;
  }

  /**
   * Get high
   * @return high
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getHigh() {
    return high;
  }


  @JsonProperty(value = JSON_PROPERTY_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHigh(@javax.annotation.Nullable Double high) {
    this.high = high;
  }


  public MarketDataUpdateV1 low(@javax.annotation.Nullable Double low) {
    this.low = low;
    return this;
  }

  /**
   * Get low
   * @return low
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLow() {
    return low;
  }


  @JsonProperty(value = JSON_PROPERTY_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLow(@javax.annotation.Nullable Double low) {
    this.low = low;
  }


  public MarketDataUpdateV1 previousClose(@javax.annotation.Nullable Double previousClose) {
    this.previousClose = previousClose;
    return this;
  }

  /**
   * Get previousClose
   * @return previousClose
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREVIOUS_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPreviousClose() {
    return previousClose;
  }


  @JsonProperty(value = JSON_PROPERTY_PREVIOUS_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviousClose(@javax.annotation.Nullable Double previousClose) {
    this.previousClose = previousClose;
  }


  public MarketDataUpdateV1 volume(@javax.annotation.Nullable Long volume) {
    this.volume = volume;
    return this;
  }

  /**
   * Get volume
   * @return volume
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VOLUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getVolume() {
    return volume;
  }


  @JsonProperty(value = JSON_PROPERTY_VOLUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolume(@javax.annotation.Nullable Long volume) {
    this.volume = volume;
  }


  public MarketDataUpdateV1 timestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
  }


  public MarketDataUpdateV1 pChange(@javax.annotation.Nullable Double pChange) {
    this.pChange = pChange;
    return this;
  }

  /**
   * Get pChange
   * @return pChange
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_P_CHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getpChange() {
    return pChange;
  }


  @JsonProperty(value = JSON_PROPERTY_P_CHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setpChange(@javax.annotation.Nullable Double pChange) {
    this.pChange = pChange;
  }


  /**
   * Return true if this MarketDataUpdateV1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketDataUpdateV1 marketDataUpdateV1 = (MarketDataUpdateV1) o;
    return Objects.equals(this.instrumentKey, marketDataUpdateV1.instrumentKey) &&
        Objects.equals(this.lastPrice, marketDataUpdateV1.lastPrice) &&
        Objects.equals(this.change, marketDataUpdateV1.change) &&
        Objects.equals(this.open, marketDataUpdateV1.open) &&
        Objects.equals(this.high, marketDataUpdateV1.high) &&
        Objects.equals(this.low, marketDataUpdateV1.low) &&
        Objects.equals(this.previousClose, marketDataUpdateV1.previousClose) &&
        Objects.equals(this.volume, marketDataUpdateV1.volume) &&
        Objects.equals(this.timestamp, marketDataUpdateV1.timestamp) &&
        Objects.equals(this.pChange, marketDataUpdateV1.pChange);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instrumentKey, lastPrice, change, open, high, low, previousClose, volume, timestamp, pChange);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketDataUpdateV1 {\n");
    sb.append("    instrumentKey: ").append(toIndentedString(instrumentKey)).append("\n");
    sb.append("    lastPrice: ").append(toIndentedString(lastPrice)).append("\n");
    sb.append("    change: ").append(toIndentedString(change)).append("\n");
    sb.append("    open: ").append(toIndentedString(open)).append("\n");
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("    previousClose: ").append(toIndentedString(previousClose)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    pChange: ").append(toIndentedString(pChange)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `instrumentKey` to the URL query string
    if (getInstrumentKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinstrumentKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInstrumentKey()))));
    }

    // add `lastPrice` to the URL query string
    if (getLastPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slastPrice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastPrice()))));
    }

    // add `change` to the URL query string
    if (getChange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChange()))));
    }

    // add `open` to the URL query string
    if (getOpen() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sopen%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOpen()))));
    }

    // add `high` to the URL query string
    if (getHigh() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shigh%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHigh()))));
    }

    // add `low` to the URL query string
    if (getLow() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slow%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLow()))));
    }

    // add `previousClose` to the URL query string
    if (getPreviousClose() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spreviousClose%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPreviousClose()))));
    }

    // add `volume` to the URL query string
    if (getVolume() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svolume%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVolume()))));
    }

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    // add `pChange` to the URL query string
    if (getpChange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spChange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getpChange()))));
    }

    return joiner.toString();
  }
}

