/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * MarketStatus
 */
@JsonPropertyOrder({
  MarketStatus.JSON_PROPERTY_MARKET,
  MarketStatus.JSON_PROPERTY_MARKET_STATUS,
  MarketStatus.JSON_PROPERTY_TRADE_DATE,
  MarketStatus.JSON_PROPERTY_INDEX,
  MarketStatus.JSON_PROPERTY_LAST,
  MarketStatus.JSON_PROPERTY_VARIATION,
  MarketStatus.JSON_PROPERTY_PERCENT_CHANGE,
  MarketStatus.JSON_PROPERTY_MARKET_STATUS_MESSAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class MarketStatus {
  public static final String JSON_PROPERTY_MARKET = "market";
  @javax.annotation.Nullable
  private String market;

  public static final String JSON_PROPERTY_MARKET_STATUS = "marketStatus";
  @javax.annotation.Nullable
  private String marketStatus;

  public static final String JSON_PROPERTY_TRADE_DATE = "tradeDate";
  @javax.annotation.Nullable
  private String tradeDate;

  public static final String JSON_PROPERTY_INDEX = "index";
  @javax.annotation.Nullable
  private String index;

  public static final String JSON_PROPERTY_LAST = "last";
  @javax.annotation.Nullable
  private Double last;

  public static final String JSON_PROPERTY_VARIATION = "variation";
  @javax.annotation.Nullable
  private Double variation;

  public static final String JSON_PROPERTY_PERCENT_CHANGE = "percentChange";
  @javax.annotation.Nullable
  private Double percentChange;

  public static final String JSON_PROPERTY_MARKET_STATUS_MESSAGE = "marketStatusMessage";
  @javax.annotation.Nullable
  private String marketStatusMessage;

  public MarketStatus() { 
  }

  public MarketStatus market(@javax.annotation.Nullable String market) {
    this.market = market;
    return this;
  }

  /**
   * Get market
   * @return market
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMarket() {
    return market;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarket(@javax.annotation.Nullable String market) {
    this.market = market;
  }


  public MarketStatus marketStatus(@javax.annotation.Nullable String marketStatus) {
    this.marketStatus = marketStatus;
    return this;
  }

  /**
   * Get marketStatus
   * @return marketStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMarketStatus() {
    return marketStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketStatus(@javax.annotation.Nullable String marketStatus) {
    this.marketStatus = marketStatus;
  }


  public MarketStatus tradeDate(@javax.annotation.Nullable String tradeDate) {
    this.tradeDate = tradeDate;
    return this;
  }

  /**
   * Get tradeDate
   * @return tradeDate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRADE_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTradeDate() {
    return tradeDate;
  }


  @JsonProperty(value = JSON_PROPERTY_TRADE_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTradeDate(@javax.annotation.Nullable String tradeDate) {
    this.tradeDate = tradeDate;
  }


  public MarketStatus index(@javax.annotation.Nullable String index) {
    this.index = index;
    return this;
  }

  /**
   * Get index
   * @return index
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIndex() {
    return index;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndex(@javax.annotation.Nullable String index) {
    this.index = index;
  }


  public MarketStatus last(@javax.annotation.Nullable Double last) {
    this.last = last;
    return this;
  }

  /**
   * Get last
   * @return last
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLast() {
    return last;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLast(@javax.annotation.Nullable Double last) {
    this.last = last;
  }


  public MarketStatus variation(@javax.annotation.Nullable Double variation) {
    this.variation = variation;
    return this;
  }

  /**
   * Get variation
   * @return variation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VARIATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getVariation() {
    return variation;
  }


  @JsonProperty(value = JSON_PROPERTY_VARIATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariation(@javax.annotation.Nullable Double variation) {
    this.variation = variation;
  }


  public MarketStatus percentChange(@javax.annotation.Nullable Double percentChange) {
    this.percentChange = percentChange;
    return this;
  }

  /**
   * Get percentChange
   * @return percentChange
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERCENT_CHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPercentChange() {
    return percentChange;
  }


  @JsonProperty(value = JSON_PROPERTY_PERCENT_CHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPercentChange(@javax.annotation.Nullable Double percentChange) {
    this.percentChange = percentChange;
  }


  public MarketStatus marketStatusMessage(@javax.annotation.Nullable String marketStatusMessage) {
    this.marketStatusMessage = marketStatusMessage;
    return this;
  }

  /**
   * Get marketStatusMessage
   * @return marketStatusMessage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_STATUS_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMarketStatusMessage() {
    return marketStatusMessage;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_STATUS_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketStatusMessage(@javax.annotation.Nullable String marketStatusMessage) {
    this.marketStatusMessage = marketStatusMessage;
  }


  /**
   * Return true if this MarketStatus object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketStatus marketStatus = (MarketStatus) o;
    return Objects.equals(this.market, marketStatus.market) &&
        Objects.equals(this.marketStatus, marketStatus.marketStatus) &&
        Objects.equals(this.tradeDate, marketStatus.tradeDate) &&
        Objects.equals(this.index, marketStatus.index) &&
        Objects.equals(this.last, marketStatus.last) &&
        Objects.equals(this.variation, marketStatus.variation) &&
        Objects.equals(this.percentChange, marketStatus.percentChange) &&
        Objects.equals(this.marketStatusMessage, marketStatus.marketStatusMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(market, marketStatus, tradeDate, index, last, variation, percentChange, marketStatusMessage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketStatus {\n");
    sb.append("    market: ").append(toIndentedString(market)).append("\n");
    sb.append("    marketStatus: ").append(toIndentedString(marketStatus)).append("\n");
    sb.append("    tradeDate: ").append(toIndentedString(tradeDate)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    last: ").append(toIndentedString(last)).append("\n");
    sb.append("    variation: ").append(toIndentedString(variation)).append("\n");
    sb.append("    percentChange: ").append(toIndentedString(percentChange)).append("\n");
    sb.append("    marketStatusMessage: ").append(toIndentedString(marketStatusMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `market` to the URL query string
    if (getMarket() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smarket%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMarket()))));
    }

    // add `marketStatus` to the URL query string
    if (getMarketStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smarketStatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMarketStatus()))));
    }

    // add `tradeDate` to the URL query string
    if (getTradeDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stradeDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTradeDate()))));
    }

    // add `index` to the URL query string
    if (getIndex() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindex%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndex()))));
    }

    // add `last` to the URL query string
    if (getLast() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slast%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLast()))));
    }

    // add `variation` to the URL query string
    if (getVariation() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svariation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVariation()))));
    }

    // add `percentChange` to the URL query string
    if (getPercentChange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spercentChange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPercentChange()))));
    }

    // add `marketStatusMessage` to the URL query string
    if (getMarketStatusMessage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smarketStatusMessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMarketStatusMessage()))));
    }

    return joiner.toString();
  }
}

