/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * Metadata
 */
@JsonPropertyOrder({
  Metadata.JSON_PROPERTY_SYMBOL,
  Metadata.JSON_PROPERTY_COMPANY_NAME,
  Metadata.JSON_PROPERTY_INDUSTRY,
  Metadata.JSON_PROPERTY_ACTIVE_SERIES,
  Metadata.JSON_PROPERTY_ISIN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class Metadata {
  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  @javax.annotation.Nullable
  private String symbol;

  public static final String JSON_PROPERTY_COMPANY_NAME = "companyName";
  @javax.annotation.Nullable
  private String companyName;

  public static final String JSON_PROPERTY_INDUSTRY = "industry";
  @javax.annotation.Nullable
  private String industry;

  public static final String JSON_PROPERTY_ACTIVE_SERIES = "activeSeries";
  @javax.annotation.Nullable
  private List<String> activeSeries = new ArrayList<>();

  public static final String JSON_PROPERTY_ISIN = "isin";
  @javax.annotation.Nullable
  private String isin;

  public Metadata() { 
  }

  public Metadata symbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
    return this;
  }

  /**
   * Get symbol
   * @return symbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(value = JSON_PROPERTY_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
  }


  public Metadata companyName(@javax.annotation.Nullable String companyName) {
    this.companyName = companyName;
    return this;
  }

  /**
   * Get companyName
   * @return companyName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPANY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCompanyName() {
    return companyName;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPANY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompanyName(@javax.annotation.Nullable String companyName) {
    this.companyName = companyName;
  }


  public Metadata industry(@javax.annotation.Nullable String industry) {
    this.industry = industry;
    return this;
  }

  /**
   * Get industry
   * @return industry
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDUSTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIndustry() {
    return industry;
  }


  @JsonProperty(value = JSON_PROPERTY_INDUSTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndustry(@javax.annotation.Nullable String industry) {
    this.industry = industry;
  }


  public Metadata activeSeries(@javax.annotation.Nullable List<String> activeSeries) {
    this.activeSeries = activeSeries;
    return this;
  }

  public Metadata addActiveSeriesItem(String activeSeriesItem) {
    if (this.activeSeries == null) {
      this.activeSeries = new ArrayList<>();
    }
    this.activeSeries.add(activeSeriesItem);
    return this;
  }

  /**
   * Get activeSeries
   * @return activeSeries
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIVE_SERIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getActiveSeries() {
    return activeSeries;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIVE_SERIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActiveSeries(@javax.annotation.Nullable List<String> activeSeries) {
    this.activeSeries = activeSeries;
  }


  public Metadata isin(@javax.annotation.Nullable String isin) {
    this.isin = isin;
    return this;
  }

  /**
   * Get isin
   * @return isin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ISIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIsin() {
    return isin;
  }


  @JsonProperty(value = JSON_PROPERTY_ISIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsin(@javax.annotation.Nullable String isin) {
    this.isin = isin;
  }


  /**
   * Return true if this Metadata object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Metadata metadata = (Metadata) o;
    return Objects.equals(this.symbol, metadata.symbol) &&
        Objects.equals(this.companyName, metadata.companyName) &&
        Objects.equals(this.industry, metadata.industry) &&
        Objects.equals(this.activeSeries, metadata.activeSeries) &&
        Objects.equals(this.isin, metadata.isin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, companyName, industry, activeSeries, isin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Metadata {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    activeSeries: ").append(toIndentedString(activeSeries)).append("\n");
    sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `symbol` to the URL query string
    if (getSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSymbol()))));
    }

    // add `companyName` to the URL query string
    if (getCompanyName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scompanyName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCompanyName()))));
    }

    // add `industry` to the URL query string
    if (getIndustry() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindustry%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndustry()))));
    }

    // add `activeSeries` to the URL query string
    if (getActiveSeries() != null) {
      for (int i = 0; i < getActiveSeries().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sactiveSeries%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getActiveSeries().get(i)))));
      }
    }

    // add `isin` to the URL query string
    if (getIsin() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsin()))));
    }

    return joiner.toString();
  }
}

