/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.marketdata.model.Advance;
import com.am.marketdata.model.IndexMetadata;
import com.am.marketdata.model.MarketStatus;
import com.am.marketdata.model.StockData;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * NSEStockIndicesDataV1
 */
@JsonPropertyOrder({
  NSEStockIndicesDataV1.JSON_PROPERTY_NAME,
  NSEStockIndicesDataV1.JSON_PROPERTY_ADVANCE,
  NSEStockIndicesDataV1.JSON_PROPERTY_TIMESTAMP,
  NSEStockIndicesDataV1.JSON_PROPERTY_DATA,
  NSEStockIndicesDataV1.JSON_PROPERTY_METADATA,
  NSEStockIndicesDataV1.JSON_PROPERTY_MARKET_STATUS,
  NSEStockIndicesDataV1.JSON_PROPERTY_DATE30D_AGO,
  NSEStockIndicesDataV1.JSON_PROPERTY_DATE365D_AGO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class NSEStockIndicesDataV1 {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ADVANCE = "advance";
  @javax.annotation.Nullable
  private Advance advance;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private String timestamp;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private List<StockData> data = new ArrayList<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private IndexMetadata metadata;

  public static final String JSON_PROPERTY_MARKET_STATUS = "marketStatus";
  @javax.annotation.Nullable
  private MarketStatus marketStatus;

  public static final String JSON_PROPERTY_DATE30D_AGO = "date30dAgo";
  @javax.annotation.Nullable
  private String date30dAgo;

  public static final String JSON_PROPERTY_DATE365D_AGO = "date365dAgo";
  @javax.annotation.Nullable
  private String date365dAgo;

  public NSEStockIndicesDataV1() { 
  }

  public NSEStockIndicesDataV1 name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public NSEStockIndicesDataV1 advance(@javax.annotation.Nullable Advance advance) {
    this.advance = advance;
    return this;
  }

  /**
   * Get advance
   * @return advance
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADVANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Advance getAdvance() {
    return advance;
  }


  @JsonProperty(value = JSON_PROPERTY_ADVANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdvance(@javax.annotation.Nullable Advance advance) {
    this.advance = advance;
  }


  public NSEStockIndicesDataV1 timestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
  }


  public NSEStockIndicesDataV1 data(@javax.annotation.Nullable List<StockData> data) {
    this.data = data;
    return this;
  }

  public NSEStockIndicesDataV1 addDataItem(StockData dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<StockData> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable List<StockData> data) {
    this.data = data;
  }


  public NSEStockIndicesDataV1 metadata(@javax.annotation.Nullable IndexMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public IndexMetadata getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable IndexMetadata metadata) {
    this.metadata = metadata;
  }


  public NSEStockIndicesDataV1 marketStatus(@javax.annotation.Nullable MarketStatus marketStatus) {
    this.marketStatus = marketStatus;
    return this;
  }

  /**
   * Get marketStatus
   * @return marketStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MarketStatus getMarketStatus() {
    return marketStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketStatus(@javax.annotation.Nullable MarketStatus marketStatus) {
    this.marketStatus = marketStatus;
  }


  public NSEStockIndicesDataV1 date30dAgo(@javax.annotation.Nullable String date30dAgo) {
    this.date30dAgo = date30dAgo;
    return this;
  }

  /**
   * Get date30dAgo
   * @return date30dAgo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATE30D_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDate30dAgo() {
    return date30dAgo;
  }


  @JsonProperty(value = JSON_PROPERTY_DATE30D_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDate30dAgo(@javax.annotation.Nullable String date30dAgo) {
    this.date30dAgo = date30dAgo;
  }


  public NSEStockIndicesDataV1 date365dAgo(@javax.annotation.Nullable String date365dAgo) {
    this.date365dAgo = date365dAgo;
    return this;
  }

  /**
   * Get date365dAgo
   * @return date365dAgo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATE365D_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDate365dAgo() {
    return date365dAgo;
  }


  @JsonProperty(value = JSON_PROPERTY_DATE365D_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDate365dAgo(@javax.annotation.Nullable String date365dAgo) {
    this.date365dAgo = date365dAgo;
  }


  /**
   * Return true if this NSEStockIndicesDataV1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NSEStockIndicesDataV1 nsEStockIndicesDataV1 = (NSEStockIndicesDataV1) o;
    return Objects.equals(this.name, nsEStockIndicesDataV1.name) &&
        Objects.equals(this.advance, nsEStockIndicesDataV1.advance) &&
        Objects.equals(this.timestamp, nsEStockIndicesDataV1.timestamp) &&
        Objects.equals(this.data, nsEStockIndicesDataV1.data) &&
        Objects.equals(this.metadata, nsEStockIndicesDataV1.metadata) &&
        Objects.equals(this.marketStatus, nsEStockIndicesDataV1.marketStatus) &&
        Objects.equals(this.date30dAgo, nsEStockIndicesDataV1.date30dAgo) &&
        Objects.equals(this.date365dAgo, nsEStockIndicesDataV1.date365dAgo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, advance, timestamp, data, metadata, marketStatus, date30dAgo, date365dAgo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NSEStockIndicesDataV1 {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    advance: ").append(toIndentedString(advance)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    marketStatus: ").append(toIndentedString(marketStatus)).append("\n");
    sb.append("    date30dAgo: ").append(toIndentedString(date30dAgo)).append("\n");
    sb.append("    date365dAgo: ").append(toIndentedString(date365dAgo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `advance` to the URL query string
    if (getAdvance() != null) {
      joiner.add(getAdvance().toUrlQueryString(prefix + "advance" + suffix));
    }

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    // add `data` to the URL query string
    if (getData() != null) {
      for (int i = 0; i < getData().size(); i++) {
        if (getData().get(i) != null) {
          joiner.add(getData().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdata%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      joiner.add(getMetadata().toUrlQueryString(prefix + "metadata" + suffix));
    }

    // add `marketStatus` to the URL query string
    if (getMarketStatus() != null) {
      joiner.add(getMarketStatus().toUrlQueryString(prefix + "marketStatus" + suffix));
    }

    // add `date30dAgo` to the URL query string
    if (getDate30dAgo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdate30dAgo%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDate30dAgo()))));
    }

    // add `date365dAgo` to the URL query string
    if (getDate365dAgo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdate365dAgo%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDate365dAgo()))));
    }

    return joiner.toString();
  }
}

