/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * OHLCVTPoint
 */
@JsonPropertyOrder({
  OHLCVTPoint.JSON_PROPERTY_TIME,
  OHLCVTPoint.JSON_PROPERTY_OPEN,
  OHLCVTPoint.JSON_PROPERTY_HIGH,
  OHLCVTPoint.JSON_PROPERTY_LOW,
  OHLCVTPoint.JSON_PROPERTY_CLOSE,
  OHLCVTPoint.JSON_PROPERTY_VOLUME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class OHLCVTPoint {
  public static final String JSON_PROPERTY_TIME = "time";
  @javax.annotation.Nullable
  private OffsetDateTime time;

  public static final String JSON_PROPERTY_OPEN = "open";
  @javax.annotation.Nullable
  private Double open;

  public static final String JSON_PROPERTY_HIGH = "high";
  @javax.annotation.Nullable
  private Double high;

  public static final String JSON_PROPERTY_LOW = "low";
  @javax.annotation.Nullable
  private Double low;

  public static final String JSON_PROPERTY_CLOSE = "close";
  @javax.annotation.Nullable
  private Double close;

  public static final String JSON_PROPERTY_VOLUME = "volume";
  @javax.annotation.Nullable
  private Long volume;

  public OHLCVTPoint() { 
  }

  public OHLCVTPoint time(@javax.annotation.Nullable OffsetDateTime time) {
    this.time = time;
    return this;
  }

  /**
   * Get time
   * @return time
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getTime() {
    return time;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTime(@javax.annotation.Nullable OffsetDateTime time) {
    this.time = time;
  }


  public OHLCVTPoint open(@javax.annotation.Nullable Double open) {
    this.open = open;
    return this;
  }

  /**
   * Get open
   * @return open
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getOpen() {
    return open;
  }


  @JsonProperty(value = JSON_PROPERTY_OPEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpen(@javax.annotation.Nullable Double open) {
    this.open = open;
  }


  public OHLCVTPoint high(@javax.annotation.Nullable Double high) {
    this.high = high;
    return this;
  }

  /**
   * Get high
   * @return high
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getHigh() {
    return high;
  }


  @JsonProperty(value = JSON_PROPERTY_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHigh(@javax.annotation.Nullable Double high) {
    this.high = high;
  }


  public OHLCVTPoint low(@javax.annotation.Nullable Double low) {
    this.low = low;
    return this;
  }

  /**
   * Get low
   * @return low
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLow() {
    return low;
  }


  @JsonProperty(value = JSON_PROPERTY_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLow(@javax.annotation.Nullable Double low) {
    this.low = low;
  }


  public OHLCVTPoint close(@javax.annotation.Nullable Double close) {
    this.close = close;
    return this;
  }

  /**
   * Get close
   * @return close
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getClose() {
    return close;
  }


  @JsonProperty(value = JSON_PROPERTY_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClose(@javax.annotation.Nullable Double close) {
    this.close = close;
  }


  public OHLCVTPoint volume(@javax.annotation.Nullable Long volume) {
    this.volume = volume;
    return this;
  }

  /**
   * Get volume
   * @return volume
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VOLUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getVolume() {
    return volume;
  }


  @JsonProperty(value = JSON_PROPERTY_VOLUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolume(@javax.annotation.Nullable Long volume) {
    this.volume = volume;
  }


  /**
   * Return true if this OHLCVTPoint object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OHLCVTPoint ohLCVTPoint = (OHLCVTPoint) o;
    return Objects.equals(this.time, ohLCVTPoint.time) &&
        Objects.equals(this.open, ohLCVTPoint.open) &&
        Objects.equals(this.high, ohLCVTPoint.high) &&
        Objects.equals(this.low, ohLCVTPoint.low) &&
        Objects.equals(this.close, ohLCVTPoint.close) &&
        Objects.equals(this.volume, ohLCVTPoint.volume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(time, open, high, low, close, volume);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OHLCVTPoint {\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    open: ").append(toIndentedString(open)).append("\n");
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("    close: ").append(toIndentedString(close)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `time` to the URL query string
    if (getTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTime()))));
    }

    // add `open` to the URL query string
    if (getOpen() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sopen%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOpen()))));
    }

    // add `high` to the URL query string
    if (getHigh() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shigh%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHigh()))));
    }

    // add `low` to the URL query string
    if (getLow() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slow%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLow()))));
    }

    // add `close` to the URL query string
    if (getClose() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sclose%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClose()))));
    }

    // add `volume` to the URL query string
    if (getVolume() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svolume%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVolume()))));
    }

    return joiner.toString();
  }
}

