/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * OHLCRequest
 */
@JsonPropertyOrder({
  OHLCRequest.JSON_PROPERTY_SYMBOLS,
  OHLCRequest.JSON_PROPERTY_IS_INDEX_SYMBOL,
  OHLCRequest.JSON_PROPERTY_TIME_FRAME,
  OHLCRequest.JSON_PROPERTY_REFRESH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class OHLCRequest {
  public static final String JSON_PROPERTY_SYMBOLS = "symbols";
  @javax.annotation.Nullable
  private String symbols;

  public static final String JSON_PROPERTY_IS_INDEX_SYMBOL = "isIndexSymbol";
  @javax.annotation.Nullable
  private Boolean isIndexSymbol;

  public static final String JSON_PROPERTY_TIME_FRAME = "timeFrame";
  @javax.annotation.Nullable
  private String timeFrame;

  public static final String JSON_PROPERTY_REFRESH = "refresh";
  @javax.annotation.Nullable
  private Boolean refresh;

  public OHLCRequest() { 
  }

  public OHLCRequest symbols(@javax.annotation.Nullable String symbols) {
    this.symbols = symbols;
    return this;
  }

  /**
   * Get symbols
   * @return symbols
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SYMBOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSymbols() {
    return symbols;
  }


  @JsonProperty(value = JSON_PROPERTY_SYMBOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbols(@javax.annotation.Nullable String symbols) {
    this.symbols = symbols;
  }


  public OHLCRequest isIndexSymbol(@javax.annotation.Nullable Boolean isIndexSymbol) {
    this.isIndexSymbol = isIndexSymbol;
    return this;
  }

  /**
   * Get isIndexSymbol
   * @return isIndexSymbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsIndexSymbol() {
    return isIndexSymbol;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsIndexSymbol(@javax.annotation.Nullable Boolean isIndexSymbol) {
    this.isIndexSymbol = isIndexSymbol;
  }


  public OHLCRequest timeFrame(@javax.annotation.Nullable String timeFrame) {
    this.timeFrame = timeFrame;
    return this;
  }

  /**
   * Get timeFrame
   * @return timeFrame
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME_FRAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimeFrame() {
    return timeFrame;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME_FRAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeFrame(@javax.annotation.Nullable String timeFrame) {
    this.timeFrame = timeFrame;
  }


  public OHLCRequest refresh(@javax.annotation.Nullable Boolean refresh) {
    this.refresh = refresh;
    return this;
  }

  /**
   * Get refresh
   * @return refresh
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REFRESH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getRefresh() {
    return refresh;
  }


  @JsonProperty(value = JSON_PROPERTY_REFRESH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefresh(@javax.annotation.Nullable Boolean refresh) {
    this.refresh = refresh;
  }


  /**
   * Return true if this OHLCRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OHLCRequest ohLCRequest = (OHLCRequest) o;
    return Objects.equals(this.symbols, ohLCRequest.symbols) &&
        Objects.equals(this.isIndexSymbol, ohLCRequest.isIndexSymbol) &&
        Objects.equals(this.timeFrame, ohLCRequest.timeFrame) &&
        Objects.equals(this.refresh, ohLCRequest.refresh);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbols, isIndexSymbol, timeFrame, refresh);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OHLCRequest {\n");
    sb.append("    symbols: ").append(toIndentedString(symbols)).append("\n");
    sb.append("    isIndexSymbol: ").append(toIndentedString(isIndexSymbol)).append("\n");
    sb.append("    timeFrame: ").append(toIndentedString(timeFrame)).append("\n");
    sb.append("    refresh: ").append(toIndentedString(refresh)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `symbols` to the URL query string
    if (getSymbols() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssymbols%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSymbols()))));
    }

    // add `isIndexSymbol` to the URL query string
    if (getIsIndexSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisIndexSymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsIndexSymbol()))));
    }

    // add `timeFrame` to the URL query string
    if (getTimeFrame() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimeFrame%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimeFrame()))));
    }

    // add `refresh` to the URL query string
    if (getRefresh() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srefresh%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRefresh()))));
    }

    return joiner.toString();
  }
}

