/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * PositionMargin
 */
@JsonPropertyOrder({
  PositionMargin.JSON_PROPERTY_TRADING_SYMBOL,
  PositionMargin.JSON_PROPERTY_TOTAL_MARGIN,
  PositionMargin.JSON_PROPERTY_SPAN_MARGIN,
  PositionMargin.JSON_PROPERTY_EXPOSURE_MARGIN,
  PositionMargin.JSON_PROPERTY_ADDITIONAL_MARGIN,
  PositionMargin.JSON_PROPERTY_TYPE,
  PositionMargin.JSON_PROPERTY_EXCHANGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class PositionMargin {
  public static final String JSON_PROPERTY_TRADING_SYMBOL = "tradingSymbol";
  @javax.annotation.Nullable
  private String tradingSymbol;

  public static final String JSON_PROPERTY_TOTAL_MARGIN = "totalMargin";
  @javax.annotation.Nullable
  private BigDecimal totalMargin;

  public static final String JSON_PROPERTY_SPAN_MARGIN = "spanMargin";
  @javax.annotation.Nullable
  private BigDecimal spanMargin;

  public static final String JSON_PROPERTY_EXPOSURE_MARGIN = "exposureMargin";
  @javax.annotation.Nullable
  private BigDecimal exposureMargin;

  public static final String JSON_PROPERTY_ADDITIONAL_MARGIN = "additionalMargin";
  @javax.annotation.Nullable
  private BigDecimal additionalMargin;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_EXCHANGE = "exchange";
  @javax.annotation.Nullable
  private String exchange;

  public PositionMargin() { 
  }

  public PositionMargin tradingSymbol(@javax.annotation.Nullable String tradingSymbol) {
    this.tradingSymbol = tradingSymbol;
    return this;
  }

  /**
   * Get tradingSymbol
   * @return tradingSymbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRADING_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTradingSymbol() {
    return tradingSymbol;
  }


  @JsonProperty(value = JSON_PROPERTY_TRADING_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTradingSymbol(@javax.annotation.Nullable String tradingSymbol) {
    this.tradingSymbol = tradingSymbol;
  }


  public PositionMargin totalMargin(@javax.annotation.Nullable BigDecimal totalMargin) {
    this.totalMargin = totalMargin;
    return this;
  }

  /**
   * Get totalMargin
   * @return totalMargin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getTotalMargin() {
    return totalMargin;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalMargin(@javax.annotation.Nullable BigDecimal totalMargin) {
    this.totalMargin = totalMargin;
  }


  public PositionMargin spanMargin(@javax.annotation.Nullable BigDecimal spanMargin) {
    this.spanMargin = spanMargin;
    return this;
  }

  /**
   * Get spanMargin
   * @return spanMargin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPAN_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getSpanMargin() {
    return spanMargin;
  }


  @JsonProperty(value = JSON_PROPERTY_SPAN_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpanMargin(@javax.annotation.Nullable BigDecimal spanMargin) {
    this.spanMargin = spanMargin;
  }


  public PositionMargin exposureMargin(@javax.annotation.Nullable BigDecimal exposureMargin) {
    this.exposureMargin = exposureMargin;
    return this;
  }

  /**
   * Get exposureMargin
   * @return exposureMargin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPOSURE_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getExposureMargin() {
    return exposureMargin;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPOSURE_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExposureMargin(@javax.annotation.Nullable BigDecimal exposureMargin) {
    this.exposureMargin = exposureMargin;
  }


  public PositionMargin additionalMargin(@javax.annotation.Nullable BigDecimal additionalMargin) {
    this.additionalMargin = additionalMargin;
    return this;
  }

  /**
   * Get additionalMargin
   * @return additionalMargin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getAdditionalMargin() {
    return additionalMargin;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_MARGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalMargin(@javax.annotation.Nullable BigDecimal additionalMargin) {
    this.additionalMargin = additionalMargin;
  }


  public PositionMargin type(@javax.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }


  public PositionMargin exchange(@javax.annotation.Nullable String exchange) {
    this.exchange = exchange;
    return this;
  }

  /**
   * Get exchange
   * @return exchange
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getExchange() {
    return exchange;
  }


  @JsonProperty(value = JSON_PROPERTY_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchange(@javax.annotation.Nullable String exchange) {
    this.exchange = exchange;
  }


  /**
   * Return true if this PositionMargin object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PositionMargin positionMargin = (PositionMargin) o;
    return Objects.equals(this.tradingSymbol, positionMargin.tradingSymbol) &&
        Objects.equals(this.totalMargin, positionMargin.totalMargin) &&
        Objects.equals(this.spanMargin, positionMargin.spanMargin) &&
        Objects.equals(this.exposureMargin, positionMargin.exposureMargin) &&
        Objects.equals(this.additionalMargin, positionMargin.additionalMargin) &&
        Objects.equals(this.type, positionMargin.type) &&
        Objects.equals(this.exchange, positionMargin.exchange);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tradingSymbol, totalMargin, spanMargin, exposureMargin, additionalMargin, type, exchange);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PositionMargin {\n");
    sb.append("    tradingSymbol: ").append(toIndentedString(tradingSymbol)).append("\n");
    sb.append("    totalMargin: ").append(toIndentedString(totalMargin)).append("\n");
    sb.append("    spanMargin: ").append(toIndentedString(spanMargin)).append("\n");
    sb.append("    exposureMargin: ").append(toIndentedString(exposureMargin)).append("\n");
    sb.append("    additionalMargin: ").append(toIndentedString(additionalMargin)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `tradingSymbol` to the URL query string
    if (getTradingSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stradingSymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTradingSymbol()))));
    }

    // add `totalMargin` to the URL query string
    if (getTotalMargin() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalMargin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalMargin()))));
    }

    // add `spanMargin` to the URL query string
    if (getSpanMargin() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sspanMargin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSpanMargin()))));
    }

    // add `exposureMargin` to the URL query string
    if (getExposureMargin() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexposureMargin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExposureMargin()))));
    }

    // add `additionalMargin` to the URL query string
    if (getAdditionalMargin() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sadditionalMargin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAdditionalMargin()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `exchange` to the URL query string
    if (getExchange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexchange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExchange()))));
    }

    return joiner.toString();
  }
}

