/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * Position
 */
@JsonPropertyOrder({
  Position.JSON_PROPERTY_TRADING_SYMBOL,
  Position.JSON_PROPERTY_QUANTITY,
  Position.JSON_PROPERTY_TYPE,
  Position.JSON_PROPERTY_PRODUCT,
  Position.JSON_PROPERTY_EXCHANGE,
  Position.JSON_PROPERTY_PRICE,
  Position.JSON_PROPERTY_OPTION_TYPE,
  Position.JSON_PROPERTY_STRIKE_PRICE,
  Position.JSON_PROPERTY_EXPIRY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class Position {
  public static final String JSON_PROPERTY_TRADING_SYMBOL = "tradingSymbol";
  @javax.annotation.Nullable
  private String tradingSymbol;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  @javax.annotation.Nullable
  private Integer quantity;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_PRODUCT = "product";
  @javax.annotation.Nullable
  private String product;

  public static final String JSON_PROPERTY_EXCHANGE = "exchange";
  @javax.annotation.Nullable
  private String exchange;

  public static final String JSON_PROPERTY_PRICE = "price";
  @javax.annotation.Nullable
  private BigDecimal price;

  public static final String JSON_PROPERTY_OPTION_TYPE = "optionType";
  @javax.annotation.Nullable
  private String optionType;

  public static final String JSON_PROPERTY_STRIKE_PRICE = "strikePrice";
  @javax.annotation.Nullable
  private BigDecimal strikePrice;

  public static final String JSON_PROPERTY_EXPIRY = "expiry";
  @javax.annotation.Nullable
  private String expiry;

  public Position() { 
  }

  public Position tradingSymbol(@javax.annotation.Nullable String tradingSymbol) {
    this.tradingSymbol = tradingSymbol;
    return this;
  }

  /**
   * Get tradingSymbol
   * @return tradingSymbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRADING_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTradingSymbol() {
    return tradingSymbol;
  }


  @JsonProperty(value = JSON_PROPERTY_TRADING_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTradingSymbol(@javax.annotation.Nullable String tradingSymbol) {
    this.tradingSymbol = tradingSymbol;
  }


  public Position quantity(@javax.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Get quantity
   * @return quantity
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getQuantity() {
    return quantity;
  }


  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(@javax.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
  }


  public Position type(@javax.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }


  public Position product(@javax.annotation.Nullable String product) {
    this.product = product;
    return this;
  }

  /**
   * Get product
   * @return product
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRODUCT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProduct() {
    return product;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProduct(@javax.annotation.Nullable String product) {
    this.product = product;
  }


  public Position exchange(@javax.annotation.Nullable String exchange) {
    this.exchange = exchange;
    return this;
  }

  /**
   * Get exchange
   * @return exchange
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getExchange() {
    return exchange;
  }


  @JsonProperty(value = JSON_PROPERTY_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchange(@javax.annotation.Nullable String exchange) {
    this.exchange = exchange;
  }


  public Position price(@javax.annotation.Nullable BigDecimal price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(@javax.annotation.Nullable BigDecimal price) {
    this.price = price;
  }


  public Position optionType(@javax.annotation.Nullable String optionType) {
    this.optionType = optionType;
    return this;
  }

  /**
   * Get optionType
   * @return optionType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPTION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOptionType() {
    return optionType;
  }


  @JsonProperty(value = JSON_PROPERTY_OPTION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOptionType(@javax.annotation.Nullable String optionType) {
    this.optionType = optionType;
  }


  public Position strikePrice(@javax.annotation.Nullable BigDecimal strikePrice) {
    this.strikePrice = strikePrice;
    return this;
  }

  /**
   * Get strikePrice
   * @return strikePrice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STRIKE_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getStrikePrice() {
    return strikePrice;
  }


  @JsonProperty(value = JSON_PROPERTY_STRIKE_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStrikePrice(@javax.annotation.Nullable BigDecimal strikePrice) {
    this.strikePrice = strikePrice;
  }


  public Position expiry(@javax.annotation.Nullable String expiry) {
    this.expiry = expiry;
    return this;
  }

  /**
   * Get expiry
   * @return expiry
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getExpiry() {
    return expiry;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiry(@javax.annotation.Nullable String expiry) {
    this.expiry = expiry;
  }


  /**
   * Return true if this Position object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Position position = (Position) o;
    return Objects.equals(this.tradingSymbol, position.tradingSymbol) &&
        Objects.equals(this.quantity, position.quantity) &&
        Objects.equals(this.type, position.type) &&
        Objects.equals(this.product, position.product) &&
        Objects.equals(this.exchange, position.exchange) &&
        Objects.equals(this.price, position.price) &&
        Objects.equals(this.optionType, position.optionType) &&
        Objects.equals(this.strikePrice, position.strikePrice) &&
        Objects.equals(this.expiry, position.expiry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tradingSymbol, quantity, type, product, exchange, price, optionType, strikePrice, expiry);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Position {\n");
    sb.append("    tradingSymbol: ").append(toIndentedString(tradingSymbol)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    optionType: ").append(toIndentedString(optionType)).append("\n");
    sb.append("    strikePrice: ").append(toIndentedString(strikePrice)).append("\n");
    sb.append("    expiry: ").append(toIndentedString(expiry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `tradingSymbol` to the URL query string
    if (getTradingSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stradingSymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTradingSymbol()))));
    }

    // add `quantity` to the URL query string
    if (getQuantity() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squantity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuantity()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `product` to the URL query string
    if (getProduct() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproduct%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProduct()))));
    }

    // add `exchange` to the URL query string
    if (getExchange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexchange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExchange()))));
    }

    // add `price` to the URL query string
    if (getPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrice()))));
    }

    // add `optionType` to the URL query string
    if (getOptionType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soptionType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOptionType()))));
    }

    // add `strikePrice` to the URL query string
    if (getStrikePrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstrikePrice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStrikePrice()))));
    }

    // add `expiry` to the URL query string
    if (getExpiry() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpiry%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiry()))));
    }

    return joiner.toString();
  }
}

