/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * QuotesRequest
 */
@JsonPropertyOrder({
  QuotesRequest.JSON_PROPERTY_SYMBOLS,
  QuotesRequest.JSON_PROPERTY_TIME_FRAME,
  QuotesRequest.JSON_PROPERTY_FORCE_REFRESH,
  QuotesRequest.JSON_PROPERTY_INDEX_SYMBOL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class QuotesRequest {
  public static final String JSON_PROPERTY_SYMBOLS = "symbols";
  @javax.annotation.Nullable
  private String symbols;

  public static final String JSON_PROPERTY_TIME_FRAME = "timeFrame";
  @javax.annotation.Nullable
  private String timeFrame;

  public static final String JSON_PROPERTY_FORCE_REFRESH = "forceRefresh";
  @javax.annotation.Nullable
  private Boolean forceRefresh;

  public static final String JSON_PROPERTY_INDEX_SYMBOL = "indexSymbol";
  @javax.annotation.Nullable
  private Boolean indexSymbol;

  public QuotesRequest() { 
  }

  public QuotesRequest symbols(@javax.annotation.Nullable String symbols) {
    this.symbols = symbols;
    return this;
  }

  /**
   * Get symbols
   * @return symbols
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SYMBOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSymbols() {
    return symbols;
  }


  @JsonProperty(value = JSON_PROPERTY_SYMBOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbols(@javax.annotation.Nullable String symbols) {
    this.symbols = symbols;
  }


  public QuotesRequest timeFrame(@javax.annotation.Nullable String timeFrame) {
    this.timeFrame = timeFrame;
    return this;
  }

  /**
   * Get timeFrame
   * @return timeFrame
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME_FRAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimeFrame() {
    return timeFrame;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME_FRAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeFrame(@javax.annotation.Nullable String timeFrame) {
    this.timeFrame = timeFrame;
  }


  public QuotesRequest forceRefresh(@javax.annotation.Nullable Boolean forceRefresh) {
    this.forceRefresh = forceRefresh;
    return this;
  }

  /**
   * Get forceRefresh
   * @return forceRefresh
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FORCE_REFRESH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getForceRefresh() {
    return forceRefresh;
  }


  @JsonProperty(value = JSON_PROPERTY_FORCE_REFRESH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForceRefresh(@javax.annotation.Nullable Boolean forceRefresh) {
    this.forceRefresh = forceRefresh;
  }


  public QuotesRequest indexSymbol(@javax.annotation.Nullable Boolean indexSymbol) {
    this.indexSymbol = indexSymbol;
    return this;
  }

  /**
   * Get indexSymbol
   * @return indexSymbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIndexSymbol() {
    return indexSymbol;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndexSymbol(@javax.annotation.Nullable Boolean indexSymbol) {
    this.indexSymbol = indexSymbol;
  }


  /**
   * Return true if this QuotesRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuotesRequest quotesRequest = (QuotesRequest) o;
    return Objects.equals(this.symbols, quotesRequest.symbols) &&
        Objects.equals(this.timeFrame, quotesRequest.timeFrame) &&
        Objects.equals(this.forceRefresh, quotesRequest.forceRefresh) &&
        Objects.equals(this.indexSymbol, quotesRequest.indexSymbol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbols, timeFrame, forceRefresh, indexSymbol);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuotesRequest {\n");
    sb.append("    symbols: ").append(toIndentedString(symbols)).append("\n");
    sb.append("    timeFrame: ").append(toIndentedString(timeFrame)).append("\n");
    sb.append("    forceRefresh: ").append(toIndentedString(forceRefresh)).append("\n");
    sb.append("    indexSymbol: ").append(toIndentedString(indexSymbol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `symbols` to the URL query string
    if (getSymbols() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssymbols%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSymbols()))));
    }

    // add `timeFrame` to the URL query string
    if (getTimeFrame() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimeFrame%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimeFrame()))));
    }

    // add `forceRefresh` to the URL query string
    if (getForceRefresh() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sforceRefresh%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getForceRefresh()))));
    }

    // add `indexSymbol` to the URL query string
    if (getIndexSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindexSymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndexSymbol()))));
    }

    return joiner.toString();
  }
}

