/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.marketdata.client.ApiClient;
/**
 * SecuritySearchRequestV1
 */
@JsonPropertyOrder({
  SecuritySearchRequestV1.JSON_PROPERTY_SYMBOLS,
  SecuritySearchRequestV1.JSON_PROPERTY_ISIN,
  SecuritySearchRequestV1.JSON_PROPERTY_SECTOR,
  SecuritySearchRequestV1.JSON_PROPERTY_INDUSTRY,
  SecuritySearchRequestV1.JSON_PROPERTY_INDEX,
  SecuritySearchRequestV1.JSON_PROPERTY_QUERY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-28T04:03:39.214147100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class SecuritySearchRequestV1 {
  public static final String JSON_PROPERTY_SYMBOLS = "symbols";
  @javax.annotation.Nullable
  private List<String> symbols = new ArrayList<>();

  public static final String JSON_PROPERTY_ISIN = "isin";
  @javax.annotation.Nullable
  private String isin;

  public static final String JSON_PROPERTY_SECTOR = "sector";
  @javax.annotation.Nullable
  private String sector;

  public static final String JSON_PROPERTY_INDUSTRY = "industry";
  @javax.annotation.Nullable
  private String industry;

  public static final String JSON_PROPERTY_INDEX = "index";
  @javax.annotation.Nullable
  private String index;

  public static final String JSON_PROPERTY_QUERY = "query";
  @javax.annotation.Nullable
  private String query;

  public SecuritySearchRequestV1() { 
  }

  public SecuritySearchRequestV1 symbols(@javax.annotation.Nullable List<String> symbols) {
    this.symbols = symbols;
    return this;
  }

  public SecuritySearchRequestV1 addSymbolsItem(String symbolsItem) {
    if (this.symbols == null) {
      this.symbols = new ArrayList<>();
    }
    this.symbols.add(symbolsItem);
    return this;
  }

  /**
   * Get symbols
   * @return symbols
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SYMBOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getSymbols() {
    return symbols;
  }


  @JsonProperty(value = JSON_PROPERTY_SYMBOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbols(@javax.annotation.Nullable List<String> symbols) {
    this.symbols = symbols;
  }


  public SecuritySearchRequestV1 isin(@javax.annotation.Nullable String isin) {
    this.isin = isin;
    return this;
  }

  /**
   * Get isin
   * @return isin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ISIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIsin() {
    return isin;
  }


  @JsonProperty(value = JSON_PROPERTY_ISIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsin(@javax.annotation.Nullable String isin) {
    this.isin = isin;
  }


  public SecuritySearchRequestV1 sector(@javax.annotation.Nullable String sector) {
    this.sector = sector;
    return this;
  }

  /**
   * Get sector
   * @return sector
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSector() {
    return sector;
  }


  @JsonProperty(value = JSON_PROPERTY_SECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSector(@javax.annotation.Nullable String sector) {
    this.sector = sector;
  }


  public SecuritySearchRequestV1 industry(@javax.annotation.Nullable String industry) {
    this.industry = industry;
    return this;
  }

  /**
   * Get industry
   * @return industry
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDUSTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIndustry() {
    return industry;
  }


  @JsonProperty(value = JSON_PROPERTY_INDUSTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndustry(@javax.annotation.Nullable String industry) {
    this.industry = industry;
  }


  public SecuritySearchRequestV1 index(@javax.annotation.Nullable String index) {
    this.index = index;
    return this;
  }

  /**
   * Get index
   * @return index
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIndex() {
    return index;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndex(@javax.annotation.Nullable String index) {
    this.index = index;
  }


  public SecuritySearchRequestV1 query(@javax.annotation.Nullable String query) {
    this.query = query;
    return this;
  }

  /**
   * Get query
   * @return query
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUERY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getQuery() {
    return query;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuery(@javax.annotation.Nullable String query) {
    this.query = query;
  }


  /**
   * Return true if this SecuritySearchRequestV1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecuritySearchRequestV1 securitySearchRequestV1 = (SecuritySearchRequestV1) o;
    return Objects.equals(this.symbols, securitySearchRequestV1.symbols) &&
        Objects.equals(this.isin, securitySearchRequestV1.isin) &&
        Objects.equals(this.sector, securitySearchRequestV1.sector) &&
        Objects.equals(this.industry, securitySearchRequestV1.industry) &&
        Objects.equals(this.index, securitySearchRequestV1.index) &&
        Objects.equals(this.query, securitySearchRequestV1.query);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbols, isin, sector, industry, index, query);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecuritySearchRequestV1 {\n");
    sb.append("    symbols: ").append(toIndentedString(symbols)).append("\n");
    sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
    sb.append("    sector: ").append(toIndentedString(sector)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `symbols` to the URL query string
    if (getSymbols() != null) {
      for (int i = 0; i < getSymbols().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%ssymbols%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getSymbols().get(i)))));
      }
    }

    // add `isin` to the URL query string
    if (getIsin() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsin()))));
    }

    // add `sector` to the URL query string
    if (getSector() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssector%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSector()))));
    }

    // add `industry` to the URL query string
    if (getIndustry() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindustry%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndustry()))));
    }

    // add `index` to the URL query string
    if (getIndex() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindex%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndex()))));
    }

    // add `query` to the URL query string
    if (getQuery() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squery%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuery()))));
    }

    return joiner.toString();
  }
}

