apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jaas-config
  labels:
    app: kafka
    service: market-data
data:
  kafka_server_jaas.conf: |
    KafkaServer {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="kafkaUser"
      password="kafkaPassword123!"
      user_kafkaUser="kafkaPassword123!";
    };
