apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
    service: market-data
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        service: market-data
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.13-2.8.1
        ports:
        - containerPort: 9092
          name: kafka
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENERS
          value: "SASL_PLAINTEXT://:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "SASL_PLAINTEXT://kafka:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "SASL_PLAINTEXT:SASL_PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "SASL_PLAINTEXT"
        - name: KAFKA_SASL_ENABLED_MECHANISMS
          value: "PLAIN"
        - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
          value: "PLAIN"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx96m -Xms96m"
        - name: KAFKA_JVM_PERFORMANCE_OPTS
          value: "-XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35"
        - name: KAFKA_LOG_CLEANER_ENABLE
          value: "false"
        - name: KAFKA_LOG_CLEANER_THREADS
          value: "1"
        - name: KAFKA_OPTS
          value: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"
        - name: KAFKA_CONFIGMAP_SERVER_PROPERTIES
          value: "true"
        resources:
          requests:
            memory: "384Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "100m"
        volumeMounts:
        - name: kafka-data
          mountPath: /kafka
        - name: jaas-config
          mountPath: /etc/kafka/secrets
        - name: server-properties
          mountPath: /opt/kafka/config/server.properties.template
          subPath: server.properties
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      tolerations:
      - key: "node.cloudprovider.kubernetes.io/uninitialized"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: kafka-data
        emptyDir: {}
      - name: jaas-config
        configMap:
          name: kafka-jaas-config
      - name: server-properties
        configMap:
          name: kafka-server-properties
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default
      resources:
        requests:
          storage: 1Gi
