apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    service: market-data
spec:
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka
    service: market-data
spec:
  ports:
  - port: 9093
    targetPort: 9093
    name: kafka-internal
  clusterIP: None
  selector:
    app: kafka
