apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  labels:
    app: kafka
    service: market-data
type: Opaque
data:
  username: a2Fma2FVc2Vy  # Base64 encoded "kafkaUser"
  password: a2Fma2FQYXNzd29yZDEyMyE=  # Base64 encoded "kafkaPassword123!"