apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-server-properties
  labels:
    app: kafka
    service: market-data
data:
  server.properties: |
    # Basic Kafka configuration
    broker.id=${KAFKA_BROKER_ID}
    zookeeper.connect=${KAFKA_ZOOKEEPER_CONNECT}
    
    # Listeners configuration
    listeners=SASL_PLAINTEXT://:9092
    advertised.listeners=SASL_PLAINTEXT://kafka:9092
    inter.broker.listener.name=SASL_PLAINTEXT
    listener.security.protocol.map=SASL_PLAINTEXT:SASL_PLAINTEXT
    
    # SASL configuration
    sasl.enabled.mechanisms=PLAIN
    sasl.mechanism.inter.broker.protocol=PLAIN
    security.inter.broker.protocol=SASL_PLAINTEXT
    
    # Other settings
    offsets.topic.replication.factor=1
    auto.create.topics.enable=true
    log.cleaner.enable=false
    log.cleaner.threads=1
    
    advertised.listeners=SASL_PLAINTEXT://kafka:9092
    