server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: market_data_service
    static_configs:
      - targets:
          - localhost
        labels:
          job: market_data_service
          app: market-data-service
          __path__: /logs/market-data-service/*.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3})\s+\[(?P<thread>[^\]]+)\]\s+(?P<level>\w+)\s+(?P<logger>[^\s]+)\s+-\s+scheduler=(?P<scheduler>[^\s]+)\s+execution_time=(?P<execution_time>[^\s]+)\s+-\s+(?P<message>.*)'
      - labels:
          level:
          scheduler:
          thread:
          logger:
      - timestamp:
          source: timestamp
          format: 2006-01-02 15:04:05.000

  - job_name: market_data_scraper
    static_configs:
      - targets:
          - localhost
        labels:
          job: market_data_scraper
          app: market-data-scraper
          __path__: /logs/market-data-scraper/*.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3})\s+\[(?P<thread>[^\]]+)\]\s+(?P<level>\w+)\s+(?P<logger>[^\s]+)\s+-\s+scheduler=(?P<scheduler>[^\s]+)\s+execution_time=(?P<execution_time>[^\s]+)\s+-\s+(?P<message>.*)'
      - labels:
          level:
          scheduler:
          thread:
          logger:
      - timestamp:
          source: timestamp
          format: 2006-01-02 15:04:05.000

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/**/*.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3})\s+(?P<level>\w+)\s+(?P<message>.*)'
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: 2006-01-02 15:04:05.000