apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
    service: market-data
type: Opaque
data:
  username: c3NkMjY1OA==  # ssd2658 (base64 encoded)
  password: c3NkMjY1OA==  # ssd2658 (base64 encoded)
