apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    service: market-data
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  clusterIP: None
  selector:
    app: mongodb
