# Common configuration shared across all profiles
app:
  # Cookie configuration
  cookie:
    validator:
      required-cookies:
        - AKA_A2
        - ak_bmsc
        - bm_mi
        - bm_sv
        - bm_sz
        - nsit
        - nseappid
      expiry-threshold-minutes: 10
    cache:
      max-size: 100
      expiration-minutes: 60
  
  # Retry configuration
  retry:
    max-attempts: 3
    base-delay-ms: 1000
  
  # Thread pool configuration
  thread-pool:
    size: 5
    queue-capacity: 10
    prefix: "market-data-"
  
  # Validation configuration
  validation:
    max-age-minutes: 15

# Kafka configuration
kafka:
  bootstrap-servers: localhost:9092
  topics:
    indices: nse-indices-update
    stock-indices: nse-stock-indices-update


# NSE API configuration
nse:
  base-url: https://www.nseindia.com
  api:
    indices: /api/allIndices
    stock-indices: /api/equity-stockIndices
  headers:
    user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    accept: "application/json, text/plain, */*"
    accept-language: "en-US,en;q=0.9"
