# Local Development Configuration
environment: local

# Image Configuration
image:
  repository: am-market-data-market-data-service
  pullPolicy: Never
  tag: "latest"

# Application Configuration
config:
  marketData:
    maxRetries: 3
    retryDelayMs: 1000
    threadPoolSize: 5
    threadQueueCapacity: 10
    maxAgeMinutes: 15

# Service Configuration
service:
  type: ClusterIP
  port: 8084

# Ingress Configuration
ingress:
  enabled: false

# Resource Configuration
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Infrastructure Configuration
postgresql:
  enabled: true
  fullname: host.docker.internal
  auth:
    database: portfolio
    username: postgres
    password: password
  primary:
    service:
      port: 5456

influxdb:
  enabled: true
  url: http://host.docker.internal:8087
  auth:
    token: my-super-secret-auth-token
    org: am_investment
    bucket: market_data

kafka:
  enabled: true
  bootstrapServers: host.docker.internal:9092
  zookeeper:
    connect: host.docker.internal:2181
  config:
    consumerGroupId: am-market-data-service
    autoOffsetReset: earliest
    topics:
      stockPrice: am-stock-price-update
      nseIndices: nse-indices-update
      nseEtf: nse-etf-update

# Upstox Configuration
upstox:
  enabled: true
  auth:
    baseUrl: https://api.upstox.com/v2
    redirectUri: http://localhost:8080

# Monitoring Configuration
monitoring:
  enabled: true
  prometheus:
    scrape: true
    port: "8084"
    path: "/actuator/prometheus"
