/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.api;

import com.am.marketdata.client.ApiException;
import com.am.marketdata.model.MarginCalculationRequest;
import com.am.marketdata.model.MarginCalculationResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for MarginCalculatorApi
 */
@Disabled
public class MarginCalculatorApiTest {

    private final MarginCalculatorApi api = new MarginCalculatorApi();

    
    /**
     * Calculate margin requirements
     *
     * Calculates SPAN, exposure, and total margin requirements for various positions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void calculateMarginTest() throws ApiException {
        MarginCalculationRequest marginCalculationRequest = null;
        MarginCalculationResponse response = 
        api.calculateMargin(marginCalculationRequest);
        
        // TODO: test validations
    }
    
}
