/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.api;

import com.am.marketdata.client.ApiException;
import com.am.marketdata.model.NSEIndexV1;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for MarketIndicesApi
 */
@Disabled
public class MarketIndicesApiTest {

    private final MarketIndicesApi api = new MarketIndicesApi();

    
    /**
     * Get all market indices
     *
     * Returns all available market indices
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllIndicesTest() throws ApiException {
        List<NSEIndexV1> response = 
        api.getAllIndices();
        
        // TODO: test validations
    }
    
    /**
     * Get index by symbol
     *
     * Returns a specific index by its symbol
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIndexTest() throws ApiException {
        String symbol = null;
        NSEIndexV1 response = 
        api.getIndex(symbol);
        
        // TODO: test validations
    }
    
}
