/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.api;

import com.am.marketdata.client.ApiException;
import com.am.marketdata.model.SecurityDTOV1;
import com.am.marketdata.model.SecuritySearchRequestV1;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for SecurityMetadataApi
 */
@Disabled
public class SecurityMetadataApiTest {

    private final SecurityMetadataApi api = new SecurityMetadataApi();

    
    /**
     * Find securities by symbols
     *
     * Returns metadata for specific symbols
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findBySymbolsTest() throws ApiException {
        String symbols = null;
        List<SecurityDTOV1> response = 
        api.findBySymbols(symbols);
        
        // TODO: test validations
    }
    
    /**
     * Get all securities
     *
     * Returns all available securities in the database
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllTest() throws ApiException {
        List<SecurityDTOV1> response = 
        api.getAll();
        
        // TODO: test validations
    }
    
    /**
     * Get sectors for symbols
     *
     * Returns a mapping of symbol to sector
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSectorsTest() throws ApiException {
        String symbols = null;
        Map<String, String> response = 
        api.getSectors(symbols);
        
        // TODO: test validations
    }
    
    /**
     * Search securities
     *
     * Search for securities using various filters
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchTest() throws ApiException {
        SecuritySearchRequestV1 securitySearchRequestV1 = null;
        List<SecurityDTOV1> response = 
        api.search(securitySearchRequestV1);
        
        // TODO: test validations
    }
    
}
