/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.api;

import com.am.marketdata.client.ApiException;
import com.am.marketdata.model.NSEStockIndicesDataV1;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for StockIndicesApi
 */
@Disabled
public class StockIndicesApiTest {

    private final StockIndicesApi api = new StockIndicesApi();

    
    /**
     * Get available indices
     *
     * Returns list of available broad market and sector indices
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAvailableIndicesTest() throws ApiException {
        Map<String, List<String>> response = 
        api.getAvailableIndices();
        
        // TODO: test validations
    }
    
    /**
     * Get stock indices data
     *
     * Returns constituent stocks for a specific index
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStockIndicesTest() throws ApiException {
        String indexSymbol = null;
        Boolean forceRefresh = null;
        NSEStockIndicesDataV1 response = 
        api.getStockIndices(indexSymbol, forceRefresh);
        
        // TODO: test validations
    }
    
    /**
     * Get multiple stock indices
     *
     * Returns constituent stocks for multiple indices
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStockIndicesBatchTest() throws ApiException {
        List<String> requestBody = null;
        Boolean forceRefresh = null;
        List<NSEStockIndicesDataV1> response = 
        api.getStockIndicesBatch(requestBody, forceRefresh);
        
        // TODO: test validations
    }
    
}
