apiVersion: v2
name: market-data
description: A Helm chart for Market Data Service deployment on AKS
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.5.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: kafka
    version: 23.0.5
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: influxdb
    version: 5.4.13
    repository: https://helm.influxdata.com/
    condition: influxdb.enabled
  - name: grafana
    version: 6.57.3
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: prometheus
    version: 22.6.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
