apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "am-market-data.fullname" . }}-config
  labels:
    {{- include "am-market-data.labels" . | nindent 4 }}
data:
  # Spring Profile
  SPRING_PROFILES_ACTIVE: "{{ .Values.environment }}"
  TZ: "Asia/Kolkata"

  # Database Configuration
  POSTGRES_URL: "jdbc:postgresql://{{ .Values.postgresql.fullname }}:{{ .Values.postgresql.primary.service.port }}"
  POSTGRES_DATABASE: "{{ .Values.postgresql.auth.database }}"
  # Vault Secret Paths for PostgreSQL
  POSTGRES_SECRET_PATH: "{{ .Values.vault.secretPaths.postgres }}"


  # MongoDB Configuration
  # These are placeholder values that will be overridden by Vault Agent injected environment variables
  MONGODB_URL: "placeholder-mongodb-url"
  MONGODB_DATABASE: "placeholder-mongodb-database"
  MONGODB_USERNAME: "placeholder-mongodb-username"
  MONGODB_PASSWORD: "placeholder-mongodb-password"

  # Redis Configuration
  # These are placeholder values that will be overridden by Vault Agent injected environment variables
  REDIS_URL: "placeholder-redis-url"
  REDIS_PORT: "placeholder-redis-port"

  # InfluxDB Configuration
  # These are placeholder values that will be overridden by Vault Agent injected environment variables
  INFLUXDB_TOKEN: "placeholder-token"
  INFLUXDB_URL: "placeholder-url"
  INFLUXDB_ORG: "placeholder-org"
  INFLUXDB_BUCKET: "placeholder-bucket"

  # Kafka Configuration
  # These are placeholder values that will be overridden by Vault Agent injected environment variables
  KAFKA_BOOTSTRAP_SERVERS: "placeholder-kafka-bootstrap-servers"
  KAFKA_ZOOKEEPER_CONNECT: "placeholder-kafka-zookeeper-connect"
  KAFKA_CONSUMER_GROUP_ID: "placeholder-kafka-consumer-group-id"
  KAFKA_CONSUMER_AUTO_OFFSET_RESET: "placeholder-kafka-auto-offset-reset"
  KAFKA_TOPICS_STOCK_PRICE: "placeholder-kafka-stock-price-topic"
  KAFKA_TOPICS_NSE_INDICES: "placeholder-kafka-nse-indices-topic"
  KAFKA_TOPICS_NSE_ETF: "placeholder-kafka-nse-etf-topic"

  # Market Data Configuration
  MARKET_DATA_MAX_RETRIES: "{{ .Values.config.marketData.maxRetries }}"
  MARKET_DATA_RETRY_DELAY_MS: "{{ .Values.config.marketData.retryDelayMs }}"
  MARKET_DATA_THREAD_POOL_SIZE: "{{ .Values.config.marketData.threadPoolSize }}"
  MARKET_DATA_THREAD_QUEUE_CAPACITY: "{{ .Values.config.marketData.threadQueueCapacity }}"
  MARKET_DATA_MAX_AGE_MINUTES: "{{ .Values.config.marketData.maxAgeMinutes }}"

  # Upstock Configuration
  # These are placeholder values that will be overridden by Vault Agent injected environment variables
  UPSTOCK_API_BASE_URL: "placeholder-upstock-api-base-url"
  UPSTOCK_REDIRECT_URI: "placeholder-upstock-redirect-uri"
  UPSTOCK_ACCESS_TOKEN: "placeholder-upstock-access-token"
  UPSTOCK_CODE: "placeholder-upstock-code"

  # Metrics Configuration
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_METRICS_TAGS_APPLICATION: "market-data-{{ .Values.environment }}"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "{{ .Values.monitoring.prometheus.scrape }}"
