apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "am-market-data.fullname" . }}-config
  labels:
    {{- include "am-market-data.labels" . | nindent 4 }}
data:
  # Spring Profile
  SPRING_PROFILES_ACTIVE: "{{ .Values.environment }}"
  TZ: "Asia/Kolkata"

  # Database Configuration
  POSTGRES_URL: "jdbc:postgresql://{{ .Values.postgresql.fullname }}:{{ .Values.postgresql.primary.service.port }}"
  POSTGRES_DATABASE: "{{ .Values.postgresql.auth.database }}"
  # Vault Secret Paths for PostgreSQL
  POSTGRES_SECRET_PATH: "{{ .Values.vault.secretPaths.postgres }}"


  # MongoDB Configuration
  MONGODB_URL: "{{ .Values.vault.secretPaths.database }}/mongodb#url"
  MONGODB_DATABASE: "{{ .Values.vault.secretPaths.database }}/mongodb#marketdtadatabase"
  MONGODB_USERNAME: "{{ .Values.vault.secretPaths.database }}/mongodb#username"
  MONGODB_PASSWORD: "{{ .Values.vault.secretPaths.database }}/mongodb#password"

  # Redis Configuration
  REDIS_URL: "{{ .Values.vault.secretPaths.database }}/redis#url"
  REDIS_PORT: "{{ .Values.redis.auth.port }}"

  # InfluxDB Configuration
  INFLUXDB_TOKEN: "{{ .Values.vault.secretPaths.database }}/influxdb#token"
  INFLUXDB_URL: "{{ .Values.vault.secretPaths.database }}/influxdb#url"
  INFLUXDB_ORG: "{{ .Values.vault.secretPaths.database }}/influxdb#org"
  INFLUXDB_BUCKET: "{{ .Values.vault.secretPaths.database }}/influxdb#bucket"

  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.vault.secretPaths.basepath }}/kafka#kafkabootstrapserver"
  KAFKA_ZOOKEEPER_CONNECT: "{{ .Values.vault.secretPaths.basepath }}/kafka#zookeeperconnect"
  KAFKA_CONSUMER_GROUP_ID: "{{ .Values.vault.secretPaths.basepath }}/kafka#consumerGroupId"
  KAFKA_CONSUMER_AUTO_OFFSET_RESET: "{{ .Values.vault.secretPaths.basepath }}/kafka#autooffsetreset"
  KAFKA_TOPICS_STOCK_PRICE: "{{ .Values.vault.secretPaths.basepath }}/kafka#stockpricetopic"
  KAFKA_TOPICS_NSE_INDICES: "{{ .Values.vault.secretPaths.basepath }}/kafka#nseindicestopic"
  KAFKA_TOPICS_NSE_ETF: "{{ .Values.vault.secretPaths.basepath }}/kafka#nseetftopic"

  # Market Data Configuration
  MARKET_DATA_MAX_RETRIES: "{{ .Values.config.marketData.maxRetries }}"
  MARKET_DATA_RETRY_DELAY_MS: "{{ .Values.config.marketData.retryDelayMs }}"
  MARKET_DATA_THREAD_POOL_SIZE: "{{ .Values.config.marketData.threadPoolSize }}"
  MARKET_DATA_THREAD_QUEUE_CAPACITY: "{{ .Values.config.marketData.threadQueueCapacity }}"
  MARKET_DATA_MAX_AGE_MINUTES: "{{ .Values.config.marketData.maxAgeMinutes }}"

  # Upstox Configuration
  UPSTOX_API_BASE_URL: "{{ .Values.vault.secretPaths.api }}/upstox#apiBaseUrl"
  UPSTOX_REDIRECT_URI: "{{ .Values.vault.secretPaths.api }}/upstox#redirectUri"
  UPSTOX_ACCESS_TOKEN: "{{ .Values.vault.secretPaths.api }}/upstox#accesstoken"
  UPSTOX_CODE: "{{ .Values.vault.secretPaths.api }}/upstox#authCode"

  # Metrics Configuration
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_METRICS_TAGS_APPLICATION: "market-data-{{ .Values.environment }}"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "{{ .Values.monitoring.prometheus.scrape }}"
