apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "market-data.fullname" . }}-config
  labels:
    {{- include "market-data.labels" . | nindent 4 }}
data:
  # Spring Profile
  SPRING_PROFILES_ACTIVE: {{ .Values.environment }}
  TZ: Asia/Kolkata

  # Database Configuration
  POSTGRES_URL: jdbc:postgresql://{{ include "market-data.postgresql.fullname" . }}:{{ .Values.postgresql.primary.service.port }}
  POSTGRES_DATABASE: {{ .Values.postgresql.auth.database }}
  POSTGRES_USERNAME: {{ .Values.postgresql.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}

  # InfluxDB Configuration
  INFLUXDB_ORG: {{ .Values.influxdb.auth.org }}
  INFLUXDB_BUCKET: {{ .Values.influxdb.auth.bucket }}
  INFLUXDB_TOKEN: {{ .Values.influxdb.auth.token }}
  INFLUXDB_URL: http://{{ include "market-data.influxdb.fullname" . }}:{{ .Values.influxdb.service.port }}

  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: {{ include "market-data.kafka.fullname" . }}:{{ .Values.kafka.service.port }}
  KAFKA_ZOOKEEPER_CONNECT: {{ include "market-data.zookeeper.fullname" . }}:{{ .Values.kafka.zookeeper.service.port }}
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://{{ include "market-data.kafka.fullname" . }}:{{ .Values.kafka.service.port }}
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_CONSUMER_GROUP_ID: am-market-data-service
  KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest

  # Market Data Configuration (from memory)
  MARKET_DATA_MAX_RETRIES: {{ .Values.config.marketData.maxRetries | quote }}
  MARKET_DATA_RETRY_DELAY_MS: {{ .Values.config.marketData.retryDelayMs | quote }}
  MARKET_DATA_THREAD_POOL_SIZE: {{ .Values.config.marketData.threadPoolSize | quote }}
  MARKET_DATA_THREAD_QUEUE_CAPACITY: {{ .Values.config.marketData.threadQueueCapacity | quote }}
  MARKET_DATA_MAX_AGE_MINUTES: {{ .Values.config.marketData.maxAgeMinutes | quote }}

  # Metrics Configuration (from memory)
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,metrics,prometheus
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
  MANAGEMENT_METRICS_TAGS_APPLICATION: market-data-{{ .Values.environment }}
