apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "am-market-data.fullname" . }}
  labels:
    {{- include "am-market-data.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "am-market-data.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Prometheus annotations for metrics collection
        prometheus.io/scrape: "{{ .Values.monitoring.prometheus.scrape }}"
        prometheus.io/path: "{{ .Values.monitoring.prometheus.path }}"
        prometheus.io/port: "{{ .Values.monitoring.prometheus.port }}"
        # Add checksum annotations for config changes
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        # Vault Agent Injector annotations
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/auth-config-audience: "vault"
        vault.hashicorp.com/auth-config-issuer: "https://kubernetes.default.svc.cluster.local"
        vault.hashicorp.com/auth-config-disable-iss-validation: "true"
        vault.hashicorp.com/auth-config-disable-local-ca-jwt: "true"
        vault.hashicorp.com/auth-config-disable-local-ca-jwt: "true"  
        vault.hashicorp.com/role: "dev-role"
        vault.hashicorp.com/agent-inject-secret-influxdb: "kv/preprod/database/influxdb"
        vault.hashicorp.com/agent-inject-template-influxdb: |
          {{`{{- with secret "kv/ preprod/database/influxdb" -}}
          export INFLUXDB_URL="{{ .Data.data.url }}"
          export INFLUXDB_TOKEN="{{ .Data.data.token }}"
          export INFLUXDB_ORG="{{ .Data.data.org }}"
          export INFLUXDB_BUCKET="{{ .Data.data.bucket }}"
          {{- end -}}`}}
        vault.hashicorp.com/agent-inject-secret-mongodb: "kv/preprod/database/mongodb"
        vault.hashicorp.com/agent-inject-template-mongodb: |
          {{`{{- with secret "kv/preprod/database/mongodb" -}}
          export MONGODB_URL="{{ .Data.data.url }}"
          export MONGODB_DATABASE="{{ .Data.data.marketdtadatabase }}"
          export MONGODB_USERNAME="{{ .Data.data.username }}"
          export MONGODB_PASSWORD="{{ .Data.data.password }}"
          {{- end -}}`}}
        vault.hashicorp.com/agent-inject-secret-redis: "kv/preprod/database/redis"
        vault.hashicorp.com/agent-inject-template-redis: |
          {{`{{- with secret "kv/preprod/database/redis" -}}
          export REDIS_URL="{{ .Data.data.url }}"
          export REDIS_PORT="{{ .Data.data.port }}"
          export REDIS_PASSWORD="{{ .Data.data.password }}"
          {{- end -}}`}}
        vault.hashicorp.com/agent-inject-secret-kafka: "kv/preprod/kafka"
        vault.hashicorp.com/agent-inject-template-kafka: |
          {{`{{- with secret "kv/preprod/kafka" -}}
          export KAFKA_BOOTSTRAP_SERVERS="{{ .Data.data.kafkabootstrapserver }}"
          export KAFKA_ZOOKEEPER_CONNECT="{{ .Data.data.zookeeperconnect }}"
          export KAFKA_CONSUMER_GROUP_ID="{{ .Data.data.consumerGroupId }}"
          export KAFKA_CONSUMER_AUTO_OFFSET_RESET="{{ .Data.data.autooffsetreset }}"
          export KAFKA_TOPICS_STOCK_PRICE="{{ .Data.data.stockpricetopic }}"
          export KAFKA_TOPICS_NSE_INDICES="{{ .Data.data.nseindicestopic }}"
          export KAFKA_TOPICS_NSE_ETF="{{ .Data.data.nseetftopic }}"
          {{- end -}}`}}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "am-market-data.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: vault-auth
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "ghcr.io/am-portfolio/am-market-data/market-data-service:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          # Load environment variables from ConfigMap
          envFrom:
            - configMapRef:
                name: {{ include "am-market-data.fullname" . }}-config
          env:
            # Thread Pool Configuration (from memory)
            - name: MARKET_DATA_THREAD_POOL_SIZE
              value: "{{ .Values.config.marketData.threadPoolSize }}"
            - name: MARKET_DATA_THREAD_QUEUE_CAPACITY
              value: "{{ .Values.config.marketData.threadQueueCapacity }}"
            # Retry Configuration (from memory)
            - name: MARKET_DATA_MAX_RETRIES
              value: "{{ .Values.config.marketData.maxRetries }}"
            - name: MARKET_DATA_RETRY_DELAY_MS
              value: "{{ .Values.config.marketData.retryDelayMs }}"
            # Data Validation (from memory)
            - name: MARKET_DATA_MAX_AGE_MINUTES
              value: "{{ .Values.config.marketData.maxAgeMinutes }}"
            # Metrics Configuration (from memory)
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,metrics,prometheus"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: "always"
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: "market-data-{{ .Values.environment }}"
          ports:
            - name: http
              containerPort: 8084
              protocol: TCP
          # Health checks with retry-based thresholds
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: {{ .Values.config.marketData.maxRetries }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: {{ .Values.config.marketData.maxRetries }}
          # Resource limits from values file
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
