{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "market-data.fullname" . }}-secrets
  labels:
    {{- include "market-data.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "market-data.fullname" . }}-secrets
    template:
      metadata:
        labels:
          {{- include "market-data.labels" . | nindent 10 }}
  data:
    # GitHub Package Registry
    - secretKey: GITHUB_PACKAGES_USERNAME
      remoteRef:
        key: {{ .Values.vault.secretPaths.github }}
        property: username
    - secretKey: GITHUB_PACKAGES_TOKEN
      remoteRef:
        key: {{ .Values.vault.secretPaths.githubToken }}
        property: token

    # Database Secrets
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.vault.secretPaths.database }}
        property: password
    - secretKey: POSTGRES_USERNAME
      remoteRef:
        key: {{ .Values.vault.secretPaths.database }}
        property: username

    # InfluxDB Secrets
    - secretKey: INFLUXDB_TOKEN
      remoteRef:
        key: {{ .Values.vault.secretPaths.influxdb }}
        property: token

    # Upstox Secrets
    - secretKey: UPSTOX_ACCESS_TOKEN
      remoteRef:
        key: {{ .Values.vault.secretPaths.upstox }}
        property: access_token
    - secretKey: UPSTOX_API_KEY
      remoteRef:
        key: {{ .Values.vault.secretPaths.upstox }}
        property: api_key
    - secretKey: UPSTOX_SECRET_KEY
      remoteRef:
        key: {{ .Values.vault.secretPaths.upstox }}
        property: secret_key
    - secretKey: UPSTOX_CODE
      remoteRef:
        key: {{ .Values.vault.secretPaths.upstox }}
        property: auth_code
{{- end }}
