/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Advance
 */
class AdvanceTest {
    private final Advance model = new Advance();

    /**
     * Model tests for Advance
     */
    @Test
    void testAdvance() {
        // TODO: test Advance
    }

    /**
     * Test the property 'declines'
     */
    @Test
    void declinesTest() {
        // TODO: test declines
    }

    /**
     * Test the property 'advances'
     */
    @Test
    void advancesTest() {
        // TODO: test advances
    }

    /**
     * Test the property 'unchanged'
     */
    @Test
    void unchangedTest() {
        // TODO: test unchanged
    }

}
