/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BrokerageCalculationRequest
 */
class BrokerageCalculationRequestTest {
    private final BrokerageCalculationRequest model = new BrokerageCalculationRequest();

    /**
     * Model tests for BrokerageCalculationRequest
     */
    @Test
    void testBrokerageCalculationRequest() {
        // TODO: test BrokerageCalculationRequest
    }

    /**
     * Test the property 'tradingSymbol'
     */
    @Test
    void tradingSymbolTest() {
        // TODO: test tradingSymbol
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'buyPrice'
     */
    @Test
    void buyPriceTest() {
        // TODO: test buyPrice
    }

    /**
     * Test the property 'sellPrice'
     */
    @Test
    void sellPriceTest() {
        // TODO: test sellPrice
    }

    /**
     * Test the property 'exchange'
     */
    @Test
    void exchangeTest() {
        // TODO: test exchange
    }

    /**
     * Test the property 'tradeType'
     */
    @Test
    void tradeTypeTest() {
        // TODO: test tradeType
    }

    /**
     * Test the property 'brokerType'
     */
    @Test
    void brokerTypeTest() {
        // TODO: test brokerType
    }

    /**
     * Test the property 'brokerName'
     */
    @Test
    void brokerNameTest() {
        // TODO: test brokerName
    }

    /**
     * Test the property 'brokerFlatFee'
     */
    @Test
    void brokerFlatFeeTest() {
        // TODO: test brokerFlatFee
    }

    /**
     * Test the property 'brokerPercentageFee'
     */
    @Test
    void brokerPercentageFeeTest() {
        // TODO: test brokerPercentageFee
    }

    /**
     * Test the property 'stateCode'
     */
    @Test
    void stateCodeTest() {
        // TODO: test stateCode
    }

}
