/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BrokerageCalculationResponse
 */
class BrokerageCalculationResponseTest {
    private final BrokerageCalculationResponse model = new BrokerageCalculationResponse();

    /**
     * Model tests for BrokerageCalculationResponse
     */
    @Test
    void testBrokerageCalculationResponse() {
        // TODO: test BrokerageCalculationResponse
    }

    /**
     * Test the property 'buyTransactionValue'
     */
    @Test
    void buyTransactionValueTest() {
        // TODO: test buyTransactionValue
    }

    /**
     * Test the property 'sellTransactionValue'
     */
    @Test
    void sellTransactionValueTest() {
        // TODO: test sellTransactionValue
    }

    /**
     * Test the property 'buyBrokerage'
     */
    @Test
    void buyBrokerageTest() {
        // TODO: test buyBrokerage
    }

    /**
     * Test the property 'sellBrokerage'
     */
    @Test
    void sellBrokerageTest() {
        // TODO: test sellBrokerage
    }

    /**
     * Test the property 'buySTT'
     */
    @Test
    void buySTTTest() {
        // TODO: test buySTT
    }

    /**
     * Test the property 'sellSTT'
     */
    @Test
    void sellSTTTest() {
        // TODO: test sellSTT
    }

    /**
     * Test the property 'buyExchangeCharges'
     */
    @Test
    void buyExchangeChargesTest() {
        // TODO: test buyExchangeCharges
    }

    /**
     * Test the property 'sellExchangeCharges'
     */
    @Test
    void sellExchangeChargesTest() {
        // TODO: test sellExchangeCharges
    }

    /**
     * Test the property 'buyGST'
     */
    @Test
    void buyGSTTest() {
        // TODO: test buyGST
    }

    /**
     * Test the property 'sellGST'
     */
    @Test
    void sellGSTTest() {
        // TODO: test sellGST
    }

    /**
     * Test the property 'buySEBICharges'
     */
    @Test
    void buySEBIChargesTest() {
        // TODO: test buySEBICharges
    }

    /**
     * Test the property 'sellSEBICharges'
     */
    @Test
    void sellSEBIChargesTest() {
        // TODO: test sellSEBICharges
    }

    /**
     * Test the property 'buyStampDuty'
     */
    @Test
    void buyStampDutyTest() {
        // TODO: test buyStampDuty
    }

    /**
     * Test the property 'sellStampDuty'
     */
    @Test
    void sellStampDutyTest() {
        // TODO: test sellStampDuty
    }

    /**
     * Test the property 'dpCharges'
     */
    @Test
    void dpChargesTest() {
        // TODO: test dpCharges
    }

    /**
     * Test the property 'totalBuyCharges'
     */
    @Test
    void totalBuyChargesTest() {
        // TODO: test totalBuyCharges
    }

    /**
     * Test the property 'totalSellCharges'
     */
    @Test
    void totalSellChargesTest() {
        // TODO: test totalSellCharges
    }

    /**
     * Test the property 'totalCharges'
     */
    @Test
    void totalChargesTest() {
        // TODO: test totalCharges
    }

    /**
     * Test the property 'netProfitLoss'
     */
    @Test
    void netProfitLossTest() {
        // TODO: test netProfitLoss
    }

    /**
     * Test the property 'chargesPercentage'
     */
    @Test
    void chargesPercentageTest() {
        // TODO: test chargesPercentage
    }

    /**
     * Test the property 'breakEvenPrice'
     */
    @Test
    void breakEvenPriceTest() {
        // TODO: test breakEvenPrice
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'error'
     */
    @Test
    void errorTest() {
        // TODO: test error
    }

}
