/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.am.marketdata.model.OHLCVTPoint;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HistoricalData
 */
class HistoricalDataTest {
    private final HistoricalData model = new HistoricalData();

    /**
     * Model tests for HistoricalData
     */
    @Test
    void testHistoricalData() {
        // TODO: test HistoricalData
    }

    /**
     * Test the property 'tradingSymbol'
     */
    @Test
    void tradingSymbolTest() {
        // TODO: test tradingSymbol
    }

    /**
     * Test the property 'isin'
     */
    @Test
    void isinTest() {
        // TODO: test isin
    }

    /**
     * Test the property 'fromDate'
     */
    @Test
    void fromDateTest() {
        // TODO: test fromDate
    }

    /**
     * Test the property 'toDate'
     */
    @Test
    void toDateTest() {
        // TODO: test toDate
    }

    /**
     * Test the property 'interval'
     */
    @Test
    void intervalTest() {
        // TODO: test interval
    }

    /**
     * Test the property 'dataPoints'
     */
    @Test
    void dataPointsTest() {
        // TODO: test dataPoints
    }

    /**
     * Test the property 'dataPointCount'
     */
    @Test
    void dataPointCountTest() {
        // TODO: test dataPointCount
    }

    /**
     * Test the property 'exchange'
     */
    @Test
    void exchangeTest() {
        // TODO: test exchange
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'retrievalTime'
     */
    @Test
    void retrievalTimeTest() {
        // TODO: test retrievalTime
    }

}
