/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HistoricalDataRequest
 */
class HistoricalDataRequestTest {
    private final HistoricalDataRequest model = new HistoricalDataRequest();

    /**
     * Model tests for HistoricalDataRequest
     */
    @Test
    void testHistoricalDataRequest() {
        // TODO: test HistoricalDataRequest
    }

    /**
     * Test the property 'symbols'
     */
    @Test
    void symbolsTest() {
        // TODO: test symbols
    }

    /**
     * Test the property 'from'
     */
    @Test
    void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'interval'
     */
    @Test
    void intervalTest() {
        // TODO: test interval
    }

    /**
     * Test the property 'continuous'
     */
    @Test
    void continuousTest() {
        // TODO: test continuous
    }

    /**
     * Test the property 'instrumentType'
     */
    @Test
    void instrumentTypeTest() {
        // TODO: test instrumentType
    }

    /**
     * Test the property 'forceRefresh'
     */
    @Test
    void forceRefreshTest() {
        // TODO: test forceRefresh
    }

    /**
     * Test the property 'filterType'
     */
    @Test
    void filterTypeTest() {
        // TODO: test filterType
    }

    /**
     * Test the property 'filterFrequency'
     */
    @Test
    void filterFrequencyTest() {
        // TODO: test filterFrequency
    }

    /**
     * Test the property 'additionalParams'
     */
    @Test
    void additionalParamsTest() {
        // TODO: test additionalParams
    }

    /**
     * Test the property 'isIndexSymbol'
     */
    @Test
    void isIndexSymbolTest() {
        // TODO: test isIndexSymbol
    }

}
