/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IndexMetadata
 */
class IndexMetadataTest {
    private final IndexMetadata model = new IndexMetadata();

    /**
     * Model tests for IndexMetadata
     */
    @Test
    void testIndexMetadata() {
        // TODO: test IndexMetadata
    }

    /**
     * Test the property 'indexName'
     */
    @Test
    void indexNameTest() {
        // TODO: test indexName
    }

    /**
     * Test the property 'open'
     */
    @Test
    void openTest() {
        // TODO: test open
    }

    /**
     * Test the property 'high'
     */
    @Test
    void highTest() {
        // TODO: test high
    }

    /**
     * Test the property 'low'
     */
    @Test
    void lowTest() {
        // TODO: test low
    }

    /**
     * Test the property 'previousClose'
     */
    @Test
    void previousCloseTest() {
        // TODO: test previousClose
    }

    /**
     * Test the property 'last'
     */
    @Test
    void lastTest() {
        // TODO: test last
    }

    /**
     * Test the property 'percChange'
     */
    @Test
    void percChangeTest() {
        // TODO: test percChange
    }

    /**
     * Test the property 'change'
     */
    @Test
    void changeTest() {
        // TODO: test change
    }

    /**
     * Test the property 'timeVal'
     */
    @Test
    void timeValTest() {
        // TODO: test timeVal
    }

    /**
     * Test the property 'yearHigh'
     */
    @Test
    void yearHighTest() {
        // TODO: test yearHigh
    }

    /**
     * Test the property 'yearLow'
     */
    @Test
    void yearLowTest() {
        // TODO: test yearLow
    }

    /**
     * Test the property 'indicativeClose'
     */
    @Test
    void indicativeCloseTest() {
        // TODO: test indicativeClose
    }

    /**
     * Test the property 'totalTradedVolume'
     */
    @Test
    void totalTradedVolumeTest() {
        // TODO: test totalTradedVolume
    }

    /**
     * Test the property 'totalTradedValue'
     */
    @Test
    void totalTradedValueTest() {
        // TODO: test totalTradedValue
    }

    /**
     * Test the property 'ffmcSum'
     */
    @Test
    void ffmcSumTest() {
        // TODO: test ffmcSum
    }

}
