/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.am.marketdata.model.Position;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MarginCalculationRequest
 */
class MarginCalculationRequestTest {
    private final MarginCalculationRequest model = new MarginCalculationRequest();

    /**
     * Model tests for MarginCalculationRequest
     */
    @Test
    void testMarginCalculationRequest() {
        // TODO: test MarginCalculationRequest
    }

    /**
     * Test the property 'positions'
     */
    @Test
    void positionsTest() {
        // TODO: test positions
    }

    /**
     * Test the property 'orderType'
     */
    @Test
    void orderTypeTest() {
        // TODO: test orderType
    }

    /**
     * Test the property 'exchange'
     */
    @Test
    void exchangeTest() {
        // TODO: test exchange
    }

}
