/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.am.marketdata.model.PositionMargin;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MarginCalculationResponse
 */
class MarginCalculationResponseTest {
    private final MarginCalculationResponse model = new MarginCalculationResponse();

    /**
     * Model tests for MarginCalculationResponse
     */
    @Test
    void testMarginCalculationResponse() {
        // TODO: test MarginCalculationResponse
    }

    /**
     * Test the property 'totalMarginRequired'
     */
    @Test
    void totalMarginRequiredTest() {
        // TODO: test totalMarginRequired
    }

    /**
     * Test the property 'spanMargin'
     */
    @Test
    void spanMarginTest() {
        // TODO: test spanMargin
    }

    /**
     * Test the property 'exposureMargin'
     */
    @Test
    void exposureMarginTest() {
        // TODO: test exposureMargin
    }

    /**
     * Test the property 'additionalMargin'
     */
    @Test
    void additionalMarginTest() {
        // TODO: test additionalMargin
    }

    /**
     * Test the property 'positionMargins'
     */
    @Test
    void positionMarginsTest() {
        // TODO: test positionMargins
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'error'
     */
    @Test
    void errorTest() {
        // TODO: test error
    }

}
