/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MarketStatus
 */
class MarketStatusTest {
    private final MarketStatus model = new MarketStatus();

    /**
     * Model tests for MarketStatus
     */
    @Test
    void testMarketStatus() {
        // TODO: test MarketStatus
    }

    /**
     * Test the property 'market'
     */
    @Test
    void marketTest() {
        // TODO: test market
    }

    /**
     * Test the property 'marketStatus'
     */
    @Test
    void marketStatusTest() {
        // TODO: test marketStatus
    }

    /**
     * Test the property 'tradeDate'
     */
    @Test
    void tradeDateTest() {
        // TODO: test tradeDate
    }

    /**
     * Test the property 'index'
     */
    @Test
    void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'last'
     */
    @Test
    void lastTest() {
        // TODO: test last
    }

    /**
     * Test the property 'variation'
     */
    @Test
    void variationTest() {
        // TODO: test variation
    }

    /**
     * Test the property 'percentChange'
     */
    @Test
    void percentChangeTest() {
        // TODO: test percentChange
    }

    /**
     * Test the property 'marketStatusMessage'
     */
    @Test
    void marketStatusMessageTest() {
        // TODO: test marketStatusMessage
    }

}
