/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NSEIndexV1
 */
class NSEIndexV1Test {
    private final NSEIndexV1 model = new NSEIndexV1();

    /**
     * Model tests for NSEIndexV1
     */
    @Test
    void testNSEIndexV1() {
        // TODO: test NSEIndexV1
    }

    /**
     * Test the property 'key'
     */
    @Test
    void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'index'
     */
    @Test
    void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'indexSymbol'
     */
    @Test
    void indexSymbolTest() {
        // TODO: test indexSymbol
    }

    /**
     * Test the property 'last'
     */
    @Test
    void lastTest() {
        // TODO: test last
    }

    /**
     * Test the property 'variation'
     */
    @Test
    void variationTest() {
        // TODO: test variation
    }

    /**
     * Test the property 'percentChange'
     */
    @Test
    void percentChangeTest() {
        // TODO: test percentChange
    }

    /**
     * Test the property 'open'
     */
    @Test
    void openTest() {
        // TODO: test open
    }

    /**
     * Test the property 'high'
     */
    @Test
    void highTest() {
        // TODO: test high
    }

    /**
     * Test the property 'low'
     */
    @Test
    void lowTest() {
        // TODO: test low
    }

    /**
     * Test the property 'previousClose'
     */
    @Test
    void previousCloseTest() {
        // TODO: test previousClose
    }

    /**
     * Test the property 'yearHigh'
     */
    @Test
    void yearHighTest() {
        // TODO: test yearHigh
    }

    /**
     * Test the property 'yearLow'
     */
    @Test
    void yearLowTest() {
        // TODO: test yearLow
    }

    /**
     * Test the property 'indicativeClose'
     */
    @Test
    void indicativeCloseTest() {
        // TODO: test indicativeClose
    }

    /**
     * Test the property 'pe'
     */
    @Test
    void peTest() {
        // TODO: test pe
    }

    /**
     * Test the property 'pb'
     */
    @Test
    void pbTest() {
        // TODO: test pb
    }

    /**
     * Test the property 'dy'
     */
    @Test
    void dyTest() {
        // TODO: test dy
    }

    /**
     * Test the property 'declines'
     */
    @Test
    void declinesTest() {
        // TODO: test declines
    }

    /**
     * Test the property 'advances'
     */
    @Test
    void advancesTest() {
        // TODO: test advances
    }

    /**
     * Test the property 'unchanged'
     */
    @Test
    void unchangedTest() {
        // TODO: test unchanged
    }

    /**
     * Test the property 'percentChange365d'
     */
    @Test
    void percentChange365dTest() {
        // TODO: test percentChange365d
    }

    /**
     * Test the property 'date365dAgo'
     */
    @Test
    void date365dAgoTest() {
        // TODO: test date365dAgo
    }

    /**
     * Test the property 'chart365dPath'
     */
    @Test
    void chart365dPathTest() {
        // TODO: test chart365dPath
    }

    /**
     * Test the property 'date30dAgo'
     */
    @Test
    void date30dAgoTest() {
        // TODO: test date30dAgo
    }

    /**
     * Test the property 'percentChange30d'
     */
    @Test
    void percentChange30dTest() {
        // TODO: test percentChange30d
    }

    /**
     * Test the property 'chart30dPath'
     */
    @Test
    void chart30dPathTest() {
        // TODO: test chart30dPath
    }

    /**
     * Test the property 'chartTodayPath'
     */
    @Test
    void chartTodayPathTest() {
        // TODO: test chartTodayPath
    }

    /**
     * Test the property 'previousDay'
     */
    @Test
    void previousDayTest() {
        // TODO: test previousDay
    }

    /**
     * Test the property 'oneWeekAgo'
     */
    @Test
    void oneWeekAgoTest() {
        // TODO: test oneWeekAgo
    }

    /**
     * Test the property 'oneMonthAgo'
     */
    @Test
    void oneMonthAgoTest() {
        // TODO: test oneMonthAgo
    }

    /**
     * Test the property 'oneYearAgo'
     */
    @Test
    void oneYearAgoTest() {
        // TODO: test oneYearAgo
    }

}
