/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OHLCVTPoint
 */
class OHLCVTPointTest {
    private final OHLCVTPoint model = new OHLCVTPoint();

    /**
     * Model tests for OHLCVTPoint
     */
    @Test
    void testOHLCVTPoint() {
        // TODO: test OHLCVTPoint
    }

    /**
     * Test the property 'time'
     */
    @Test
    void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'open'
     */
    @Test
    void openTest() {
        // TODO: test open
    }

    /**
     * Test the property 'high'
     */
    @Test
    void highTest() {
        // TODO: test high
    }

    /**
     * Test the property 'low'
     */
    @Test
    void lowTest() {
        // TODO: test low
    }

    /**
     * Test the property 'close'
     */
    @Test
    void closeTest() {
        // TODO: test close
    }

    /**
     * Test the property 'volume'
     */
    @Test
    void volumeTest() {
        // TODO: test volume
    }

}
