/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Position
 */
class PositionTest {
    private final Position model = new Position();

    /**
     * Model tests for Position
     */
    @Test
    void testPosition() {
        // TODO: test Position
    }

    /**
     * Test the property 'tradingSymbol'
     */
    @Test
    void tradingSymbolTest() {
        // TODO: test tradingSymbol
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'product'
     */
    @Test
    void productTest() {
        // TODO: test product
    }

    /**
     * Test the property 'exchange'
     */
    @Test
    void exchangeTest() {
        // TODO: test exchange
    }

    /**
     * Test the property 'price'
     */
    @Test
    void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'optionType'
     */
    @Test
    void optionTypeTest() {
        // TODO: test optionType
    }

    /**
     * Test the property 'strikePrice'
     */
    @Test
    void strikePriceTest() {
        // TODO: test strikePrice
    }

    /**
     * Test the property 'expiry'
     */
    @Test
    void expiryTest() {
        // TODO: test expiry
    }

}
