/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PositionMargin
 */
class PositionMarginTest {
    private final PositionMargin model = new PositionMargin();

    /**
     * Model tests for PositionMargin
     */
    @Test
    void testPositionMargin() {
        // TODO: test PositionMargin
    }

    /**
     * Test the property 'tradingSymbol'
     */
    @Test
    void tradingSymbolTest() {
        // TODO: test tradingSymbol
    }

    /**
     * Test the property 'totalMargin'
     */
    @Test
    void totalMarginTest() {
        // TODO: test totalMargin
    }

    /**
     * Test the property 'spanMargin'
     */
    @Test
    void spanMarginTest() {
        // TODO: test spanMargin
    }

    /**
     * Test the property 'exposureMargin'
     */
    @Test
    void exposureMarginTest() {
        // TODO: test exposureMargin
    }

    /**
     * Test the property 'additionalMargin'
     */
    @Test
    void additionalMarginTest() {
        // TODO: test additionalMargin
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'exchange'
     */
    @Test
    void exchangeTest() {
        // TODO: test exchange
    }

}
