/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SecurityDTOV1
 */
class SecurityDTOV1Test {
    private final SecurityDTOV1 model = new SecurityDTOV1();

    /**
     * Model tests for SecurityDTOV1
     */
    @Test
    void testSecurityDTOV1() {
        // TODO: test SecurityDTOV1
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'isin'
     */
    @Test
    void isinTest() {
        // TODO: test isin
    }

    /**
     * Test the property 'sector'
     */
    @Test
    void sectorTest() {
        // TODO: test sector
    }

    /**
     * Test the property 'industry'
     */
    @Test
    void industryTest() {
        // TODO: test industry
    }

    /**
     * Test the property 'marketCapValue'
     */
    @Test
    void marketCapValueTest() {
        // TODO: test marketCapValue
    }

    /**
     * Test the property 'marketCapType'
     */
    @Test
    void marketCapTypeTest() {
        // TODO: test marketCapType
    }

}
