/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SecuritySearchRequestV1
 */
class SecuritySearchRequestV1Test {
    private final SecuritySearchRequestV1 model = new SecuritySearchRequestV1();

    /**
     * Model tests for SecuritySearchRequestV1
     */
    @Test
    void testSecuritySearchRequestV1() {
        // TODO: test SecuritySearchRequestV1
    }

    /**
     * Test the property 'symbols'
     */
    @Test
    void symbolsTest() {
        // TODO: test symbols
    }

    /**
     * Test the property 'isin'
     */
    @Test
    void isinTest() {
        // TODO: test isin
    }

    /**
     * Test the property 'sector'
     */
    @Test
    void sectorTest() {
        // TODO: test sector
    }

    /**
     * Test the property 'industry'
     */
    @Test
    void industryTest() {
        // TODO: test industry
    }

    /**
     * Test the property 'index'
     */
    @Test
    void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'query'
     */
    @Test
    void queryTest() {
        // TODO: test query
    }

}
