/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.marketdata.model;

import com.am.marketdata.model.Metadata;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StockData
 */
class StockDataTest {
    private final StockData model = new StockData();

    /**
     * Model tests for StockData
     */
    @Test
    void testStockData() {
        // TODO: test StockData
    }

    /**
     * Test the property 'priority'
     */
    @Test
    void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'identifier'
     */
    @Test
    void identifierTest() {
        // TODO: test identifier
    }

    /**
     * Test the property 'series'
     */
    @Test
    void seriesTest() {
        // TODO: test series
    }

    /**
     * Test the property 'open'
     */
    @Test
    void openTest() {
        // TODO: test open
    }

    /**
     * Test the property 'dayHigh'
     */
    @Test
    void dayHighTest() {
        // TODO: test dayHigh
    }

    /**
     * Test the property 'dayLow'
     */
    @Test
    void dayLowTest() {
        // TODO: test dayLow
    }

    /**
     * Test the property 'lastPrice'
     */
    @Test
    void lastPriceTest() {
        // TODO: test lastPrice
    }

    /**
     * Test the property 'previousClose'
     */
    @Test
    void previousCloseTest() {
        // TODO: test previousClose
    }

    /**
     * Test the property 'change'
     */
    @Test
    void changeTest() {
        // TODO: test change
    }

    /**
     * Test the property 'totalTradedVolume'
     */
    @Test
    void totalTradedVolumeTest() {
        // TODO: test totalTradedVolume
    }

    /**
     * Test the property 'stockIndClosePrice'
     */
    @Test
    void stockIndClosePriceTest() {
        // TODO: test stockIndClosePrice
    }

    /**
     * Test the property 'totalTradedValue'
     */
    @Test
    void totalTradedValueTest() {
        // TODO: test totalTradedValue
    }

    /**
     * Test the property 'yearHigh'
     */
    @Test
    void yearHighTest() {
        // TODO: test yearHigh
    }

    /**
     * Test the property 'ffmc'
     */
    @Test
    void ffmcTest() {
        // TODO: test ffmc
    }

    /**
     * Test the property 'yearLow'
     */
    @Test
    void yearLowTest() {
        // TODO: test yearLow
    }

    /**
     * Test the property 'nearWKH'
     */
    @Test
    void nearWKHTest() {
        // TODO: test nearWKH
    }

    /**
     * Test the property 'nearWKL'
     */
    @Test
    void nearWKLTest() {
        // TODO: test nearWKL
    }

    /**
     * Test the property 'perChange365d'
     */
    @Test
    void perChange365dTest() {
        // TODO: test perChange365d
    }

    /**
     * Test the property 'date365dAgo'
     */
    @Test
    void date365dAgoTest() {
        // TODO: test date365dAgo
    }

    /**
     * Test the property 'chart365dPath'
     */
    @Test
    void chart365dPathTest() {
        // TODO: test chart365dPath
    }

    /**
     * Test the property 'date30dAgo'
     */
    @Test
    void date30dAgoTest() {
        // TODO: test date30dAgo
    }

    /**
     * Test the property 'perChange30d'
     */
    @Test
    void perChange30dTest() {
        // TODO: test perChange30d
    }

    /**
     * Test the property 'chart30dPath'
     */
    @Test
    void chart30dPathTest() {
        // TODO: test chart30dPath
    }

    /**
     * Test the property 'chartTodayPath'
     */
    @Test
    void chartTodayPathTest() {
        // TODO: test chartTodayPath
    }

    /**
     * Test the property 'meta'
     */
    @Test
    void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'pChange'
     */
    @Test
    void pChangeTest() {
        // TODO: test pChange
    }

}
