apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  labels:
    app: influxdb
    service: market-data
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb2/meta"
    
    [data]
      dir = "/var/lib/influxdb2/data"
      wal-dir = "/var/lib/influxdb2/wal"
      series-id-set-cache-size = 100
    
    [http]
      bind-address = ":8086"
      auth-enabled = true
      log-enabled = true
      write-tracing = false
      pprof-enabled = false
      
    [logging]
      level = "info"
      
    [retention]
      check-interval = "30m"
