apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
    service: market-data
spec:
  ports:
  - port: 8086
    targetPort: 8086
    name: api
  selector:
    app: influxdb
