server:
  ha:
    enabled: false
  standalone:
    enabled: true
  service:
    enabled: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"
  dataStorage:
    enabled: true
    size: 5Gi
    storageClass: managed-csi-premium
  auditStorage:
    enabled: true
    size: 5Gi
    storageClass: managed-csi-premium
  dev:
    enabled: false

ui:
  enabled: true
  serviceType: LoadBalancer

injector:
  enabled: true