# External API Configuration
external:
  api:
    enabled: true
    retry:
      max-attempts: 3
      base-delay-ms: 1000
    http:
      connect-timeout-ms: 5000
      socket-timeout-ms: 30000
      max-conn-total: 50
      max-conn-per-route: 20
    health-check:
      enabled: true
      interval-ms: 300000
    endpoints:
      auto-load: true
      config-location: classpath:application-endpoints.yml

# TradeBrain API Configuration
trade-brain:
  baseUrl: ${TRADEBRAIN_BASE_URL:https://api.tradebrain.com}
  api:
    indexAll: ${TRADEBRAIN_INDEX_ALL_PATH:/api/market/indices}
  headers:
    userAgent: "AM-MarketData/1.0"
    accept: "application/json"
    acceptLanguage: "en-US,en;q=0.9"

# Resilience4j Configuration
resilience4j:
  retry:
    instances:
      externalApiRetry:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
  circuitbreaker:
    instances:
      externalApiCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
