# API Endpoints Configuration
endpoints:
  # TradeBrain API Endpoints
  tradebrain:
    base-url: ${TRADEBRAIN_BASE_URL:https://api.tradebrain.com}
    endpoints:
      - id: tradebrain.index
        name: TradeBrain Indices
        path: /api/index/all
        method: GET
        health-check-enabled: true
      - id: tradebrain.stock.index
        name: TradeBrain Stock Indices
        path: /api/market/stock/indices
        method: GET
        health-check-enabled: true
    headers:
      User-Agent: AM-MarketData/1.0
      Accept: application/json
      Accept-Language: en-US,en;q=0.9
