# Base Configuration
base:
  resource: api/company
  base-url: ${TRADEBRAIN_BASE_URL:https://portal.tradebrains.in}
  indices-path: /api/index/all

# TradeBrain API Configuration
trade-brain:
  baseUrl: ${base.base-url}
  api:
    indices:
      all: ${TRADEBRAIN_INDICES_ALL_PATH:${base.indices-path}}
    company:
      stock:
        details: ${base.base-url}/${base.resource}/stock/{symbol}
        historical: ${base.base-url}/${base.resource}/stock/historical/{symbol}
        technical: ${base.base-url}/${base.resource}/stock/technicals/{symbol}
        shareholding: ${base.base-url}/${base.resource}/stock/shareholding/{symbol}
        heatmap: ${base.base-url}/${base.resource}/stock/heatmap/{symbol}
      profile:
        short-details: ${base.base-url}/${base.resource}/short/details/{symbol}
        key-metrics: ${base.base-url}/${base.resource}/keymetrics/{symbol}
        company-profile: ${base.base-url}/${base.resource}/profile/info/{symbol}
        insights: ${base.base-url}/${base.resource}/insights/{symbol}
        corporate-action: ${base.base-url}/${base.resource}/corporate/actions/{symbol}
        shareholding: ${base.base-url}/${base.resource}/detailed/shareholding/{symbol}
        score: ${base.base-url}/${base.resource}/portal/score/{symbol}
        board-of-directors: ${base.base-url}/${base.resource}/board/directors/{symbol}
        top-shareholders: ${base.base-url}/${base.resource}/top/shareholders/quaters/{symbol}
      financial:
        dividends: ${base.base-url}/${base.resource}/ratios/factsheet/dividends/{symbol}/standalone
        half-yearly-statement: ${base.base-url}/${base.resource}/half-yearly/statement/{symbol}/standalone
        quarterly-results-standalone: ${base.base-url}/${base.resource}/quarterly-results/statement/{symbol}/standalone
        profit-and-loss-standalone: ${base.base-url}/${base.resource}/profit-and-loss/statement/{symbol}/standalone
        balance-sheet-standalone: ${base.base-url}/${base.resource}/balance/sheet/{symbol}/standalone
        cash-flow-standalone: ${base.base-url}/${base.resource}/cash-flow/statement/{symbol}/standalone
      documents:
        credit-rating: ${base.base-url}/${base.resource}/credit-rating/{symbol}
        industry-peers: ${base.base-url}/${base.resource}/sector/industry/peers/{symbol}
      reports:
        director-report: ${base.base-url}/${base.resource}/director/report/{symbol}
        chairman-report: ${base.base-url}/${base.resource}/chairman/report/{symbol}
        auditor-report: ${base.base-url}/${base.resource}/auditors/report/{symbol}
        annualReports: ${base.base-url}/${base.resource}/documents/annual-reports/{symbol}
  headers:
    userAgent: "AM-MarketData/1.0"
    accept: "application/json"
    acceptLanguage: "en-US,en;q=0.9"
